### ISSUE TITLE
page.clickAndWaitForNavigation bug

### ISSUE THREAD

**Issue by transitive-bullshit** [berstend/puppeteer-extra#1]
In [page.clickAndWaitForNavigation](https://github.com/berstend/puppeteer-extra/blob/d595e51f001579ac6fd69bb32b2b8344be495638/lib/PuppeteerExtra.js#L315), you're performing the click twice and there's a console.log in there, which both seem to be by accident.

I believe lines 315-316 should be removed.

**Comment by berstend** [comment]
Hah, good catch - the whole method doesn't really fit in though. 😅 

Will either remove it or outsource it properly into it's own package when #2 is finalized :)

**Comment by berstend** [comment]
The plugin version is done:
https://github.com/berstend/puppeteer-extra/tree/rewrite/packages/puppeteer-extra-plugin-click-and-wait
