### ISSUE TITLE
Python version?

### ISSUE THREAD

**Issue by virg1n** [berstend/puppeteer-extra#105]
I'd like to know if there's a Python version of this.

Thanks!

**Comment by humorwang** [comment]
hi, this project is node.js.not pyton.

**Comment by berstend** [comment]
@virg1n `puppeteer-extra` is an addition to the canonical `puppeteer` implementation, which is written in NodeJS. :)

There are however 3rd party `puppeteer` implementations for other languages. I recall that a while back someone mentioned here that they're working on a port of `puppeteer-extra` to C# but I don't know about the status on this one.

Note: If you need specific functionality take a look into the source code of the Plugins, it should be pretty straight forward to use them in other languages (as most plugins evaluate JS code in the browser, which is the same regardless of what language the driver is written in).

There are no plans to support anything other than NodeJS, as it's the primary language for `puppeteer` related things. :)
