### ISSUE TITLE
Plugins name's easy to detect chrominium

### ISSUE THREAD

**Issue by sam4652** [berstend/puppeteer-extra#106]
Hello, 

I think it is easy to detect chrominium and block access to Website.
Is it possible to edit their names or delete this plugins ? 
Chromium PDF Plugin
Chromium PDF Viewer

Thank you for your work.

**Comment by berstend** [comment]
Hi there, this should already be done by the [`navigator.plugins`](https://github.com/berstend/puppeteer-extra/blob/master/packages/puppeteer-extra-plugin-stealth/evasions/navigator.plugins/index.js) plugin?

![image](https://user-images.githubusercontent.com/1368633/70852167-8566e300-1e9e-11ea-815b-43b1e0d8c85b.png)

Could you provide a small test case with the issue you're having?

**Comment by sam4652** [comment]
Hi, 
I have the same as you with chromium and headful : 
https://github.com/berstend/puppeteer-extra/blob/master/packages/puppeteer-extra-plugin-stealth/stealthtests/_results/headful-chromium-vanilla.js.png
![pptr](https://user-images.githubusercontent.com/58831409/70989784-82e5d280-20c4-11ea-826b-84cbf7c5b90b.PNG)

Ok with Chrome instead of chromium.

**Comment by berstend** [comment]
I don't understand what the issue is. :) I made the spoofed plugins to resemble regular Google Chrome. Please re-open with more info if this is still an issue.

**Comment by trnj** [comment]
> I don't understand what the issue is. :) I made the spoofed plugins to resemble regular Google Chrome. Please re-open with more info if this is still an issue.

For some reason, in Headless True mode it shows Chromium PDF Plugin.
In Headless False - as expected  Chrome PDF Plugin

Anyway, thank you for the plugin!
