### ISSUE TITLE
CHR_Memory Fails With User-Agent

### ISSUE THREAD

**Issue by LasalM** [berstend/puppeteer-extra#108]
Hello,

When testing on [bot.sannysoft.com](bot.sannysoft.com) I get CHR_MEMORY FAIL if I've set a custom user-agent. I searched through Antoine Vastel's docs ([https://github.com/antoinevastel/fpscanner](https://github.com/antoinevastel/fpscanner)) and it looks like CHR_Memory is based on navigator.DeviceMemory. 

Oddly enough, when I don't set a custom user-agent and instead modify the DeviceMemory the issue is not triggered. For instance,`
await this.page.evaluateOnNewDocument(() => {
         Object.defineProperty(navigator, 'deviceMemory', {
         get: () => 1000000,
    });
 }` does not trigger the warning. I've likewise tried to prevent its triggering by modifying the DeviceMemory to 1,2,3,4,5,6,7, and 8, none of which have worked. Is there any way to bypass this issue?

PS My user-agent is `Chrome/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/56.0.2924.75 Mobile/14E5239e Safari/602.11`

EDIT: I forgot to mention, this is an issue pertinent to puppeteer-extra-plugin-stealth.

**Comment by berstend** [comment]
Mhm, can't reproduce. Could you try with the latest stealth plugin? We've added quite a lot of fixes. Please re-open if you still have this issue.

**Comment by LasalM** [comment]
I’ll try. Way to go! Keep up the hard work.

**Comment by rainbowhat** [comment]
@berstend I'm still trying to reproduce this , basically it's triggered when you use a smaller screen user agent. 

`page.setUserAgent("Mozilla/5.0 (iPad; CPU OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/16B92 [FBAN/FBIOS;FBAV/196.0.0.52.95;FBBV/129677436;FBDV/iPad8,7;FBMD/iPad;FBSN/iOS;FBSV/12.1;FBSS/2;FBCR/;FBID/tablet;FBLC/de_DE;FBOP/5;FBRV/0]")
        page.setUserAgent("Mozilla/5.0 (Linux; Android 7.0; Pixel C Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/52.0.2743.98 Safari/537.36")`
