### ISSUE TITLE
Plugin fails check and is detected on a website

### ISSUE THREAD

**Issue by eradaningol** [berstend/puppeteer-extra#109]
Hi! 

I've tried to open this link using extra-plugin-stealth but it always sends a captcha when I do, both in headful and headless state. However, opening it regularly in browser always brings back a page with data. I don't think it depends on some user behavior check, does it, if I only open same page one at a time?

https://connectonline.asic.gov.au/RegistrySearch/faces/landing/panelSearch.jspx?searchText=000016722&searchType=OrgAndBusNm&_adf.ctrl-state=krh719cg1_15

**Comment by berstend** [comment]
Hard to say, debugging if this site is using specific detection methods is time-consuming so I won't be able to do that. :)

If in doubt I recommend using a headful Google Chrome (as opposed to Chromium).

Let me know if you find specifics I can look into.
