### ISSUE TITLE
Flash on AWS Lambda

### ISSUE THREAD

**Issue by cirdes** [berstend/puppeteer-extra#11]
I'm using puppeteer extra flash plugin locally but when I try to run on Aws its seems that flash is not working. Any ideas how to get it working?

**Comment by berstend** [comment]
I assume you're using Chromium when running on AWS Lambda? 

In that case you must ensure to set`pluginPath` and `pluginVersion` as per [documentation](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-flash#plugin) (AFAIR you can fetch resources from S3 buckets).

**Comment by berstend** [comment]
PS: Also flash won't work in headless mode (as per documentation), so you need to ensure to run a headful chromium instance on Lambda with the flash `pluginPath` defined.

**Comment by cirdes** [comment]
@berstend, I'm using Chromium on AWS Lambda and running on headful mode. But AWS Lambda does not have the Flash Player binaries, I have tried to download and put the binaries on the project but flash was not running. I don't know if my binaries was wrong or if I need another dependence.

Fortunately I was able to workaround without flash so I will close the issue.

Thanks so much!
