### ISSUE TITLE
solveRecaptcha is not working for google.com search results

### ISSUE THREAD

**Issue by anupam587** [berstend/puppeteer-extra#111]
i am trying to search for certain query in google.com using headless chrome.
Then it is redirecting me to recaptcha page. But above plugin is unable to fix/bypass the recaptcha.
following is my code which I used to bypass.

const puppeteer = require('puppeteer-extra');
const RecaptchaPlugin = require('puppeteer-extra-plugin-recaptcha');
puppeteer.use(
    RecaptchaPlugin({
      provider: { id: '2captcha', token: 'XXXXXXX' },
      visualFeedback: true 
    })
  );

(async () => {
    const browser = await puppeteer.launch({headless: true, args: ['--incognito']});
    try{ 
        const page = await browser.newPage();
        await page.goto('https://www.google.com', { waitUntil: 'networkidle0' })
        await page.type('input[name=q]', 'inurl:wedding-resources')
        await page.keyboard.press('Enter');
        await page.waitForNavigation();
        await page.solveRecaptchas();
        await page.screenshot({path: 'initial.png', fullPage: true});
    }catch(err){
        console.log(err);
        browser.close();
     }
)();

please let me know asap the issue with this code

**Comment by berstend** [comment]
Can you try again with `puppeteer-extra-plugin-recaptcha@3.1.9`?

If this doesn't fix it feel free to reopen this issue, but please provide debug output (documented in the readme). :)
