### ISSUE TITLE
movementX and movementY always = 0 

### ISSUE THREAD

**Issue by sam4652** [berstend/puppeteer-extra#113]
Hello,
In puppeteer, when calling page.mouse.move, movementX and movementY never changes. 
Some WebSite use this values to block acces. 
If anyone will have a solution ? 
Thanks.

**Comment by berstend** [comment]
Can you make a test case please? Also this might be better suited for the upstream puppeteer project.

**Comment by berstend** [comment]
Did you add `page.setViewport({ width: xxx, height: xxx });` as well? According to https://github.com/puppeteer/puppeteer/issues/4690 that's needed to make mouse movements work in headless.

Closing for now, please provide test code if you want to me to investigate this further. :)
