### ISSUE TITLE
await page.solveRecaptchas() timeout

### ISSUE THREAD

**Issue by gcleaves** [berstend/puppeteer-extra#115]
Hello, I've been using this plugin fairly successfully for a couple of months. But recently my script hangs on `await page.solveRecaptchas()`. Is there a way to assign a timeout to this command? Thanks!

**Comment by gcleaves** [comment]
I'm working around the issue by waiting for a button that gets activated upon solving the captcha.

    page.solveRecaptchas();
    await page.waitForSelector('#buttonId:not([disabled])',{timeout:180000})

But I'd like to hear of a better solution if there is one.

**Comment by berstend** [comment]
Mhm, would be interesting to understand why it's hanging. Could you run your script with debug output enabled (documented in the readme)?

For the time being this might be a cleaner way to add timeout support:

```js

const delay = (ms) => new Promise(_ => setTimeout(_, ms))

const race = await Promise.race([page.solveRecaptchas(), delay(60 * 1000)])
```
