### ISSUE TITLE
Immediatly recognized

### ISSUE THREAD

**Issue by 1973puppeteer** [berstend/puppeteer-extra#118]
The website that recognizes and stops the script is: www.leboncoin.fr

It used to work, but it looks that website found a way to detect it immediatly

It looks like it is related with detection some chrome-extension.

> tags.js:2 GET chrome-extension://invalid/ net::ERR_FAILED

**Comment by berstend** [comment]
This website is one hot mess, even in regular Chrome their scripts are failing.

Please provide more info with what you mean by "The website that recognizes and stops the script".

Image you would be me and the info you mentioned would be all you had to go on, that's very time-consuming. :)
