### ISSUE TITLE
Stealth mode: User agent reveals Raspbian Chromium

### ISSUE THREAD

**Issue by tylerburleigh** [berstend/puppeteer-extra#119]
I am using `puppeteer-extra-plugin-stealth` on a Raspberry Pi with Raspbian OS installed. My understanding is that this plugin has a shim for `puppeteer-extra-plugin-anonymize-ua` which defaults to setting the user agent to a Windows platform.

When I visit `https://bot.sannysoft.com` it detects that I'm using Raspbian Chromium, which defeats some of the stealthiness:

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Raspbian Chromium/74.0.3729.157 Chrome/74.0.3729.157 Safari/537.36`

I had to install a specific version of Chromium for Raspbian, so I'm not using the stock version. I'm guessing this is why. Is there a way to spoof this detail in the user-agent string?

**Comment by tylerburleigh** [comment]
Ok, so it looks like I can use a custom UA function like this to remove the Raspbian part:

```
puppeteer.use(require('puppeteer-extra-plugin-anonymize-ua')({
  customFn: (ua) => ua.replace('Raspbian Chromium/74.0.3729.157', '')})
)
```

It's interesting that by default, the UA ends up with two Chrome strings:
`Raspbian Chromium/74.0.3729.157`
and 
`Chrome/74.0.3729.157`

I wonder if this can be programmatically detected and fixed when the `puppeteer-extra-plugin-anonymize-ua` plugin is initialized?

**Comment by tylerburleigh** [comment]
Something else I noticed: Comparing it with my "real" Chrome browser, Chromium on Raspbian ends up having an older chrome version. Current is `Chrome/79.0.3945.88` but Raspbian has `Chrome/74.0.3729.157`. 

Would it increase the stealth to replace with the latest Chrome version in the UA? Chrome is pretty aggressive about getting users to update, so I imagine having an older browser version might be a clue that someone is using a bot. 

Just a thought.

**Comment by jozsi** [comment]
Regarding your last concern, see #35 🙌

**Comment by berstend** [comment]
> Would it increase the stealth to replace with the latest Chrome version in the UA?

Most likely. :) Currently it's possible to overwrite the UA to anything using the `customFn` (as you noticed), so I'm closing this in favor of #35 for now. But we can definitely improve on the default values here.
