### ISSUE TITLE
pluginPath?

### ISSUE THREAD

**Issue by EddieOne** [berstend/puppeteer-extra#12]
The pluginPath is required? Do I need to detect os and give it a .dll, .so, or .plugin file?

Thanks

**Comment by berstend** [comment]
Hey there,
if you're not specifically using the Google branded Chrome/Chrome Canary versions but pupeteer with Chromium you need to specify those two things (as Chromium doesn't ship with flash).

The plugin is dependent on the host system you run the browser on.

E.g. on macOS you'd find the flash plugin of Google Chrome here:
```
/Users/bob/Library/Application Support/Google/Chrome/PepperFlash/29.0.0.171/PepperFlashPlayer.plugin
```

You can find the flash plugin path for your system using `chrome://version/`

Let me know if you have further questions, closing this for now.

Cheers
