### ISSUE TITLE
2captcha software catalog

### ISSUE THREAD

**Issue by jozsi** [berstend/puppeteer-extra#123]
Hello,

You could add `pupeteer-extra` to the 2captcha software catalog, it perfectly fits the `Scripts & libraries` category. Besides the benefit of being listed, it has 10% reward program that can be sent either to the developer or returned to the customers' balance.

The underlying library, `2captcha-api` does not leverage this, so there wouldn't be any conflict.

Take care!

**Comment by berstend** [comment]
@jozsi Good idea, just submitted the plugin to the library (awaiting moderation). Thanks for the hint! :)
