### ISSUE TITLE
CI broken

### ISSUE THREAD

**Issue by jozsi** [berstend/puppeteer-extra#124]
The CI builds are broken because of the following error:
`../../node_modules/ava/index.d.ts:5:10 - error TS2339: Property 'observable' does not exist on type 'SymbolConstructor'.`

Interestingly, I can't reproduce it on my local machine, might be a TravisCI thing. It also exists on `master`.

Quick references:
- https://github.com/avajs/ava/issues/2151
- https://github.com/googleapis/nodejs-pubsub/issues/842

**Comment by berstend** [comment]
Yeah, super weird issue. 😄 Was able to fix it (and some others) in #128.
