### ISSUE TITLE
ebay still detects stealth mode

### ISSUE THREAD

**Issue by hems** [berstend/puppeteer-extra#126]
Ebay API is very unfriendly, so instead of using their API I'm trying to write a script that logs in and buy items for me.

Unfortunately it seems instead of making an easy to use API they are spending their resources in detecting bots :(

````js
const puppeteer = require('puppeteer-extra')

// Add stealth plugin and use defaults (all tricks to hide puppeteer usage)
const StealthPlugin = require('puppeteer-extra-plugin-stealth')
puppeteer.use(StealthPlugin())

const work = async () => {
  browser = await puppeteer.launch({headless: true})

  const page = await browser.newPage()

  await page.setViewport({ width: 800, height: 600 })

  await page.goto('https://signin.ebay.co.uk/ws/ebayisapi.dll?signin');

  await page.waitFor(5000)

  await page.screenshot({path: 'example.png'});

  await browser.close();

}

work()
````

results in:

![example](https://user-images.githubusercontent.com/27327/71755093-0eab7d00-2e81-11ea-851d-0c59e3921c41.png)

**Comment by quetzalsly** [comment]
Did you try this without headless? just curious.

**Comment by berstend** [comment]
Yeah, would second @quetzalsly question about the difference between headless/headful. The stealth plugin can't help with e.g. the IP address you're using being flagged or blacklisted.

How soon is this page popping up, immediately or after several sign-ins?

**Comment by hems** [comment]
> Yeah, would second @quetzalsly question about the difference between headless/headful. The stealth plugin also can't help with e.g. the IP address you're using being flagged or blacklisted.

shall i use `headful: true` instead of `headless: true` as options?

sorry i'm new to this..

> How soon is this page popping up, immediately or after several sign-ins?

on the first attempt it poped up..

**Comment by berstend** [comment]
No problem. :)

To make the browser "headful" you would just want to disable headless (setting `headless: false` as an option).

Are you running this from your local machine or somewhere in the Cloud? The IP address you're using might've been flagged as well.

**Comment by berstend** [comment]
@hems I did some quick testing and it seems they really dislike the 800x600 resolution. Try removing `await page.setViewport({ width: 800, height: 600 })`. :)

**Comment by hems** [comment]
> @hems I did some quick testing and it seems they really dislike the 800x600 resolution. Try removing `await page.setViewport({ width: 800, height: 600 })`. :)

haha daaaang! i suspected that could have been very suspicious to have such old school resolution.. but I forgot to remove that!

thanks a lot for looking into it, hopefully, this will sort me out!

I can't believe how ebay makes it hard for their users, all I wanted to do is to buy look for items that i would personally like to buy but rarely show up on ebay.. They don't provide a simple API for that, so i might as well use puppeteer..

**Comment by berstend** [comment]
Closing for now, let me know if you find any issues with the stealth plugin :)
