### ISSUE TITLE
chrome-aws-lambda + puppeteer cluster in puppeteer-extra

### ISSUE THREAD

**Issue by sj-log** [berstend/puppeteer-extra#127]
I was wondering, Is this possible to make?

I need to scrap on 3 pages but need more speed.
My puppeteer takes 5-6 sec for a result.
[but I found how can get more improvement on speed. ](https://github.com/puppeteer/puppeteer/issues/3120#issuecomment-450575911)
the chrome-aws-lambda seems the fastest one to use with nodeJs.

Please let me know if it is possible!
Thank you!

**Comment by berstend** [comment]
I don't see why not :) The readme provides examples for both, feel free to tinker with them and see if you can merge them. Let us know if you end up with a combination that works and speeds things up.
