### ISSUE TITLE
Distil network detection

### ISSUE THREAD

**Issue by Tyron199** [berstend/puppeteer-extra#129]
Anyone able to load a ticketmaster url ?
Example: [https://www1.ticketmaster.com/post-malone-runaway-tour/event/0600576CC602B2F4](url)

Instantly blocked
![chrome_y7VQR6eQTa](https://user-images.githubusercontent.com/6433549/71874431-2aac5a00-30df-11ea-924f-fbdf5821ea63.png)

I noticed this error, which only happens through puppeteer but not on normal chrome:

![chrome_RIy2X713oe](https://user-images.githubusercontent.com/6433549/71876344-c0e27f00-30e3-11ea-86e5-35ee41a362ff.png)

So i think the block might happen because that call fails.
Here's the code doing the fingerprinting
https://pastebin.com/Kd8PMH1a

**Comment by Tyron199** [comment]
So i completely turned off the stealth plugin and i get through fine.
Must be one of the evasions being detected.

**Comment by quetzalsly** [comment]
Why did you close this? the stealth plugin should work with this, its a good issue to have fixed.
