### ISSUE TITLE
URL not working with plugin-stealth

### ISSUE THREAD

**Issue by xiadongdev** [berstend/puppeteer-extra#136]
This URL https://www.rogers.com/web/consumer/ignite-bundles/get-iptv works fine when not using plugin-stealth, but doesn't work with the plugin:
```
import puppeteer from "puppeteer-extra";
import pluginStealth from "puppeteer-extra-plugin-stealth";

puppeteer.use(pluginStealth());
const browser = await puppeteer.launch()
const page = await browser.newPage()
await page.goto('https://www.rogers.com/web/consumer/ignite-bundles/get-iptv')
await page.screenshot({
    path: 'full.png',
    fullPage: true
})
await browser.close()
```

The error is:
```JS page error on website https://www.rogers.com/web/consumer/ignite-bundles/get-iptv = Error: TypeError: Illegal invocation```

**Comment by Niek** [comment]
This was fixed in https://github.com/berstend/puppeteer-extra/pull/130 (released as 2.4.9), are you sure you have the latest version?

**Comment by xiadongdev** [comment]
The new release works, thanks Niek!

**Comment by xiadongdev** [comment]
I have to reopen this issue because the newest version doesn't work with the following sites:
cnn.com, and wsj.com

For example, cnn.com should look like this:
<img width="300" alt="Screen Shot 2020-01-10 at 3 45 54 PM" src="https://user-images.githubusercontent.com/47586175/72193892-5b7ede80-33c0-11ea-9d8b-eb4b109042cb.png">

But when using the plugin, it looks like this (only an ad on a blank page):
<img width="300" alt="Screen Shot 2020-01-10 at 3 46 57 PM" src="https://user-images.githubusercontent.com/47586175/72193932-76515300-33c0-11ea-9517-cde6631674ca.png">

And the error was ```Error: SyntaxError: Unexpected token ','```

Thank you in advance for looking into this!

**Comment by Niek** [comment]
That's the same issue as https://github.com/berstend/puppeteer-extra/issues/137 - disabling iframe.contentWindow evasion helps for now.

**Comment by xiadongdev** [comment]
> That's the same issue as #137 - disabling iframe.contentWindow evasion helps for now.

Hi Niek, thank you for your help. I've tried 
```
puppeteer.use(pluginStealth());
pluginStealth.enabledEvasions.delete("iframe.contentWindow")
``` 
But it produced an error: 
```Property 'enabledEvasions' does not exist on type '(opts?: { enabledEvasions?: Set<string>; }) => StealthPlugin'.```

I'm using typescript, and I couldn't find docs on this, not sure how should I fix this?

**Comment by Niek** [comment]
You need to do something like:
```javascript
let ps = pluginStealth();
ps.enabledEvasions.delete('iframe.contentWindow');
puppeteer.use(ps);
```

**Comment by xiadongdev** [comment]
Thanks Niek, this solution works
