### ISSUE TITLE
webdriver is still true when using newest Stealth Plugin

### ISSUE THREAD

**Issue by lehungson5011** [berstend/puppeteer-extra#138]
Hi man!
When using puppeteer-extra-plugin-stealth 2.4.9, webdriver is still true. 
It seem like function defineProperty(window, 'navigator', ....) is run before web document attach the funtion get webdriver. So it cannot amend the value of webdriver. Please help!

**Comment by berstend** [comment]
Could you provide reproducible demo code?

Our automated tests run fine:
https://github.com/berstend/puppeteer-extra/blob/master/packages/puppeteer-extra-plugin-stealth/evasions/navigator.webdriver/index.test.js#L14-L21

**Comment by lehungson5011** [comment]
man, I open the puppeteer dev tool, and then type to console the word "navigator", and then find out that webdriver is still true

**Comment by berstend** [comment]
Do you mind sharing the full code? Please keep in mind that this is Github, so it's expected that if an issue is reported every effort should be taken by that person to make it easy for others to confirm/reproduce the issue quickly. :)

Maintaining this project takes a lot of time, so I kindly ask that you invest a bit of yours to help me reproduce the problem you've reported quickly.

**Comment by lehungson5011** [comment]
this is my issue man: https://docs.google.com/document/d/124HveZ4_GuS0vRJHvZEJ8xu4sep6vMTKDlW3brsDzAc/edit?usp=sharing

**Comment by Niek** [comment]
In your screenshot you can see you are looking at the wrong object - the target navigator one. If you just try ``'webdriver' in navigator`` or ``navigator.webdriver`` you'll see the hiding is working fine.

**Comment by lehungson5011** [comment]
man, can you please guide me some solution to bypass success Taobao slider captcha as I stated in issue B in the google doc file? It recognize bot so it refuse the sliding action.

**Comment by berstend** [comment]
Unfortunately this is out of the scope of an open-source project (and the free, volunteered support that we provide for it).

Commercial support is available upon request. :)

**Comment by lehungson5011** [comment]
Please guide me steps to request Commercial support. My email is lehungsonk49ftu@gmail.com
