### ISSUE TITLE
Question: only works with puppeteer <= 1.5.0?

### ISSUE THREAD

**Issue by aledbf** [berstend/puppeteer-extra#14]

**Comment by berstend** [comment]
These guys are moving fast! I'm looking into this now. :-)

**Comment by berstend** [comment]
@aledbf this if fixed now.
it was only a minor issue with the browser.onClose handler, the underlying API got removed (which is fine as onDisconnect now works reliably).

I'll incorporate your PR as well to test against the latest puppeteer versions.

**Comment by aledbf** [comment]
@berstend thank you for working so fast on this!
