### ISSUE TITLE
Window screen width/height values always stuck at default 800x600

### ISSUE THREAD

**Issue by themattrobinson** [berstend/puppeteer-extra#142]
Hey @berstend, thanks for a great package, and for helping us all out! 

Related to the puppeteer extra and stealth plugins, I am writing code that relies on the window.screen.width and window.screen.height values to be consistent, and more importantly, not be detectable by bot blockers.

No matter what I try, it seems that the "screen.width" and "screen.height" values are staying at the default of 800 width and 600 height when running on Lambda, though it seems to be set correctly when running locally.

I am running with headless mode set to true.

This is the "defaultViewport" object I'm setting:
`let defaultViewport  = {
    deviceScaleFactor  : 1,
    hasTouch        : false,
    height             : 1110,
    width              : 1920,
    isLandscape  : true,
    isMobile         : false,
  }
`

I tried both setting the "defaultViewport" when launching the Puppeteer Extra browser, as well as setting it on the new page created (page.setViewport). I am now setting them both to the same value, just to be sure.

Again, it seems to work when run locally, but when I run in Lambda, I am seeing that the screen dimensions are stuck at 800x600 (please see the attached bot test screenshots). What also doesn't make total sense to me is that even when I run it locally, the screen width/height is set to 1440 and 900.. I am running in headless mode with the viewport settings set above, so not sure where these values are coming from. I get the general difference between window and screen heights, but more importantly, it's the Lambda browser screen settings that are causing me the problems. 

Do you have any insight into why this may be? 
This may also be related to issue #100  (Umbrella device fingerprinting).

Let me know if you need to see my code, though it pretty much follows the example provided here: in particular this one that you provided: https://github.com/alixaxel/chrome-aws-lambda/issues/75#issuecomment-571212091

I've also attached a screenshotted snippet of my Lambda Cloudwatch logs, which shows some console errors from the bot.sanysoft.com page.

Thank you!

**Local Puppeteer stealth test screenshot**

![puppeteer-stealth-test-LOCAL](https://user-images.githubusercontent.com/29411538/72750776-c338e480-3b8b-11ea-8751-8a621ee38c4c.png)

------------------------------------------------------------------------------------

**Lambda Puppeteer stealth test screenshot**
![puppeteer-stealth-test-LAMBDA](https://user-images.githubusercontent.com/29411538/72750778-c633d500-3b8b-11ea-9c2c-b13b654ef581.png)

------------------------------------------------------------------------------------

**Lambda Puppeteer cloudwatch logs**
![puppeteer-stealth-lambda-cloudwatch-logs](https://user-images.githubusercontent.com/29411538/72750798-d0ee6a00-3b8b-11ea-84f3-cae11378d420.png)

**Comment by themattrobinson** [comment]
Also to notice (might be a clue?), see that the information below "Fp-collect info" in the Lambda screenshot is empty, whereas it's filled out completely in the local screenshot.

**Comment by berstend** [comment]
Closing as I guess this is obsolete by now
