### ISSUE TITLE
Make it work with puppeteer-web

### ISSUE THREAD

**Issue by elpaxel** [berstend/puppeteer-extra#145]
So how to make it work with [puppeteer-web](https://github.com/puppeteer/puppeteer/tree/master/utils/browser) ?
I will not post all the issues that I've got from browserify/webpack. One thing that is webpack workaround for dynamic require ([issue](https://github.com/berstend/puppeteer-extra/issues/93#issuecomment-564185702)) not suitable because I can't load node_modules folder into browser obviously. And using addExtra for all stealth evasions ([issue](https://github.com/berstend/puppeteer-extra/issues/93#issuecomment-563159177)) is uncomfortable.

**Comment by dannielibor** [comment]
Im also having a hard time using `puppeteer-extra` and `StealthPlugin()` with vue webpack im using electron as well
