### ISSUE TITLE
Blank screenshot with stealth plugin

### ISSUE THREAD

**Issue by xiadongdev** [berstend/puppeteer-extra#148]
Thank you for this great plugin, it works well most of the time but with this website: https://www.worldmarktheclub.com/, I got a blank screenshot when using the plugin:

```
import puppeteer from "puppeteer-extra";
import pluginStealth from "puppeteer-extra-plugin-stealth";
puppeteer.use(pluginStealth());
const browser = await puppeteer.launch()
const page = await browser.newPage()
await page.goto('https://www.worldmarktheclub.com/')
await page.screenshot({
    path: 'full.png',
    fullPage: true
})
await browser.close()
```
Without `puppeteer.use(pluginStealth());` it works fine, and there's no error.

Thank you in advance for looking into this!

**Comment by NazarKalytiuk** [comment]
try to wait a few seconds before screenshot, because the page is actually loaded, but not rendered when you try to take a screenshot.

**Comment by xiadongdev** [comment]
> try to wait a few seconds before screenshot, because the page is actually loaded, but not rendered when you try to take a screenshot.

Thanks for your suggestion, but adding a wait (~10s) doesn't work either, when the plugin is active, the page is loaded as an empty one

**Comment by cimm** [comment]
Same problem with the domain above and another one as well. Waiting doesn't help, the request is cancelled for some reason.

**Comment by brunogaspar** [comment]
With or without the plugin, the result is the same for me, empty screenshot.

This website is quite weird, even on normal Chrome/Firefox, i see a totally blank page for a second, so quite unsure if this will be easily solvable.

**Comment by berstend** [comment]
Closing until someone is enabling remote debugging and looking at the devtools/console output when stealth is enabled. :-)

**Comment by brunogaspar** [comment]
The website above, at least with the latest versions no longer gives me the issue reported on the OP.

However, i've found a few websites, that share similarities that have the same behaviour, although if i keep the browser open and do a refresh, the behaviour disappears.

I've tried to use remote debugging but i couldn't find anything out of the ordinary.
