### ISSUE TITLE
Unfortunately this is out of the scope of an open-source project (and the free, volunteered support that we provide for it).

### ISSUE THREAD

**Issue by lehungson5011** [berstend/puppeteer-extra#149]
Unfortunately this is out of the scope of an open-source project (and the free, volunteered support that we provide for it).

Commercial support is available upon request. :)

_Originally posted by @berstend in https://github.com/berstend/puppeteer-extra/issues/138#issuecomment-575922787_

**Comment by lehungson5011** [comment]
Please guide me steps to request Commercial support. My email is lehungsonk49ftu@gmail.com

**Comment by quetzalsly** [comment]
I also need to bypass aliexpress slider thing... please let me know if you solve it!

**Comment by a10kiloham** [comment]
> I also need to bypass aliexpress slider thing... please let me know if you solve it!

https://medium.com/@filipvitas/how-to-solve-geetest-slider-captcha-with-js-ac764c4e9905

**Comment by berstend** [comment]
We now have a channel in our discord server to request paid help:
https://github.com/berstend/puppeteer-extra/wiki/Scraping-Chat
