### ISSUE TITLE
Frame has no method solveRecaptchas

### ISSUE THREAD

**Issue by mikelam14** [berstend/puppeteer-extra#151]
I also encountered similar problem. I am solving recaptcha within the iframe, and I have located the correct frame. During debugging I think the Frame object has no solveRecaptchas() method at all, while the Page object still has.

Code is something like

`const puppeteer = require('puppeteer-extra'); const CaptchaPlugin = require('puppeteer-extra-plugin-recaptcha'); const captcha = CaptchaPlugin({ provider: { id: '2captcha', token: 'xxxxx' }, visualFeedback: true }); puppeteer.use(captcha);`

Then after finding frame and named as myframe;

`await myframe.solveRecaptchas();`

It then says myframe has no method solveRecaptchas()

I suspect I did something to the package so it affects the Frame behavior, but I reinstalled it and it still does the same. Or maybe it has been detected? Any ideas?

Thanks.

**Comment by berstend** [comment]
Solution: #353
