### ISSUE TITLE
Callback not issuing correctly

### ISSUE THREAD

**Issue by bilihjou** [berstend/puppeteer-extra#162]
Every time i use the pluguin, the callback is being transmited correctly but the webpage just ¿reloads?
Ataching video and code so you can try to help me out

```js
await page.goto(link, {waitUntil: 'load', timeout: 0})
await page.screenshot({path: 'screenshot.png'});

await page.solveRecaptchas().catch(function(error) {
    console.error(error);
});

await new Promise(r => setTimeout(r, 5000)).catch(function(error) {
    console.error(error);
});

await evaluateFirstPage(link).catch(function(error) {
    console.error(error);
});
```

https://vimeo.com/395266602

**Comment by ShiromMakkad** [comment]
I've got the same issue with PerimeterX on a different website. I'd guess this is some sort of defense mechanism by perimeterX. The callback function is called handleCaptcha('TOKEN'). I was able to use a different library to get the token from 2captcha and run the function using puppeteer exec, but it caused the same behavior. Running this exact function in the dev console worked though. 

Puppeteer has different behavior with the same function being run in the dev console vs the exec function. I'm not sure what's causing this and it would be nice if this had a second look.

**Comment by berstend** [comment]
> After solving the reCAPTCHAs the plugin will automatically detect and trigger their optional callback. This might result in forms being submitted and page navigations to occur, depending on how the site owner implemented the reCAPTCHA.

https://developers.google.com/recaptcha/docs/display#render_param

So it'd be worthwhile looking into this callback, maybe it's broken or malformed.

Check the `data-callback` attribute of the recaptcha tag.

**Comment by berstend** [comment]
You can also dig through `window.___grecaptcha_cfg.clients` to find the callback.

**Comment by ShiromMakkad** [comment]
I've already dug through that and found the callback which is `handleCaptcha()`. Running the command in the dev console works, so it's not broken or malformed. I linked to another issue which describes this in more detail and shows how strange this bug is at https://github.com/puppeteer/puppeteer/issues/6517.

**Comment by berstend** [comment]
@ShiromMakkad is there a demo site where I can see/test that captcha issue? You can also send me a PM on our discord.
