### ISSUE TITLE
CHR_Memory Fails With Custom User-Agent

### ISSUE THREAD

**Issue by rainbowhat** [berstend/puppeteer-extra#167]
Plugin : puppeteer-extra-plugin-stealth
Version : 2.4.9

```
const puppeteer = require('puppeteer-extra')
const StealthPlugin = require('puppeteer-extra-plugin-stealth')
puppeteer.use(StealthPlugin())

puppeteer.launch({ headless: true,args: ['--no-sandbox'] }).then(async browser => {
  console.log('Running tests..')
  const page = await browser.newPage()
  page.setUserAgent("Mozilla/5.0 (Linux; Android 7.0; Pixel C Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/52.0.2743.98 Safari/537.36")
  await page.goto('https://bot.sannysoft.com')
  await page.waitFor(5000)
  await page.screenshot({ path: 'testresult.png', fullPage: true })
  await browser.close()
  console.log(`All done, check the screenshot. ✨`)
})
```
**User Agent - Failed**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.246
Mozilla/5.0 (Linux; Android 7.0; Pixel C Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/52.0.2743.98 Safari/537.36

**User Agent - Passed**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

![testresult](https://user-images.githubusercontent.com/3077812/76276558-15ab9d00-62c1-11ea-81c1-2a2be76774ec.png)

**Comment by brunogaspar** [comment]
Can't reproduce this either.

Give it a try with the latest updates.

**Comment by pomcho555** [comment]
Reproduced that somehow on my laptop.

- User Agent - Failed
```Mozilla/5.0 (Linux; Android 7.0; SM-G930V Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36```
Same as @rainbowhat

- User Agent Passed 
Same as @rainbowhat

- version
puppeteer-extra: 6.14.9
