### ISSUE TITLE
Puppeteer doesn't launch on ubuntu with headless: false

### ISSUE THREAD

**Issue by shahroozme** [berstend/puppeteer-extra#169]
I'm trying to scrape a specific website (adidas) but to make it work I need to turn off the headless mode.
I'm not sure if this is a bug or that's how puppeteer works.

I tried to run puppeteer with `headless: false` on ubuntu server but got this error:
```
(node:25119) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
[25130:25130:0312/190512.907721:ERROR:browser_main_loop.cc(1512)] Unable to open X display.
[0312/190512.916195:ERROR:nacl_helper_linux.cc(308)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly
```

**Description**
```
OS: Ubuntu 18.04.4 LTS
Node.JS: v13.11.0
Puppeteer: 2.1.1
puppeteer-extra: 3.1.9
puppeteer-extra-plugin-stealth: 2.4.9
```

**Puppeteer config**
```
const browser = await puppeteer.launch({
  headless: false,
  args: [
    '--no-sandbox',
    '--disable-setuid-sandbox',
  ],
})
```

**Comment by brunogaspar** [comment]
If the same occurs without using the plugin (which seems to be the case by looking at your example above), then the problem is with Puppeteer, not this library.

From a very quick look i've found [this issue](https://github.com/puppeteer/puppeteer/issues/5385).

**Comment by shahroozme** [comment]
The same error occurs without the plugin,
Do you have any idea how can I solve this?
Or how adidas is preventing me from scraping the website with `headless: true`?

**Comment by Edison6351** [comment]
i have the same error in my code.and on my mac the code runs perfect :)

**Comment by MrPluto** [comment]
because you server has no X display, install and run it  follow [this](https://www.mattzeunert.com/2018/07/21/running-headful-chrome-on-ubuntu-server.html)
