### ISSUE TITLE
Puppeteer.launch is not a function

### ISSUE THREAD

**Issue by nongnoobjung** [berstend/puppeteer-extra#17]
Puppeteer.launch is not a function

puppeteer install already via npm

**Comment by berstend** [comment]
Looking into this, seems to be an issue with the `@next` version.

For now just use the stable `puppeteer@1.7.0` :-)

**Comment by berstend** [comment]
@nongnoobjung this has been fixed now, make sure to update `puppeteer-extra` to the latest `2.1.1` version.
