### ISSUE TITLE
Handle Transient Network Issues

### ISSUE THREAD

**Issue by allanchua101** [berstend/puppeteer-extra#171]
Sometimes, 2captcha is refusing connection and it crashes the whole node process (1 out of 100 times), to solve the problem. Adding an network issue management would improve the situation.

**Comment by brunogaspar** [comment]
If you happen to have a simple way to handle this, please submit a pull request with the additions, you're more than welcomed to do so :)

**Comment by berstend** [comment]
This has been fixed in a recent recaptcha plugin release. :-)
