### ISSUE TITLE
user agent still contains HeadlessChrome

### ISSUE THREAD

**Issue by brdeav39** [berstend/puppeteer-extra#179]
When trying to extract the user agent used, it still shows HeadlessChrome instead of just Chrome, when running in headless mode. Am I doing something wrong? Here is my code:

     

            const puppeteer = require('puppeteer-extra');
            const StealthPlugin = require('puppeteer-extra-plugin-stealth')
            puppeteer.use(StealthPlugin())
            var browser = await puppeteer.launch({
                args: [
                    '--no-sandbox',
                    '--disable-setuid-sandbox',
                    '--disable-dev-shm-usage',
                    '--disable-accelerated-2d-canvas',
                    '--no-first-run',
                    '--no-zygote',
                    '--disable-gpu',
                    '--proxy-server=http://' + host + ':' + port
                ],
                headless: true
            });
            var page = await browser.newPage();
            if(user != null)
                await page.authenticate({ username: user, password: pass });
            await page.goto(postBody.productUrl);
            var userAgent = await browser.userAgent();
            var cookies = await page.cookies();
            browser.close();

And here is the userAgent I get: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/80.0.3987.0 Safari/537.36`

**Comment by dat7e** [comment]
I had the same issue and found out puppeteer's `page.setUserAgent` wasn't working. Not sure why that though.

**Comment by ejames17** [comment]
@dat7e   i had the same issue. You need to run await page.evaluate('navigator.userAgent');

 const userAgent = new UserAgent({ deviceCategory: 'mobile' });
        await page.setUserAgent(userAgent.toString());
        const ua = await page.evaluate('navigator.userAgent');

**Comment by dat7e** [comment]
@ejames17 that worked beautifully. Thank you!

**Comment by brunogaspar** [comment]
Confirmed, the user agent is not being set properly for some reason.

**Comment by brunogaspar** [comment]
So, from the looks of it, it's a Puppeteer bug, going to close since there's already an alternative to retrieve the user agent.
