### ISSUE TITLE
puppeteer-extra-plugin-recaptcha page.solveRecaptchas is not a function

### ISSUE THREAD

**Issue by arkinzgithub** [berstend/puppeteer-extra#184]
Hello i'm sorry to bother you but my puppeter extra recapcha has a strange issue indeed my nodejs debugger is saying me that page.solveRecaptchas is not a function but i've properly imported my pluggins so can you help me, i'm really lost, thanks.

Here is my code 

`
const puppeteer = require('puppeteer-extra')
const RecaptchaPlugin = require('puppeteer-extra-plugin-recaptcha')

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

(async () => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();
  await page.goto('https://recaptcha-demo.appspot.com/recaptcha-v2-checkbox.php');
  await sleep(5000)
  await page.solveRecaptchas()
  
 

})();

`

So do you have any idea of how can i fix it, y also tried to reinstall every of my npm packets therefore i don't have any idea, Thanks arkinz ^^

**Comment by ejames17** [comment]
@arkinzgithub  i have been having this problem as well when im using incognito.

**Comment by RusTit** [comment]
Hey,
I don't see in your code initialization for this plugin.
(https://www.npmjs.com/package/puppeteer-extra-plugin-recaptcha)
```js
puppeteer.use(
  RecaptchaPlugin({
    provider: {
      id: '2captcha',
      token: 'XXXXXXX' // REPLACE THIS WITH YOUR OWN 2CAPTCHA API KEY ⚡
    },
    visualFeedback: true // colorize reCAPTCHAs (violet = detected, green = solved)
  })
)
```

**Comment by berstend** [comment]
Solution: #353
