### ISSUE TITLE
how to add puppeteer-extra flash plugin to site-scan to generate screenshots with flash enabled

### ISSUE THREAD

**Issue by world33** [berstend/puppeteer-extra#19]
![mpi mk ua](https://user-images.githubusercontent.com/20501877/47782999-bdbc6800-dd55-11e8-8ee7-106d97556fa3.png)
Would anyone be able to point out to a total coding noob how to integrate in the **site-scan** script (to generate website screenshots) at https://github.com/christopherwk210/site-scan/blob/master/lib/site-scan.js 
the flash plugin provided by puppeteer-extra?
I have tried including these lines in the site-scan script but with no much luck:

`#! /usr/bin/env node

// Modules
const argv      = require('minimist')(process.argv.slice(2));
const puppeteer = require('**puppeteer-extra**')
**puppeteer.use(require('puppeteer-extra-plugin-flash')())**
const chalk     = require('chalk');`

I need to create website screenshots in bulk but with site-scan (both headless or not) all the sites with flash are not generated properly and show a placeholder instead.
This site screenshot, for example, http://mpi.mk.ua/ shows a massive gray placeholder requiring to enable flash. 
Thanks for any tip

**Comment by berstend** [comment]
Hi there,
keep in mind that you need to configure the [puppeteer-extra flash plugin](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-flash):


```
puppeteer.use(require('puppeteer-extra-plugin-flash')({
	pluginPath: 'foo',
    pluginVersion" '1.2.3'
}))
```

The values above are exemplary and depend on your host system.

You can look up the flash path and version by navigating to `chrome://version/`.

Let me know if there are further issues, closing for now. :-)
