### ISSUE TITLE
Detection Problem: Canvas Fingerprinting

### ISSUE THREAD

**Issue by wernerwernerwerner888** [berstend/puppeteer-extra#190]
Hello, 
first i want to say thanks to the devs, great work here
The biggest problem is that many websites did work on there detection systems and many do use canvas fingerprinting to catch bots.

Is there any idea or workaround to create unique canvas fingerprints or manipulate canvas so it would become slightly different?

**Comment by yeetyoteImagoat** [comment]
You can download an anti-canvassing plugin on Chrome, and then launch it with Puppeteer commands to run on Chromium

**Comment by xiaohuimc** [comment]
> Chromium



> You can download an anti-canvassing plugin on Chrome, and then launch it with Puppeteer commands to run on Chromium

The plugin can only be run after ‘headless=False’, is there any other way

**Comment by berstend** [comment]
Closed in favor of #101 ;-)

**Comment by berstend** [comment]
> The plugin can only be run after ‘headless=False’, is there any other way

Chrome Extensions cannot run in headless mode.
