### ISSUE TITLE
This might being detected on account.google.com

### ISSUE THREAD

**Issue by brooklyn097** [berstend/puppeteer-extra#191]
It was fine to use this plugin to do auto log-in to a google account but today it stopped working.
I've done some test such as switch to another PC, test on different OS (Windows and Mac are tested), downgrade to older version of chrome (79.x), changing the IP, user agent, run on Microsoft Edge chromium version... But non of them worked.
Google throws to this message

> Couldn't sign you in
> This browser or app may not be secure. Learn more
> Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

So i think google detects headless browser on their end but not on browser level.
Is there any workaround to resolve this problem?

**Comment by partyconfetti** [comment]
+1 We are having this issue since last week.
We would also pay for a solution if anyone is interested.

**Comment by bluefox** [comment]
For anyone who has this issue, we find reverting back to the older 2.4.5 version seems to work for us.

**Comment by phancongtaidhsp** [comment]
> For anyone who has this issue, we find reverting back to the older 2.4.5 version seems to work for us.

version puppeteer-extra or puppeteer-extra-plugin-stealth

**Comment by brooklyn097** [comment]
> For anyone who has this issue, we find reverting back to the older 2.4.5 version seems to work for us.

Downgrade version of puppeteer-extra-plugin-stealth is working. Thank you!

**Comment by phancongtaidhsp** [comment]
> xtra-plugin-stealth

i try downgrade version 2.4.4 didn't work for me

**Comment by phancongtaidhsp** [comment]
> > For anyone who has this issue, we find reverting back to the older 2.4.5 version seems to work for us.
> 
> Downgrade version of puppeteer-extra-plugin-stealth is working. Thank you!
i try downgrade version 2.4.4 didn't work for me

**Comment by brooklyn097** [comment]
> > > For anyone who has this issue, we find reverting back to the older 2.4.5 version seems to work for us.
> > 
> > 
> > Downgrade version of puppeteer-extra-plugin-stealth is working. Thank you!
> 
> i try downgrade version 2.4.4 didn't work for me

Try 2.4.5 instead of 2.4.4.

**Comment by phancongtaidhsp** [comment]
> > > > For anyone who has this issue, we find reverting back to the older 2.4.5 version seems to work for us.
> > > 
> > > 
> > > Downgrade version of puppeteer-extra-plugin-stealth is working. Thank you!
> > 
> > 
> > i try downgrade version 2.4.4 didn't work for me
> 
> Try 2.4.5 instead of 2.4.4.
It doesn't work. Could you give code example for sign in google account and show me your version puppeteer-extra, puppeteer-extra-plugin-stealth

**Comment by phancongtaidhsp** [comment]
I try downgrade version 2.4.0 is working. Thank you!

**Comment by sandou78** [comment]
same I downgrade to 2.4.5 it works

**Comment by nitishmakhija** [comment]
`"puppeteer": "^1.15.0",                                                                                                           
   "puppeteer-extra": "^3.1.9",                                                                                                  "puppeteer-extra-plugin-stealth": "^2.4.5",`

I have these in my dependencies but it fails for me

**Comment by Brandawg93** [comment]
@nitishmakhija change `"puppeteer-extra-plugin-stealth": "^2.4.5"` to `"puppeteer-extra-plugin-stealth": "2.4.5"`. You just need to take out the "^" or it will keep updating to the latest patch.
