### ISSUE TITLE
recaptcha doesn't work

### ISSUE THREAD

**Issue by Dam998** [berstend/puppeteer-extra#194]
Hi,
I tried the example in the readme file, but it's seems to no work for me
after some seconds the browser close and this is what I found in the response.png

![response](https://user-images.githubusercontent.com/23696659/81429300-e1881780-915d-11ea-80c8-24d3018bb46a.png)

**Comment by Dam998** [comment]
I want to update, now it's working, I don't know why, I didn't change nothing
but seems it take a lot of time to solve it, more or less 30 seconds to solve it, is it normal?

**Comment by walidsa3d** [comment]
Recaptcha solving takes time. It's normal.
