### ISSUE TITLE
Puppeteer bot detection with out-of-process iframes by user-agent and screen size

### ISSUE THREAD

**Issue by ukrexpo** [berstend/puppeteer-extra#196]
Real User-Agent is detectable with <iframe> when using "puppeteer-extra-plugin-stealth". To prevent it use "'--disable-features=site-per-process'" argument for puppeteer.launch(). See explanation: https://github.com/puppeteer/puppeteer/issues/2548

Real screen size is also detectable with iframe, to prevent it I used preload() script.

OS: Windows 10
"puppeteer": 3.0.4
"puppeteer-extra": 3.1.9
"puppeteer-extra-plugin-stealth": 2.4.9

Code to reproduce:

``` javascript
const puppeteer = require('puppeteer');
const puppeteerExtraPluginStealth = require('puppeteer-extra-plugin-stealth');
const puppeteerExtraPluginUserAgentOverride = require('puppeteer-extra-plugin-stealth/evasions/user-agent-override');
const {PuppeteerExtra} = require('puppeteer-extra');

function preload(device) {
  Object.defineProperty(navigator, 'platform', {
    value: device.platform,
    writable: true,
  });
  Object.defineProperty(navigator, 'userAgent', {
    value: device.userAgent,
    writable: true,
  });
  Object.defineProperty(screen, 'height', {
    value: device.viewport.height,
    writable: true,
  });
  Object.defineProperty(screen, 'width', {
    value: device.viewport.width,
    writable: true,
  });
  Object.defineProperty(window, 'devicePixelRatio', {
    value: device.viewport.deviceScaleFactor,
    writable: true,
  });
}

const device = {
  userAgent: 'Mozilla/5.0 (Macintosh)',
  viewport: {
    width: 1200,
    height: 800,
    deviceScaleFactor: 1,
    isMobile: false,
    hasTouch: false,
    isLandscape: true,
  },
  locale: 'en-US,en;q=0.9',
  platform: 'Macintosh',
};

(async () => {
  try {
    const pptr = new PuppeteerExtra(puppeteer);
    const pluginStealth = puppeteerExtraPluginStealth();
    pluginStealth.enabledEvasions.delete('user-agent-override'); // Remove this specific stealth plugin from the default set
    pptr.use(pluginStealth);

    const pluginUserAgentOverride = puppeteerExtraPluginUserAgentOverride({
      userAgent: device.userAgent,
      locale: device.locale,
      platform: device.platform,
    });
    pptr.use(pluginUserAgentOverride);

    const browser = await pptr.launch({
      args: [
        '--disable-features=site-per-process',
        `--window-size=${device.viewport.width},${device.viewport.height}`,
      ],
      headless: false,
      defaultViewport: device.viewport,
    });
    const page = await browser.newPage();
    await page.evaluateOnNewDocument(preload, device);
    await page.goto('https://codepen.io/ukrexpo/pen/JjYverG');
  } catch (err) {
    console.error(err);
  }
})();
```

**Comment by ruimarinho** [comment]
@ukrexpo shouldn't `platform` be `MacIntel` instead?

**Comment by brdeav39** [comment]
Awesome! This just fixed a problem I was encountering a particular site. Thanks man.

**Comment by kensnyder** [comment]
I also discovered that puppeteer reports a `colorDepth` and `pixelDepth` of 30 instead of the 24 I see on other desktop browsers (Windows and Mac). It sounds like there are [a few devices](https://en.wikipedia.org/wiki/Color_depth#Deep_color_(30-bit)) that support 30-bit color, but theoretically the depth should match up with graphics card vendor reported by WebGL.

Additionally a plugin like this could consider changing `window.outerHeight` and `screen.availHeight` to account for an OS dock height and browser tabs + omnibar height. It gives away puppeteer quickly if the `window.innerHeight` doesn't make sense with the values for `screen.height` and `screen.availHeight`.

**Comment by momala454** [comment]
also document['documentElement']['clientHeight']

**Comment by momala454** [comment]
careful also with
```
document.documentElement.clientWidth
document.documentElement.clientHeight
```

it looks like chrome headless doesn't account for scrollbar size

regarding window.innerHeight / screen.availHeight
maybe be carefull with css media queries which could detect the real size ?

**Comment by berstend** [comment]
I think in more recent Chrome versions this might be required: `--flag-switches-begin --disable-site-isolation-trials --flag-switches-end`

**Comment by flashjames** [comment]
Also make sure you're using a recent puppeteer version, in puppeteer@1.8.0 @berstend answer crashes chromium

**Comment by berstend** [comment]
> Also make sure you're using a recent puppeteer version, in puppeteer@1.8.0 @berstend answer crashes chromium

pptr `1.8.0` has been released 3 years ago and uses chrome v70 😅 but happy to hear our efforts for backwards compatibility are appreciated :-)

**Comment by berstend** [comment]
Opportunity for someone to get involved (#439):
> Would be great if someone can make a proper test case to confirm failing behavior + fixed behavior when the two launch args are used. Also it'd be worthwhile to document negative side-effects - if they're neglectable we can make an evasion to enable that as the default.

**Comment by ya-mouse** [comment]
The workaround is broken since puppeteer@12.0.0, the last working version is @11.0.0.
At least on Linux host it doesn't work. Running workaround reveals the real platform details/UA.

**Comment by berstend** [comment]
Pretty sure this issue is not applicable anymore, closing as there's no substantive discussion either

**Comment by onlynfp** [comment]
@ukrexpo How can I use multiple devices from your code?
