### ISSUE TITLE
puppeteer-extra-plugin-flash: "Click to enable Adobe Flash Player" prompt visible when using Puppeteer 1.10.0 with "external" Chromium 70.0.3538.102

### ISSUE THREAD

**Issue by timopulkkinen** [berstend/puppeteer-extra#20]
Hello,

first of all, thanks for the plugin! 

It worked perfectly earlier with both the "built-in" Chromium and stock Chrome, but when I changed the browser to Chromium 70.0.3538.102, the prompt requesting a click came back. Some kind of a change in the prefs or ...?

Package info:
```
ii  chromium                           70.0.3538.102-1~deb9u1         amd64        web browser
ii  flashplayer-chromium               31.0.0.148-dmo1                amd64        Flash Player for Chromium (Pepper)
```

**Comment by berstend** [comment]
@timopulkkinen apologies for the delay, is this still an issue?

Would be great if you can post your `puppeteer-extra-plugin-flash` config here and verify that the path matches what you see in `chrome://version`. :-)

**Comment by berstend** [comment]
Also as it seems you're using Linux you might want to give the [management policy](https://gist.github.com/berstend/bcd64a4a2db28afbd6486daf69f4e787) option a try, if you have control of the system.

**Comment by berstend** [comment]
Closing for now, let me know if I can help further.

**Comment by timopulkkinen** [comment]
> Also as it seems you're using Linux you might want to give the [management policy](https://gist.github.com/berstend/bcd64a4a2db28afbd6486daf69f4e787) option a try, if you have control of the system.

Thanks, got it working by adding the policy. Here's a oneliner for adding that in a Dockerfile in case someone needs it:

```
RUN mkdir -p /etc/chromium/policies/managed \
    && mkdir -p /etc/opt/chrome/policies/managed \
    && sh -c 'echo "{\"RunAllFlashInAllowMode\": true,\"AllowOutdatedPlugins\": true,\"DefaultPluginsSetting\": 1,\"PluginsAllowedForUrls\": [\"https://*\", \"http://*\"]}" >  /etc/chromium/policies/managed/flash_policy.json' \
    && sh -c 'echo "{\"RunAllFlashInAllowMode\": true,\"AllowOutdatedPlugins\": true,\"DefaultPluginsSetting\": 1,\"PluginsAllowedForUrls\": [\"https://*\", \"http://*\"]}" >  /etc/opt/chrome/policies/managed/flash_policy.json' \
    && chmod -w /etc/opt/chrome/policies/managed \
    && chmod -w /etc/chromium/policies/managed
```

**Comment by berstend** [comment]
Sweet, thanks for sharing @timopulkkinen
