### ISSUE TITLE
Is there a way/plugin to add mp4 support to Puppeteer.?

### ISSUE THREAD

**Issue by thegeekybaniya** [berstend/puppeteer-extra#200]
Can we make a plugin for puppeteer to add mp4 support? We have already added a lot using this library, what would be the pathway for that, I am willing to take that up.

**Comment by danielgwilson** [comment]
You can get it working pretty easily by setting the `executablePath` `LaunchOption` to the path to your Chrome installation. Chromium does not support `.mp4`, but Chrome does—both work with puppeteer.

See:
https://github.com/puppeteer/puppeteer/issues/291

> I think is is because the MP4 codec is under a paid license fee. Which means it isn't distributed with Chromium but only within Google Chrome.

> mp4 is missing in chromium: https://www.chromium.org/audio-video

**Comment by thegeekybaniya** [comment]
@danielgwilson But will the puppeteer extra stealth plugin will be as effective as it is now?

**Comment by danielgwilson** [comment]
@thegeekybaniya not 100% sure but it seems to work fairly well—if others are aware of any "gotchas" that I've missed, I'd be super interested.

**Comment by berstend** [comment]
> @danielgwilson But will the puppeteer extra stealth plugin will be as effective as it is now?

The stealth plugin works with all chromium based browsers :-)
