### ISSUE TITLE
Rewrite in Typescript

### ISSUE THREAD

**Issue by berstend** [berstend/puppeteer-extra#21]
### Current progress (28 Nov - not pushed yet!) 📚 

- [x] **Rewrite `puppeteer-extra` in TypeScript** 🎉 
- [x] **New `addExtra` export to support non-standard or multiple puppeteer instances**
- [x] **Find a way to stay compatible with the existing default export and behavior**
- [x] **Make all existing tests go green**
- [x] **Find a way to use documentation.js with TypeScript**
- [x] Find a way to have plugins extend Puppeteer types (e.g. `page.solveCaptchas()`)
- [x] Add TypeScript usage examples to readme
- [x] Add puppeteer-firefox usage examples to readme  
- [x] Beautify the documentation.js output to the current look
- [x] Update all plugins to use the new core
- [x] Update all plugins to use the new documentation approach

---

_(initial comment)_

I started this repo before noticing how awesome typescript is. 😄 

Whenever I find the time I shall refactor this project into typescript.

Potential issues:
- Automatic JSDoc > Markdown conversion (tsdoc isn't there yet) 
  - https://github.com/documentationjs/documentation/issues/282
- How to best generate types when dynamically patching puppeteer 

### Update

Parts have been rewritten in TypeScript 🎉 
- [puppeteer-extra-plugin-recaptcha](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-recaptcha)
- [puppeteer-extra-plugin](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin) (base class for plugins)

Before I can rewrite the rest I **need to improve the generated typedoc output**.

We're using `typedoc-plugin-markdown` (the current best thing) and the [output looks like this](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin/docs), compared to the [previous documentation.js based docs](https://github.com/berstend/puppeteer-extra/blob/06c38ad4f7e730f4be1af297cb10bd6ebce49762/packages/puppeteer-extra-plugin/readme.md#api). 😢 

I'm really close to start developing my own minimal `typedoc-plugin-readme` plugin. 😅

**Comment by outlabeau** [comment]
Agreed!  At this point, i will only use npm modules that have an @types package that goes along with it.  Especially important for puppeteer-extra since it's used as a drop-in replacement for puppeteer in the code.  Can't wait to see a @types package become available for this!

**Comment by berstend** [comment]
@outlabeau I'm gonna create a `d.ts` for the time being (until everything is written in typescript) 😄 No need for `@types` though, the new version will come pre-shipped with the definitions.

**Comment by outlabeau** [comment]
@berstend that's great!  Can't wait for the d.ts.

**Comment by NikoMontana** [comment]
What is the status for this intend?

**Comment by berstend** [comment]
Apologies, got swamped with $work related things. Given that I love TS and my documentation system seems to be supporting TS now (this was the main blocker) I'll be rewriting the puppeteer-extra core in TS now after some hygiene tasks (updating deps, etc) :)

**Comment by berstend** [comment]
Current workarounds are mentioned here:
https://github.com/berstend/puppeteer-extra/issues/38#issuecomment-543388568

I'm checking that documentation.js will work with TypeScript as advertised (auto-generated docs are super important 😄).

In case that doesn't work I'll whip up a custom `d.ts` for the time being with the essentials.

**Comment by berstend** [comment]
The heavy lifting is done and the TypeScript version makes all tests go green. The auto-completion support in JS is a game changer, even for non-TS users. 

I ended up finding a way to stay backwards compatible with the current default export/behaviour:

```js
// existing simple case: defaults to require "puppeteer"
const puppeteer = require('puppeteer-extra')
puppeteer.use(...)

// new: optionally provide a puppeteer instance to patch
const { addExtra } = require('puppeteer-extra')
const puppeteer = addExtra(require('puppeteer-firefox'))
puppeteer.use(...)
```

Using this opportunity to cleanup and overhaul some other things as well before pushing this release.

**Comment by berstend** [comment]
First class TypeScript support has just landed!

```ts
import puppeteer from 'puppeteer-extra'

import RecaptchaPlugin from 'puppeteer-extra-plugin-recaptcha'
import StealthPlugin from 'puppeteer-extra-plugin-stealth'

puppeteer.use(RecaptchaPlugin()).use(StealthPlugin())

puppeteer.launch({ headless: false }).then(async browser => {
  const page = await browser.newPage()
  await page.setViewport({ width: 800, height: 600 })

  await page.goto('https://bot.sannysoft.com')
  await page.waitFor(5000)
  await page.screenshot({ path: 'stealth.png', fullPage: true })

  await browser.close()
})
```

![image](https://user-images.githubusercontent.com/1368633/69873140-cadcbb00-12b7-11ea-926c-5a5738832eac.png)

cc @outlabeau @NikoMontana 

They only thing I haven't figured out yet is how plugins could automatically extend built-in Puppeteer types (e.g. `page.solveCaptchas()`). 

Not sure if that's even possible.

But that's not too critical and can be overridden by the user easily (`(page as any).solveCaptchas()`). :)

**Comment by berstend** [comment]
Found a way to have plugins extend Puppeteer types (e.g. page.solveCaptchas()) fully type safe for consumers by shipping an ambient d.ts file. :)

Closing this for now.
