### ISSUE TITLE
Doesn't work with socks5 proxy

### ISSUE THREAD

**Issue by ordimans** [berstend/puppeteer-extra#210]
Hello,

I make a bot for famous china website. Thanks to this module, because stealthmode helped....
Without socks5 proxy registration is work with steatlh plugin.
But with puppeteer-page-proxy and a Request Interception, it's doesn't work.
I use differents private socks5 proxy, and same... the account was not created....

So is there another solution to use a proxy with puppeteer-extra ?
Or maybe i give a try to playwright, but it will probably same....

my code

```
(async () => {
  const browser = await puppeteer.launch({ headless: false, userDataDir: './cache'});
  //const browser = await puppeteer.launch({product:'firefox',  args:['-private-window']});
  //await browser.userAgent("Mozilla/5.0 (Linux; U; Android 2.3.6; en-us; Nexus S Build/GRK39F) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1");
  // Create a new incognito browser context.
  const context = await browser.createIncognitoBrowserContext();
  

  const page = await context.newPage();
  //To use proxy
  if (mustUseProxy)
  {
    await page.setRequestInterception(true);
    page.on('request', async req => {
        await useProxy(req, proxyUrl);
    });
  }

  await page.setUserAgent(UA);  
  //await page.setViewport({ width: 600, height: 960});

```

**Comment by ordimans** [comment]
Not sure if the StealthPlugin is OK.
I have hairline missing.
It's normal ?

Don't know if it's detected by aliexpress...

**Comment by Torpedo99** [comment]
Hairline is dependent on the browser.
You could try using the local chrome installation (via `executablePath` arg) to see if hairline issue is fixed.

**Comment by ordimans** [comment]
I use 

`puppeteer.executablePath('C:\Program Files (x86)\Google\Chrome\Application');
`

It's same.
Can this failed test can be detected by website ??

**Comment by danielgwilson** [comment]
I'm also experiencing the hairline issue recently for some reason.

**Comment by danielgwilson** [comment]
@ordimans  @Torpedo99 

I added an issue with a solution to the hairline issue—see #219 

As mentioned there, however, it does seem that standard Chrome has problems as well. The recent increased detection rates are likely therefore a result of some other detection that hasn't been evaded yet.

**Comment by berstend** [comment]
`puppeteer-page-proxy` is a pretty ugly hack in my opinion. Better to use the alternative ways to use a proxy (chrome launch args, `proxy.pac`, `proxy-chain`, etc). :-) Closing this for now.
