### ISSUE TITLE
StealthPlugin (puppeteer v3.2.0): TypeError: browser.setMaxListeners is not a function

### ISSUE THREAD

**Issue by akornatskyy** [berstend/puppeteer-extra#211]
`StealthPlugin` fails with `TypeError` after upgrade to puppeteer v3.2.0.

```
TypeError: browser.setMaxListeners is not a function
    at StealthPlugin.onBrowser (.../node_modules/puppeteer-extra-plugin-stealth/index.js:155:13)
    at StealthPlugin._bindBrowserEvents (.../node_modules/puppeteer-extra-plugin/dist/index.cjs.js:479:24)
```

Note, according to [release notes](https://github.com/puppeteer/puppeteer/releases/tag/v3.2.0), puppeteer v3.2.0 switched to `Mitt` instead of `EventEmitter`.

**Comment by jchen54** [comment]
Same issue here. Tried downgrading puppeteer to v3.1.0, but see the same issue.

Here are the library versions I'm listing on my package.json
```
"puppeteer": "^3.1.0",
"puppeteer-extra": "^3.1.9",
"puppeteer-extra-plugin-stealth": "^2.4.9"
```

Any way around this?

**Comment by bacaist** [comment]
Node v10x... succesfull but i upgrade my nodejs for latest version v12x.. and then i have got fail

**Comment by akornatskyy** [comment]
Workaround:
```js
const puppeteer = require('puppeteer-extra');
const stealth = require('puppeteer-extra-plugin-stealth')();

stealth.onBrowser = () => {};
puppeteer.use(stealth);
```

**Comment by bacaist** [comment]
No, dont do that. Just try uninstall puppeteer and then
npm install puppeeter@3.1.0

its work for me

**Comment by akornatskyy** [comment]
@bacaist yep, I know you can pin the last good known version.

However, if you want to be up to date with upstream dependency (which is updated often), you can apply above workaround (consider to have a look at source code of `Mitt` and `StealthPlugin` to better understand the change).

**Comment by GitRubb** [comment]
@akornatskyy any idea how to implement that fix in typescript? That doesn't seem to work for me as shown in your solution.

**Comment by akornatskyy** [comment]
@GitRubb consider upgrade to version v3.3.0, read more [here](https://github.com/puppeteer/puppeteer/releases/tag/v3.3.0), please.

**Comment by XQDD** [comment]
puppeteer with puppeteer version 4.0.0 @akornatskyy

**Comment by akornatskyy** [comment]
the above workaround is confirmed to work with v4.0.0.

**Comment by kkmuffme** [comment]
Still same with 4.4.0 too

**Comment by akornatskyy** [comment]
> Still same with 4.4.0 too

@kkmuffme did you try the above [workaround](https://github.com/berstend/puppeteer-extra/issues/211#issuecomment-636283110)?

**Comment by kkmuffme** [comment]
Ah thank you, I somehow missed that & just tried reinstalling
