### ISSUE TITLE
Recaptcha V2 - undocumented error reported by 2captcha

### ISSUE THREAD

**Issue by khobabc** [berstend/puppeteer-extra#212]
Is there any plan for following issue reported by 2captcha for puppeteer-extra-plugin-recaptcha:
https://2captcha.com/blog/google-search-recaptcha

**Comment by khobabc** [comment]
An update to the article is as follows: https://2captcha.com/blog/update-google-recaptcha
This article recommends to send cookies and proxy, so how would someone would be able to do this?

**Comment by brunogaspar** [comment]
Duplicate of #204

**Comment by berstend** [comment]
Closing in favor of #204.
