### ISSUE TITLE
puppeteer-extra-plugin-recaptcha doesn't find ReCaptcha on angel.co

### ISSUE THREAD

**Issue by Lisennk** [berstend/puppeteer-extra#215]
.solveRecaptchas() doesn't work on page nor on all iframes.
Even if I clearly see recaptcha with devtools.

My page is:
https://angel.co/join?source=homepage&source_content=global_header_join_text

**Comment by Carcraftz** [comment]
I think the recaptcha thing is broken right now :/ 

https://2captcha.com/blog/update-google-recaptcha

This needs to be implemented into the plugin

**Comment by dantgal** [comment]
Same here: https://github.com/berstend/puppeteer-extra/issues/204 and here: https://github.com/berstend/puppeteer-extra/issues/212 - plugin needs update to send also ```data-s``` variable

**Comment by berstend** [comment]
This has been fixed in the latest version.
