### ISSUE TITLE
How to send additional parameters to in.php ?

### ISSUE THREAD

**Issue by danilogacevic** [berstend/puppeteer-extra#216]
According to this post https://2captcha.com/blog/google-search-recaptcha, sending "data-s" parameter is necessary to solve google captcha.

"_You should NOT run these JS which loads the captcha on google.com/sorry/index. If you load the captcha on the webpage and then send us this captcha for solving, a token we provide with a solution then will NOT work. That is because of this new data-s variable. A captcha could be loaded only once with given data-s._"

Can we solve captcha at all following these rules ?

**Comment by dantgal** [comment]
Without plugin change/upgrade it's not possible now :(
