### ISSUE TITLE
What are all you guys using pupeteer for?

### ISSUE THREAD

**Issue by AdityaAnand1** [berstend/puppeteer-extra#217]
I'm just curious to know what all everyone is scraping 😉 There isn't much of a community around it so thought this is the best place to discuss/

**Comment by dantgal** [comment]
Google search results - but it's impossible now using this plugin - Google changed reCaptcha and no chance to solve it

**Comment by AdityaAnand1** [comment]
Interesting, would love to know your use case. How exactly are you using Google search results? In a derivative product or some internal tool or something else?

Assuming you're talking about [this](https://github.com/berstend/puppeteer-extra/issues/193) issue, they seem to have a workaround.

**Comment by dench1k** [comment]
I make music mixes every month and post it on a couple of platforms including youtube. There is a thing called music policies, where you can search for a track and get the info about it's license (i.e. can you actually use it without restrictions or it can cause ban). So I made a bot, which logs in the gmail account and searches via this service through my tracklist, tells me the info about a track and makes a screenshot to check this info.

**Comment by seuaCoder** [comment]
> Google search results - but it's impossible now using this plugin - Google changed reCaptcha and no chance to solve it

Did you find any alternative ?

**Comment by dantgal** [comment]
nope and I will be very happy when recaptcha plugin for puppeteer is upgraded

**Comment by Marineeee** [comment]
https://github.com/danielgatis/puppeteer-recaptcha-solver , here is a free solver working (for me lol)

**Comment by dantgal** [comment]
But it's for old style reCaptcha (embedded) for such things puppeteer works like a charm too

**Comment by Marineeee** [comment]
U need v3 ?

**Comment by dantgal** [comment]
yuup! Tried https://github.com/danielgatis/puppeteer-recaptcha-solver but it also failed: https://postimg.cc/kD24p1Hb - tough times for google serp scrapers :(

**Comment by lmourabraga** [comment]
I have been using to scrap all images of the e-commerce of the company I work for and save each file naming with SKU of their respective products in order to centralize all these images in an API we created for our products.

**Comment by lmourabraga** [comment]
> yuup! Tried https://github.com/danielgatis/puppeteer-recaptcha-solver but it also failed: https://postimg.cc/kD24p1Hb - tough times for google serp scrapers :(

Dantgal, regarding your situation there are not solutions known yet for reCaptcha v3 once it was developed to not be beaten by an automatization. Actually you will always need a human solver for it.  As you can see, the solutions we have over the internet depends on the human hands to deliver their solution. For instance: https://2captcha.com/?from=9148648 see the content for: Work for 2Captcha.

**Comment by dantgal** [comment]
Yes, you are absolutely right! I have used 2captcha with puppeteer until it was possibe - now it's not :(

**Comment by RadoslavK** [comment]
Browser game bot. More reliable than simple http requests :D Just fun personal project.

**Comment by cnscorpions** [comment]
I scrape google serps with Puppeteer, but now google ban my bot. :(

**Comment by cnscorpions** [comment]
@dantgal Hi, just wonder how to identify recap version? I'm totally confused.

**Comment by itsdarrylnorris** [comment]
@AdityaAnand1 

> I'm just curious to know what all everyone is scraping 😉 There isn't much of a community around it so thought this is the best place to discuss

We have a discord server with a community around scraping/puppeteer/playwright. Here is the discord invite -> discord.gg/vz7pekk

**Comment by cnscorpions** [comment]
@itsdarrylnorris thanks

**Comment by dantgal** [comment]
> @dantgal Hi, just wonder how to identify recap version? I'm totally confused.

Hello Gavin! Sorry but I gave up with puppeteer, too many sleepless nights to fight with it :(

**Comment by cnscorpions** [comment]
@dantgal okay, good luck. it's hard work for me too. 
I am working on a google scraping project overnight. :( 
oh shit, Google bans all my proxy IPs.

**Comment by Dwight-Schrute** [comment]
@AdityaAnand1 - onlyFans automation for a growing 'influencer'. Those girls make serious cash

**Comment by berstend** [comment]
Closing this for now 😄 

> There isn't much of a community

Not anymore! Our discord has an active and cool community (which is better suited for these types of discussion): https://github.com/berstend/puppeteer-extra/wiki/Scraping-Chat
