### ISSUE TITLE
Bug (with fix)—missing hairline feature detection evasion when using Chrome executable

### ISSUE THREAD

**Issue by danielgwilson** [berstend/puppeteer-extra#219]
## Current behavior

_(confirmed in `2.4.5`, `2.4.7`, `2.4.9`)_

When evaluating the puppeteer instance via https://bot.sannysoft.com, the `Hairline Feature` test is marked as missing.

**Note, however, that this is also true for _Chrome Version 83.0.4103.61 (Official Build) (64-bit)_
 on _MacOS 10.15.5 (19F101) Catalina_.**

## Expected behavior

Given that this hairline feature is missing in normal Chrome, I'm not clear on whether a fix is actually needed. However, in case it's useful to anyone else, I've gotten a fix to work based on [Sangaline's OG article](https://intoli.com/blog/making-chrome-headless-undetectable/).

I include the snippet below upon creation of a new page (should be fairly straightforward to translate this to an additional plugin if necessary).

```typescript
...    
    const page = await this.browser.newPage();

    // Bypass hairline feature
    await page.evaluateOnNewDocument(() => {
      // store the existing descriptor
      const elementDescriptor = Object.getOwnPropertyDescriptor(
        HTMLElement.prototype,
        "offsetHeight"
      );

      // redefine the property with a patched descriptor
      Object.defineProperty(HTMLDivElement.prototype, "offsetHeight", {
        ...elementDescriptor,
        get: function() {
          if (this.id === "modernizr") {
            return 1;
          }
          // @ts-ignore
          return elementDescriptor.get.apply(this);
        },
      });
    });
...
```

**Comment by Kikobeats** [comment]
just to add some context, `Hairline Feature` is based on Retina/HiDPI detection and it doesn't really make a ton of sense because the majority of people don’t have HiDPI screens and most users’ browsers won’t support this feature.

Reference: https://intoli.com/blog/making-chrome-headless-undetectable/

**Comment by berstend** [comment]
Would be nice to add this evasion dynamically based on emulating a retina device or not (PRs welcome).

Closing for now as it doesn't seem critical :)
