### ISSUE TITLE
Being taunted by a company

### ISSUE THREAD

**Issue by a10kiloham** [berstend/puppeteer-extra#227]
Haha these guys are taunting this plugin, but do provide one additional signal
https://datadome.co/bot-detection/client-side-detection-is-essential-for-bot-protection/
But the canPlay is a useful signal. Not sure what to send - guess spoof it?

**Comment by momala454** [comment]
they just want to be cracked ...

**Comment by apo-j** [comment]
Any idea to workaround datadome? I'm actually blocked by a website which uses datadome

**Comment by momala454** [comment]
check this issue for the things that must be fixed : https://github.com/berstend/puppeteer-extra/issues/239

**Comment by berstend** [comment]
I could not reproduce this issue, so I guess we fixed it already?

I added tests for what the datadome article mentioned: https://github.com/berstend/puppeteer-extra/pull/277
