### ISSUE TITLE
Help with stealth plugin

### ISSUE THREAD

**Issue by zulunidi** [berstend/puppeteer-extra#229]
Hi ,

I am trying to open ebay url using stealth, however its redirecting to captcha page.  Any help on this would be highly appreciated. Am running a basic js.

const puppeteer = require('puppeteer-extra')

// Add stealth plugin and use defaults (all tricks to hide puppeteer usage)
const StealthPlugin = require('puppeteer-extra-plugin-stealth')
puppeteer.use(StealthPlugin())

const work = async () => {
  browser = await puppeteer.launch({headless: true})

  const page = await browser.newPage()

  await page.goto('https://signin.ebay.com.au/ws/eBayISAPI.dll?SignIn&amp;ru=https%3A%2F%2Fwww.ebay.com.au%2F');

  await page.waitFor(5000);

  await page.screenshot({path: 'example.png'});

  await browser.close();

}

work()

**Comment by shannonlal** [comment]
@zulunidi looks like you need to solve the captcha using a service such as 2captcha.  There is a plugin in this repo which provides instructions on how to set this up.   As a note you will most likely need to use an external service which you pay for (2captcha) to solve the problem.

**Comment by itsdarrylnorris** [comment]
Using 2captcah should do the trick. Closing this issue.
