### ISSUE TITLE
TypeError: browser.setMaxListeners is not a function

### ISSUE THREAD

**Issue by kkmuffme** [berstend/puppeteer-extra#235]
Followup to https://github.com/berstend/puppeteer-extra/issues/211

Since 4.0.0 this issue has reappeared and exists all the way up to the latest (4.4.0)

With 4.4.0 the suggested workaround of reinstalling puppeteer doesn't help either.

**Comment by brunogaspar** [comment]
This issue is unfortunate but it's a duplicate of #228

**Comment by itsdarrylnorris** [comment]
Hey @kkmuffme ,

Can we close this issue? Since is a duplicated of #228

**Comment by berstend** [comment]
Duplicate of and fixed in #228.
