### ISSUE TITLE
Is there any plan to update the stealth plugin?

### ISSUE THREAD

**Issue by Sesamestrong** [berstend/puppeteer-extra#236]
There are several live methods used to detect Puppeteer running `puppeteer-extra-plugin-stealth`  (#208 #225 #218 #213 #227 #147 #231 #204 #209 #199 #196 #193 #187 #175). These have been open for a number of weeks and the owner of the repository has been MIA since February, so fixes for these fingerprinting techniques cannot be published to the `puppeteer-extra-plugin-stealth` npm package. It is clear that the only way the cat-and-mouse game can go on in a large scale is if the `puppeteer-extra-plugin-stealth` module is updated frequently with more/better evasions.
I am in the process of contacting @berstend at his listed email, but in case he does not respond, I think that people should decide how to continue with maintenance of a fork of `puppeteer-extra` or some other open-source headless browser stealth plugin.
Is there any agreed-upon plan of what to do? I know that a few people have made forks which they are maintaining, and one person is developing a [Playwright equivalent](https://github.com/Niek/playwright-addons/) that is actively maintained but still very young. Personally, I think that if @berstend comes back online, the best option would be to pick an [existing contributor](https://github.com/berstend/puppeteer-extra/graphs/contributors) to also have push access to the monorepo.

**Comment by brunogaspar** [comment]
If he replies through email would be nice, on GitHub he's totally MIA, but i really hope he's ok with all the shit that's going on with the world.

Either way i'm working on my simple version for puppeteer, hopefully in the next week i might have something open.

**Comment by berstend** [comment]
Hi everyone,
apologies for the delay in communication and thanks to everyone reaching out (esp. via email, e.g. @Sesamestrong).

I've been affected by the covid situation and subject to related issues that unfortunately drew my attention away from open-source work for the past months. 

I'm humbled that this project had such an impact and created value for quite a few people. I also appreciate and acknowledge that some have been using it as a building block and depend on it being actively maintained, supported and updated.

That being said and things normalizing on my end as well here's my proposed plan how to go from here:
- This weekend I will assess the current state of things, merge & publish any critical PRs
- **I'm actively looking for contributors who'd like to get involved in the project more** and receive push privileges, so I'm not the sole person responsible for pushing updates or checking PRs. :-)
	- I need to update the tooling for that a bit, e.g. currently CI won't push updated NPM packages automatically (it's done manually)
- Unfortunately a lot of issues are from less experienced developers and of of the type "help this website is blocking me" 😅. This is a bit overwhelming for a single maintainer to handle so I'm looking for support here as well and will implement e.g. Issue templates to aid with handling those requests.

I'm gonna create a sticky issue regarding the current state of the project and call for co-maintainers as well.

Thanks and stay safe everyone!

**Comment by brunogaspar** [comment]
Glad that you're "ok" @berstend , let us know if we can help in something outside code wise.

Me, and i'm sure, others are here to help you maintain this if you see fit :)

**Comment by berstend** [comment]
@brunogaspar Thanks a lot, I'm doing fine by now. :-)

I need a few more days to organize certain things on my end but will use the weekend to see where we are at with `puppeteer-extra` and organize/prepare the next steps going forward (involving/empowering others as well). :)

**Comment by kylerchin** [comment]
Full support! :)

**Comment by berstend** [comment]
Thanks again for the support. :-) Closing this ticket for now as we're in full swing and pushed a couple of updates already. Cheers!

**Comment by toxx91** [comment]
RTCPeerConnection
RTCRtpReceiver
RTCIceCandidate
webkitMediaStream
RTCTrackEvent
RTCRtpSender
RTCError
RTCPeerConnectionIceEvent
RTCRtpTransceiver
WebGLQuery
WebGLRenderingContext
WebGLProgram
WebGLTransformFeedback
WebGLFramebuffer
webkitRTCPeerConnection

**Comment by taewookim** [comment]
Any way I can contribute? Having this [issue](https://github.com/puppeteer/puppeteer/issues/7498) as well.
