### ISSUE TITLE
puppeteer-extra-plugin-recaptcha Add New Provider

### ISSUE THREAD

**Issue by captchasio** [berstend/puppeteer-extra#237]
I'd like to request support for adding CAPTCHAs.IO (API https://api.captchas.io/document/) as a new provider to puppeteer-extra-plugin-recaptcha. Well, the service has exactly the same API with that of 2Captcha. Which allows it to be so easy to add support for this service as another provider to puppeteer-extra-plugin-recaptcha.

**Comment by berstend** [comment]
Hey there, 2captcha is pretty standard at this point - they've been around for ages, work reliably and are pretty cheap.

There's no real incentive currently to add more providers. It's definitely possible but the (super low) demand doesn't justify the effort. :-) The recaptcha plugin itself needs some love and I wanna focus on that for the time being.

Please reopen this issue if the above is not correct or I'm missing something. :-)

**Comment by joeregs** [comment]
I second this, please add support for Captchas.io as 2captcha is way too slow, it takes 60 seconds sometimes.

**Comment by joeregs** [comment]
> Hey there, 2captcha is pretty standard at this point - they've been around for ages, work reliably and are pretty cheap.
> 
> There's no real incentive currently to add more providers. It's definitely possible but the (super low) demand doesn't justify the effort. :-) The recaptcha plugin itself needs some love and I wanna focus on that for the time being.
> 
> Please reopen this issue if the above is not correct or I'm missing something. :-)

Is there any documentation on how to add another provider please?

**Comment by PureAyGames** [comment]
> Hey there, 2captcha is pretty standard at this point - they've been around for ages, work reliably and are pretty cheap.
> 
> There's no real incentive currently to add more providers. It's definitely possible but the (super low) demand doesn't justify the effort. :-) The recaptcha plugin itself needs some love and I wanna focus on that for the time being.
> 
> Please reopen this issue if the above is not correct or I'm missing something. :-)

yeah can u show us how implementing another provider would work

**Comment by PureAyGames** [comment]
2capthca is actually ass so idk what you mean man. its know and advertised that they take 45 to 60 seconds. cap monster is cheaper and takes only 5 seconds on averege


> Hey there, 2captcha is pretty standard at this point - they've been around for ages, work reliably and are pretty cheap.
> 
> There's no real incentive currently to add more providers. It's definitely possible but the (super low) demand doesn't justify the effort. :-) The recaptcha plugin itself needs some love and I wanna focus on that for the time being.
> 
> Please reopen this issue if the above is not correct or I'm missing something. :-)


2capthca is actually ass so idk what you mean man. its know and advertised that they take 45 to 60 seconds. cap monster is cheaper and takes only 5 seconds on averege
