### ISSUE TITLE
How to figure out new evasions

### ISSUE THREAD

**Issue by jimmycarlinco** [berstend/puppeteer-extra#24]
Hey guys, sorry  if this is not in the scope of this library. I have an interesting question: how would one figure out other detections if this stealth library is enabled but you still get blocked? You must definitely have more experience in this area since you already have figured out a bunch of evasions. Perhaps we should create a list of articles on different evasions for headless detection that are not covered by this library? 

Thanks a bunch if you find some time to contribute to this issue

**Comment by berstend** [comment]
Hey @jimmycarlinco! 👋 

The whole detection & evasion thing is quite interesting, I find. 

Most of the "community" surrounding this topic [can be found here](https://github.com/paulirish/headless-cat-n-mouse). This was also used as the initial source of evasions (by now I added new ones and improved the existing ones from there).

If you have a link that you can share publicly I'm happy to take a look when I find the time.

On a general note: You always want to confirm that the site in question is actually able to detect headless usage and not just subject to a false positive (some ways to detect headless usage are very aggressive and consider regular browsers to be headless as well in certain conditions).

The best way to do that would be to manually use Chrome (without pptr) and observe how the site behaves. Next up would be using *headful* + *Chrome* and see if that works (check the stealthtests folder in the stealth repo).

Cheers

**Comment by berstend** [comment]
Closing for now, will add some documentation how to figure out new problems when I find the time.
