### ISSUE TITLE
Chromium Plugin Names

### ISSUE THREAD

**Issue by janisblaus** [berstend/puppeteer-extra#242]
https://amiunique.org/fp this detection reveals that plugins are from Chromium instead masked as Chrome. 

A simple workaround is to use 

`executablePath: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',`

in launch options.

**Comment by berstend** [comment]
Hey, we'll add info regarding chrome vs chromium to the documentation in the future. Closing for now. :-)
