### ISSUE TITLE
Cannot build on Windows

### ISSUE THREAD

**Issue by moltar** [berstend/puppeteer-extra#246]
I'm working on PR for GitHub Actions (#245) and I can't get a Windows build to work.

The errors are pretty vague and don't tell much. I don't have a Windows box to test it on.

Can anyone please try the following and see if you can figure out why the build is failing?

```sh
yarn
yarn bootstrap
yarn lerna add puppeteer@2.1.1
yarn lerna link

## this step fails
yarn lerna run build --concurrency 1
```

The failure is here: https://github.com/berstend/puppeteer-extra/runs/853251961?check_suite_focus=true

A partial snippet:

```
The system cannot find the file specified.
error Command failed with exit code 1.
error Command failed with exit code 1.
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in 'puppeteer-extra-plugin-recaptcha'
error Command failed with exit code 1.
verbose 39.617 Error: Command failed with exit code 1.
    at ProcessTermError.ExtendableBuiltin (C:\npm\prefix\node_modules\yarn\lib\cli.js:721:66)
    at ProcessTermError.MessageError (C:\npm\prefix\node_modules\yarn\lib\cli.js:750:123)
    at new ProcessTermError (C:\npm\prefix\node_modules\yarn\lib\cli.js:790:113)
    at C:\npm\prefix\node_modules\yarn\lib\cli.js:34550:30
    at Generator.throw (<anonymous>)
    at step (C:\npm\prefix\node_modules\yarn\lib\cli.js:310:30)
    at C:\npm\prefix\node_modules\yarn\lib\cli.js:323:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
##[error]Process completed with exit code 1.
```

**Comment by berstend** [comment]
The `package.json` scripts haven't been developed with Windows in mind. :-)

`yarn lerna run build` will basically run `yarn build` in every package, the problematic one is `recaptcha` where `yarn build` itself will chain more yarn scripts:

```
yarn clean && tsc --project tsconfig.json --module commonjs && rollup -c rollup.config.ts && yarn ambient-dts
```

One way to find the culprit would be to cd into recaptcha package and run these commands manually to see which one breaks.

I also don't have a windows box/vm right now, but this might useful (ssh into a GH action session): https://github.com/mxschmitt/action-tmate

If I recall correctly there was also an issue when using ENVs in package.json scripts under windows.

**Comment by berstend** [comment]
I'm not sure if we should actually invest time in making the build compatible with Windows, so far no one complained. :-) I'd also assume that virtually all devs are using WSL to build their NodeJS projects.

Using `puppeteer-extra` under vanilla Windows is fine, this only affects developing it.

**Comment by moltar** [comment]
Oh, forgot about the `&&`! I did fix some `rm` to `rimraf` though :)

> I'm not sure if we should actually invest time in making the build compatible with Windows, so far no one complained. :-) I'd also assume that virtually all devs are using WSL to build their NodeJS projects (windows incompatible package.json files are common).

Yeah, I didn't care much about build, just more about the tests. I wanted tests to run on Windows.

But my understanding was the build is required before the tests? Or is it not true?

If we only need the build before publishing, then I can actually extract that part into a separate workflow that only runs on Linux systems and doesn't even need a matrix, just a single run.

**Comment by berstend** [comment]
> But my understanding was the build is required before the tests?

That's correct, `yarn test-ci` will build first and test using the transpiled js files:

```
"test-ci": "yarn build && TS_NODE_COMPILER_OPTIONS='{\"module\":\"commonjs\"}' ava --fail-fast -v dist/*.test.js"
```

IIRC the intention behind this was to test the resulting output (to catch issues with the TypeScript compilation).

It's definitely possible to make the `package.json` windows compatible but I'm currently lacking the means (and passion) to help with that. 😅 

Maybe we table Windows testing until someone with a Windows machine and desire to help us comes along?

**Comment by moltar** [comment]
Ok, I think I have resolved all of the Windows build issues.

But there are 2 failing tests on Windows. I'll create a new issue.

**Comment by moltar** [comment]
> Maybe we table Windows testing until someone with a Windows machine and desire to help us comes along?

I wanted to get Windows builds and tests to work so that it opens up opportunity for Windows users to contribute.

As it was, they couldn't even run tests property.
