### ISSUE TITLE
[Question] Should I still set user agent when using Puppeteer Stealth?

### ISSUE THREAD

**Issue by gitcro** [berstend/puppeteer-extra#255]
I wonder wheather I should still rotate through different user agents when using the stealth plugin? Thx!

**Comment by berstend** [comment]
Depends on your use-case I'd say, if you want to "impersonate" different personas then you might want to do that. :-)

There was an idea for a plugin to auto-generate random user-agents using e.g. https://github.com/intoli/user-agents (or even more holistic "personas" with different viewports, etc) but that hasn't been done yet. :-)

**Comment by gitcro** [comment]
Ok, thx!
