### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Could not find browser revision 768783. Run "npm install" or "yarn install" to download a browser binary.

### ISSUE THREAD

**Issue by vinchu** [berstend/puppeteer-extra#258]
MacBook:puppeteer abc$ node test.js 
(node:58532) UnhandledPromiseRejectionWarning: Error: Could not find browser revision 768783. Run "npm install" or "yarn install" to download a browser binary.
    at ChromeLauncher.launch (/Users/abc/node_modules/puppeteer-core/lib/cjs/node/Launcher.js:86:23)
    at async PuppeteerExtra.launch (/Users/abc/node_modules/puppeteer-extra/dist/index.cjs.js:129:25)
(node:58532) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:58532) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by vinchu** [comment]
MacBook:puppeteer abc$ node test.js 
(node:60823) UnhandledPromiseRejectionWarning: Error: Could not find browser revision 768783. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.
    at ChromeLauncher.launch (/Users/abc/node_modules/puppeteer-core/lib/cjs/puppeteer/node/Launcher.js:86:23)
    at async PuppeteerExtra.launch (/Users/abc/node_modules/puppeteer-extra/dist/index.cjs.js:129:25)
(node:60823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:60823) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by brunogaspar** [comment]
Would need more information to really help you as the information you gave us is quite vague and is super difficult to reproduce.

Let us know more about your environment, the exact dependencies you're installing and maybe a script that reproduces the problem.

**Comment by berstend** [comment]
This sounds more like a general puppeteer (or user) error. Please reopen if puppeteer-extra is connected to this issue specifically (and please add proper description).
