### ISSUE TITLE
unable to click a checkbox after updates to a website im using puppeteer stealth on

### ISSUE THREAD

**Issue by michaelsalexander83** [berstend/puppeteer-extra#260]
I have this website which somehow detect puppeteer stealth.

One of the final steps is setting a checkbox and then clicking submit, however this never works after last week.
Any thoughts regarding this?

If I run the page normally in chrome and do all the steps puppeteer does it works fine, however as soon as I start the puppeteer process it:

1) reloads the page without submitting the form sometimes
2) OR it is unable to click the final approval checkbox and therefore it cannot submit.

Also would it be possble to get a little more debugging information? I already run the stealth plugin with 
```DEBUG=puppeteer-extra,puppeteer-extra-plugin:* node iwininthend.js```

But after some issue with the page or an element the browser just crashes. I use the plugins with and without headless= false or headless = true both the same results.

**Comment by brunogaspar** [comment]
Without seeing the code you are using and knowing the website in question is quite impossible to help you.

**Comment by berstend** [comment]
Try disabling `iframe.contentWindow`, it's known to cause troubles sometimes (https://github.com/berstend/puppeteer-extra/issues/137). Closing until there's more info.
