### ISSUE TITLE
Captures iframe instead of page

### ISSUE THREAD

**Issue by trnj** [berstend/puppeteer-extra#261]
Duplicate. Please remove.

**Comment by trnj** [comment]
Probably the same as here
https://github.com/berstend/puppeteer-extra/issues/202

**Comment by brunogaspar** [comment]
@trnj Seems to be the same as #202 , at least i tested 5 times without the fix and it was not showing the full page screenshot, just an iframe as you mention, then applied the fix and tested it 5 times and it showed the full page screenshot.

**Comment by trnj** [comment]
Yes, thank you. If possible remove this issue. The solution works.

**Comment by brunogaspar** [comment]
Sure no problem.

Going to close this one and hopefully we can create a patch ASAP.
