### ISSUE TITLE
Using with puppeteer-core?

### ISSUE THREAD

**Issue by lanly-dev** [berstend/puppeteer-extra#262]
Is it possible to use puppeteer-extra-plugin-stealth features with puppeteer-core? I assumed it can't from the look of it but still wondering if there is any chance. Thanks

**Comment by brunogaspar** [comment]
There's a few issues (closed) that mentions how to use it with puppeteer-core, have you checked those out?

https://github.com/berstend/puppeteer-extra/search?q=puppeteer-core&type=Issues

**Comment by lanly-dev** [comment]
I looked over the related issue, I tried but it is just too complicated to apply in my [project](https://github.com/lanly-dev/VSCode-LMPTM) (due to this [issue](https://github.com/lanly-dev/VSCode-LMPTM/issues/6)) since a lot of Typescript and Webpack errors show up after that. I'm probably going to wait and try future releases. Thanks!
