### ISSUE TITLE
Package to integrate with proxy per page

### ISSUE THREAD

**Issue by barddoo** [berstend/puppeteer-extra#269]
Add package in order to do the job [puppeteer-page-proxy](https://github.com/Cuadrix/puppeteer-page-proxy) does, currently it doesn't work with puppeteer-extra

**Comment by jozsi** [comment]
Last time I checked that approach, I did not like it. Using [proxy-chain](https://github.com/apify/proxy-chain) worked pretty well. It's a [long standing puppeteer issue](https://github.com/puppeteer/puppeteer/issues/678), while [playwright is pretty close](https://github.com/microsoft/playwright/issues/2833) to have it ready.

**Comment by berstend** [comment]
An alternative is using a `proxy.pac`, but it's still now awesome.

There are plans to create a `proxy` plugin for `puppeteer-extra` to make things more convenient, but we're still discussing the specifics.

Closing for this for now, unless there's more specific input/suggestions.
