### ISSUE TITLE
[Question] plugin-stealth different result on MacOS and Ubuntu

### ISSUE THREAD

**Issue by oOGabsOo** [berstend/puppeteer-extra#271]
Hello,

I am currently using code that works perfectly under MacOs and i'm never detected by distill,  the same code used in ubuntu on server side (16.04) is immediately detected by disitll...

I am using the following code:

`

     puppeteer.use(Stealth())

     async function main() {
         const browser = await puppeteer.launch({
         headless: true
     });

    let page = await browser.newPage();

    await page.evaluateOnNewDocument(() => {
        delete navigator.__proto__.webdriver;
    });

    await page.setUserAgent(new userAgent().toString())
    await page.goto("xxxx")
    await page.waitFor(10000);
    await page.screenshot({ path: "stealth.png", fullPage: true });
    await browser.close();
}
main();

`

I'm using the following modules on both side:

`    "puppeteer": "^5.2.1",
    "puppeteer-extra": "^3.1.13",
    "puppeteer-extra-plugin-adblocker": "^2.11.6",
    "puppeteer-extra-plugin-stealth": "^2.4.14",`

I wonder what can be the differences between the 2 environments :s And any Idea how to fix it ?

**Comment by sanchobouillant** [comment]
Hello,

They maybe detect the server ip. Like Lk, Netflix, ...

**Comment by oOGabsOo** [comment]
Hello,

Yes, it's a possibility at least for the first server which was used to parse html content on a daily basis. But I also tried on 2 different server (Azure VM) with the exact same code and the result is the same.

**Comment by sanchobouillant** [comment]
Install ubuntu server on a VM and try with a residential IP.

Azure have "server ips". And some websites could block them.

**Comment by oOGabsOo** [comment]
OK thx for the info i'll try that.

**Comment by berstend** [comment]
Can you navigate to https://httpbin.org/headers and paste the result here?

Note: The stealth plugin is currently not hiding that you're using Linux in the User-Agent: https://github.com/berstend/puppeteer-extra/blob/master/packages/puppeteer-extra-plugin-stealth/evasions/user-agent-override/index.js#L62

**Comment by oOGabsOo** [comment]
Hello,

Here is the result 

`<html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{
  "headers": {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9", 
    "Accept-Encoding": "gzip, deflate, br", 
    "Accept-Language": "en-US", 
    "Host": "httpbin.org", 
    "Sec-Fetch-Dest": "document", 
    "Sec-Fetch-Mode": "navigate", 
    "Sec-Fetch-Site": "none", 
    "Sec-Fetch-User": "?1", 
    "Upgrade-Insecure-Requests": "1", 
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36", 
    "X-Amzn-Trace-Id": "Root=1-5f294c9f-d9cd2159cc05ad3d242d6546"
  }
}
</pre></body></html>`

**Comment by berstend** [comment]
@oOGabsOo And that's the server-side result? Why does it say `Macintosh`, are you overriding the UA manually in addition to using the stealth plugin?

**Comment by oOGabsOo** [comment]
Yes i'm switching the UA => await page.setUserAgent(new userAgent().toString())

I also tried with the remote desktop and with a real browser, the result is the same i'm detected by distill :s (i'm probably a robot without knowing :s )

**Comment by berstend** [comment]
Are you using any proxies at all? Otherwise your server IP would be immediately recognized as such.

Closing this for now, our [chat](https://github.com/berstend/puppeteer-extra/wiki/Scraping-Chat) is better suited for these types of issues.

**Comment by shimuldn** [comment]
> Yes i'm switching the UA => await page.setUserAgent(new userAgent().toString())
> 
> I also tried with the remote desktop and with a real browser, the result is the same i'm detected by distill :s (i'm probably a robot without knowing :s )

You can try my settings from #314 with puppeteer-extra-plugin-stealth@2.6.0.
