### ISSUE TITLE
Discord Error

### ISSUE THREAD

**Issue by HiddenToolz** [berstend/puppeteer-extra#283]
Hello, when i browse discord pages, i look for network on the url :https://discord.com/api/v6/auth/register
This url return : if the register worked // if the ip is rate limited //  data when an account is created
When i click on register, it ask me for a captcha, and i can return this correctly as :

```
` 	await page.on('response', async (response) => {    
    if (response.url() == "https://discord.com/api/v6/auth/register")
    {
       if (typeof await response.text() !== 'undefined')
        {
       		if (await reply.includes("captcha-required")) { console.log("Captcha asked by server")}
       		if (await reply.includes("You are being rate limited.")) { console.log("IP Address is Rate limited !")}
        }
    }
}); 
```

The error comes when i succesfully confirm my captcha, it basicly make a request to the same url but i think it like lock it or continue to use it until it because injecting in it a token on the way! I would need to wait to be SURE the register is finished, and then get the content of it. 
Note : The request then get removed from the Network tab, i checked !
So the error returned is : 
(node:1068) UnhandledPromiseRejectionWarning: Error: Protocol error (Network.getResponseBody): No resource with given identifier found
I tried to add a delay when entering the on response trigger, but same result
How can i make sure than my request is totaly done  before checking the values ?
Else my code will always  crash !

**Comment by berstend** [comment]
Sorry, this is unreadable. Please use proper backticks (```) for code-fencing and provide proper examples to reproduce what you describe. Alternatively you can join the chat and ask nicely for help there.
