### ISSUE TITLE
[Question] Does it solve fade in / fade out reCaptcha?

### ISSUE THREAD

**Issue by psalkowskisii** [berstend/puppeteer-extra#285]
Hi, lastly I have found that the page which I run puppeteer is using reCaptcha, but the one with fade in / fade out the selection. For example, it asks me for a select bus, then when I select one, it refreshes tile with a new image that may have a bus. Does this plugin handle that kind of captchas?

**Comment by HiddenToolz** [comment]
yes, 2captcha are basicly people completing captcha for a really smal amount of money. So they recieve what you see on the screen and then complete them for you

**Comment by psalkowskisii** [comment]
@HiddenToolz thanks for reply!

How does it work then? As far as I found 2Captcha requires image as a captcha, but fade-in / fade-out is a multiple images? The only way that comes to my mind is that after they got from us some keys from HTML about captcha, they run the same captcha at theirs environment, and then they are solving it for us somehow. 

Do you have any knowledge about that?

**Comment by HiddenToolz** [comment]
Im not working for 2captcha. I know if works, that's it
