### ISSUE TITLE
Missing puppeteer.errors 

### ISSUE THREAD

**Issue by SBerkovic** [berstend/puppeteer-extra#288]
As of v5.0.0, puppeteer removed the top level file `puppeteer/Errors`. The same data is supposed to be exposed via `puppeteer.errors`

See [here](https://pptr.dev/#?product=Puppeteer&version=v5.0.0&show=api-release-notes)  for v5.0 breaking changes

**Comment by berstend** [comment]
@SBerkovic Is this something that affects `puppeteer-extra`? I don't see `puppeteer/Errors` being used anywhere?

**Comment by SBerkovic** [comment]
Its not used in `puppeteer-extra`, but users of `puppeteer-extra` maybe be using it in their implementation, and now have no access to `puppeteer.errors`.
for example
```
// before the change
const { TimeoutError } = require('puppeteer/Errors');
if (err instanceOf TimeoutError) {
    // do something
}

// after the change
const puppeteer = require('puppeteer');
const { TimeoutError } = puppeteer.errors
if (err instanceOf TimeoutError) {
    // do something
}
```

The problem is that in `puppeteer-extra`,  puppeteer.errors is not exported and not defined so it cannot be used.

**Comment by brunogaspar** [comment]
You can try to use `puppeteer.pptr.errors`.

I know it's not the proper way, but should unblock you for now if you are using this.

**Comment by SBerkovic** [comment]
Thanks @brunogaspar.
That should work
