### ISSUE TITLE
Adblocker with amp pages

### ISSUE THREAD

**Issue by vanilataher** [berstend/puppeteer-extra#289]
Most of the time there is an ad like this in amp pages. It shows up when using puppeteer-extra together with adblocker and stealth. The real page shows for a second and then everything is replaced by a single ad.

Just importing the module causes the problem, regardless of enabling it or not, and then we have to forcefully enable the adblocker. 

![image](https://user-images.githubusercontent.com/65680228/90208635-1960c400-de0b-11ea-9824-b0a9f085a4e8.png)

Url: https://bikroy.com/bn/ads

**Comment by brunogaspar** [comment]
You are more than welcome to research for a solution to that problem.

Here's the library the plugin uses behind the scenes https://github.com/cliqz-oss/adblocker maybe you should start there?

**Comment by berstend** [comment]
Closing as this is about an external dependency.
