### ISSUE TITLE
Stealth Plugin cannot bypass fingerprint

### ISSUE THREAD

**Issue by ntta** [berstend/puppeteer-extra#290]
Hi,

I'm scrapping data from [an e-commerce website](https://shop.coles.com.au/a/hoppers-crossing/specials/search/half-price-specials). The website has been using fingerprintjs2. A few months ago I found out Stealth Plugin could help me bypass the fingerprint. However, it doesn't work anymore and it looks like the website has fingerprinted my machine or browser.

When I manually open Chromium to access the website, it allows me to pass. But when I use puppeteer to control Chromium, it will be detected by fingerprint. I've tried to copy all request headers from the manual process to the automated process, but it doesn't work as well.

Is there any workaround that can help me solve this issue?

Thanks.

**Comment by HiddenToolz** [comment]
Send the url of the website then the puppeteer devs can loop about it first Oo

**Comment by ntta** [comment]
> Send the url of the website then the puppeteer devs can loop about it first Oo

I added it in the first post, thank you.

**Comment by berstend** [comment]
`fingerprintjs2` uses canvas hashes to fingerprint devices/browsers, this is currently not implemented in the stealth plugin.

Translation: The goal of the stealth plugin is to hide that you're using a scripted browser, not trying to spoof different personas. We're already working on a `fingerprint` plugin that will focus on spoofing fingerprints. :-)

Closing this for now

**Comment by yuis-ice** [comment]
same here
