### ISSUE TITLE
Is there smaller version like puppeteer core only?

### ISSUE THREAD

**Issue by shirshak55** [berstend/puppeteer-extra#30]
Currently I only use pupeeteer core as puppetter is too heavy and I already have chrome installed so I use chrome-paths and puppeteer-core which works really well. Is there any way to switch from pupeeteer to puppeteer core?

**Comment by jchook** [comment]
I think you can still specify `executablePath` when calling [`puppeteer.launch()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions).

**Comment by shirshak55** [comment]
@jchook but u are missing point that is we need to add puppeteer otherwise this library wont work. Puppetter is peer dependency. I want to use puppeteer core because its extremely lightweight :)

**Comment by jchook** [comment]
@shirshak55 according to ["puppeteer vs puppeteer-core"](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteer-vs-puppeteer-core) they have two main differences...

> 
> To sum up, the only differences between puppeteer-core and puppeteer are:
> 
> * puppeteer-core doesn't automatically download Chromium when installed.
> * puppeteer-core ignores all PUPPETEER_* env variables.
> 

You can avoid downloading chrome using the [`PUPPETEER_SKIP_CHROMIUM_DOWNLOAD`](https://github.com/GoogleChrome/puppeteer/blob/v0.10.2/docs/api.md#environment-variables) environment variable during installation. This makes `puppeteer` almost identical to `puppeteer-core` with the added benefit of convenient env vars.

e.g.  `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1 npm install puppeteer`

**Comment by shirshak55** [comment]
@jchook wow thanks :) never realized there was environment that could control whether we can download chromium or not.

**Comment by berstend** [comment]
I'll look into that a bit (to see if there are more differences between core and non-core). Definitely something I'll add to the documentation. :) Keeping this issue open for now.

**Comment by shirshak55** [comment]
@berstend hmm I think as jchook as said i can use env variable to make puppeteer act like puppeteer core :)
