### ISSUE TITLE
puppeteer.devices is undefined

### ISSUE THREAD

**Issue by honeo** [berstend/puppeteer-extra#301]
The readme.md says you can use it to replace puppeteer, but there are some properties that don't exist, like .devices.
Why is this?

**Comment by brunogaspar** [comment]
You can use `puppeteer.pptr.devices` for now.

Basically the implementation does not expose those properties, so you need to get the original Puppeteer instance by doing `puppeteer.pptr` and then call whatever you want from that instance.

Basically this is the same as https://github.com/berstend/puppeteer-extra/issues/288 but for different property.

**Comment by honeo** [comment]
Thank you!
By going through .pptr, I don't have to import puppeteer separately.

**Comment by andreconghau** [comment]
It works fine by ` puppeteer.pptr.`
```js
const device = puppeteer.pptr.devices['iPhone 8'];
await page.emulate(device);
```
