### ISSUE TITLE
Outdated @types/puppeteer version

### ISSUE THREAD

**Issue by dgergely** [berstend/puppeteer-extra#302]
In the file `packages/puppeteer-extra/package.json` the version for `@types/puppeteer` is `^2.0.0`, however `3.0.1` is already out.
Since `package.json` sets the version, I have to use that one, otherwise both versions are installed and incompatibility issues rise.

Is there any reason for pinning version `2.x`?

**Comment by berstend** [comment]
This will be fixed with #303 :-)

**Comment by berstend** [comment]
In the meantime you could overwrite the version in your own package.json (untested):

```
  "resolutions": {
    "**/@types/puppeteer": "3.0.1"
  },
```

**Comment by dgergely** [comment]
@berstend sounds great! Thanks! Any estimation when it will be released?

**Comment by berstend** [comment]
It's a complete rewrite basically, so I want to make sure nothing breaks :-) Updating tests, etc. is pretty time-consuming but it shouldn't be too long until the new version is out.

**Comment by berstend** [comment]
Closing for now, let me know if the above mentioned hotfix isn't working.

**Comment by sebastianhaberey** [comment]
Apparently, due to an open issue, [resolutions doesn't work with deps that have '/' in their name](https://github.com/yarnpkg/yarn/issues/4874).
