### ISSUE TITLE
puppeteer-extra-plugin-stealth breaks page when headless: true

### ISSUE THREAD

**Issue by cyberz** [berstend/puppeteer-extra#305]
OS: MacOS Catalina 10.15.5
NodeJS: 10.22
"puppeteer": "5.2.1",
"puppeteer-extra": "3.1.15",
"puppeteer-extra-plugin-stealth": "2.6.1",

When I try to login on https://allegro.pl/login/form with headless: true form does not submit, on screenshot I see that the page is broken

When headless: false all working fine.
When disable puppeteer-extra-plugin-stealth page also working right

No specific settings used

**Comment by berstend** [comment]
What does breaking mean? can you check the console output of the page? You could start disabling specific stealth evasions to see which one is causing issues.

Closing until there's more technical info provided.
