### ISSUE TITLE
Fails on explicitly loaded Recaptcha audio tab

### ISSUE THREAD

**Issue by Kikey-y** [berstend/puppeteer-extra#306]
On sites that load Recaptcha automatically (https://www.google.com/recaptcha/api2/demo) everything works fine, I am able to click the Recaptcha, load the images and load the audio tab if needed too.
But on websites where Recaptcha is explicitly loaded (https://developers.google.com/recaptcha/docs/display#explicit_render) I am able to click the Recaptcha, and even solve it but when I click the the audio tab, it triggers the classic error "Your computer may be sending..."
Example of a website that renders Recaptcha explicitly is https://discordapp.com/login (note that is not my target website, just an example)
Hopefully there's a fix/workaround for this, thanks!

**Comment by berstend** [comment]
Are you talking about manually solving reCAPTCHAs with the stealth plugin or the reCAPTCHA plugin not working? Please provide more info.
