### ISSUE TITLE
Being detected by distil (on 2.6.1)

### ISSUE THREAD

**Issue by trnj** [berstend/puppeteer-extra#310]
Hello! Thank you again for this plugin. 

I've upgraded to the latest version 2.6.1 and start being detected by distil.
Also, this service https://pixelscan.net/ shows that fingerprints are fake

https://prnt.sc/ue75fa

```
    const Stealth = require('puppeteer-extra-plugin-stealth');
    const puppeteer = require('puppeteer-extra')

    puppeteer.use(Stealth());

    let browser1 = await puppeteer.launch({
        headless: true,
        //   slowMo,
        ignoreHTTPSErrors: true,
        args: [
            "--disable-gpu",
            "--disable-dev-shm-usage",
            "--no-sandbox",
            '--start-maximized',
            '--window-size=1366,768',

            '--disable-web-security', // +
            //   "--single-process",
            //    "--no-zygote"

            '--allow-running-insecure-content',
            '--disable-strict-mixed-content-checking',
            '--ignore-certificate-errors',
            // "--disable-infobars"
        ],
      //  userDataDir: `/tmp/chrome`,

    });


    console.log('Running tests..')
    const page = await browser1.newPage()
    await page.setUserAgent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36");

    await page.goto('https://pixelscan.net/', {
        waitUntil: 'networkidle2',
        timeout: 10 * 1000
    });
    await page.waitFor(5000)
    await page.screenshot({path: 'test1.png', fullPage: true})
    console.log(await page.content())
    await browser1.close()

```

**Comment by trnj** [comment]
Downgraded to 2.6.0 and it works again.

You can try, for example, on this link 
https://dubai.dubizzle.com/motors/used-cars/nissan/sentra/2020/3/7/nissan-sentra-2016-top-low-emi-monthly-aed-2

Distil activates after 3-4 tries.

**Comment by trnj** [comment]
Tried on several servers and resident network at home, can confirm, that downgrading to 2.6.0 works.  On 2.6.1 being detected by distil after 3-4 tries (or within 3-4 minutes, they probably analyze collected data).

**Comment by trnj** [comment]
Ok, probably solved. In 2.6.1 if I add,

```
        const UserAgentOverride = require('puppeteer-extra-plugin-stealth/evasions/user-agent-override')

        const ua = UserAgentOverride({
            userAgent: UserAgents.WIN,

            platform: 'Win32'
        })
        puppeteer.use(ua)
```

I do not see distil.

**Comment by trnj** [comment]
Ok, the code above works.  Tested in multiple networks and works everywhere. Thank you again for the plugin.

**Comment by trnj** [comment]
Well, this issue still exists. 
It is the same as here 
https://github.com/berstend/puppeteer-extra/issues/314

2.6.1 - is being detected by distil
2.6.0 - works

**Comment by shimuldn** [comment]
> Well, this issue still exists.
> It is the same as here
> #314
> 
> 2.6.1 - is being detected by distil
> 2.6.0 - works

Same here
2.6.0 - Work
2.6.2 - IP ban

Reopen the case may help ?
