### ISSUE TITLE
Captcha solving on Linkedin doesn't work

### ISSUE THREAD

**Issue by froidefond** [berstend/puppeteer-extra#311]
Hello,

I have the same Problem as #284 .

My version of puppeteer-extra-plugin-recaptcha is **3.1.18**

On this page : `https://www.linkedin.com/checkpoint/challenge/AgF1YhmA78AsOwAAAXRyc4GCTuRI9QcrI676g6dbj78-6lgP82Fhse-NsJhyki-_H8tQonF18rP99lib1LXrXXf5gkl_mA?ut=2AJSDT9V70PVo1`

This is for the ReCaptcha you get after trying to login to Linkedin. It's pretty hard to solve as a human (lot of pictures and tests)
Not any Api request is sent when I use `await page.solveRecaptchas()` as I can see on 2captcha Dashboard

When I run with debug, here is what I get : 
```
  puppeteer-extra-plugin:recaptcha solveRecaptchas +0ms
  puppeteer-extra-plugin:recaptcha findRecaptchas +0ms
  puppeteer-extra-plugin:recaptcha hasRecaptchaScriptTag false +0ms
  puppeteer-extra-plugin:recaptcha _generateContentScript findRecaptchas undefined +0ms
  puppeteer-extra-plugin:recaptcha findRecaptchas { captchas: [], error: null } +0ms
  puppeteer-extra-plugin:recaptcha solveRecaptchas { captchas: [], solutions: [], solved: [], error: null } +0ms
```

And the result of await page.solveRecaptchas() is : 
`{ captchas: [], solutions: [], solved: [], error: null }`

You can see in the screenshots the ReCaptcha I'm trying to solve and how it is visible in the Dom.

<img width="1577" alt="Capture d’écran 2020-09-09 à 13 17 53" src="https://user-images.githubusercontent.com/25334435/92591915-0c66b180-f29f-11ea-8c65-c47684880b4b.png">
<img width="1577" alt="Capture d’écran 2020-09-09 à 13 18 56" src="https://user-images.githubusercontent.com/25334435/92591926-0ffa3880-f29f-11ea-9b8b-da7270cab70a.png">

Thank you for your help 🙂

**Comment by josselinlbe** [comment]
J’espère que ça ne concerne pas neodeal. ¯\_(ツ)_/¯

![2020-09-16 01_52_33-Window](https://user-images.githubusercontent.com/15314417/93276217-4fed7e00-f7bf-11ea-8934-9ae1a0ec50e7.png)

**Comment by froidefond** [comment]
Plaît-il ?

**Comment by brunogaspar** [comment]
Please write only in english.

Thanks!

**Comment by PavelZubkov** [comment]
you call solveRecaptchas() before captcha load. Try waitFor*

**Comment by berstend** [comment]
No code provided, closing.
