### ISSUE TITLE
Captcha Image

### ISSUE THREAD

**Issue by hansputera** [berstend/puppeteer-extra#313]
How to bypass captcha image?

**Comment by itsdarrylnorris** [comment]
Hey @hansputera 

What type of captcha are you trying to resolve? If you are trying to solve ReCaptcha you can use our[ ReCaptcha plugin
](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-recaptcha), which connects with a third party service called 2captcha and that will resolve it for you.

**Comment by hansputera** [comment]
i trying to solve captcha image

**Comment by itsdarrylnorris** [comment]
Hey @hansputera there are multiple services / libraries that has captcha image. Do you have some code or link to the captcha that you are trying to solve?

**Comment by hansputera** [comment]
i'm using 2captcha, but that doesn't work

**Comment by itsdarrylnorris** [comment]
Hey @hansputera ,

Can you share some code of the captcha and/or the code you are using to try to solve the captcha? The lack of details makes it very difficult for other people to help out.

**Comment by Emobe** [comment]
There are different captchas. If it's not ReCaptcha, it's likely you should send a screenshot to 2captcha instead

**Comment by berstend** [comment]
Currently only reCAPTCHAs are supported by the plugin. We'll eventually support hCaptcha but no plans for regular image captchas currently.
