### ISSUE TITLE
Stealth plugin: Use latest chrome version in user agent

### ISSUE THREAD

**Issue by sydney-d** [berstend/puppeteer-extra#317]
Hello,

Wouldn't it be safer to use the latest Chrome version in the user agent, instead of using the puppeteer's Chrome version ?
How can I do it while using stealth-plugin ?

Thanks

**Comment by Niek** [comment]
If this is what you want to achieve, fetch https://omahaproxy.appspot.com/all.json in your code and set the user agent to the latest (Windows?) stable version.

**Comment by sydney-d** [comment]
Thanks !

One last question :
What's the best way to override the user agent when using stealth plugin ? 
the method described here : 
https://github.com/berstend/puppeteer-extra/blob/c44c8bb0224c6bba2554017bfb9d7a1d0119f92f/packages/puppeteer-extra-plugin-stealth/evasions/user-agent-override/readme.md

or plain old : 
`page.setUserAgent(userAgent)` ? 

Thanks again

**Comment by Niek** [comment]
The stealth version is the way to go. The standard puppeteer one is very easily detectable.
