### ISSUE TITLE
Problems with the default tab page

### ISSUE THREAD

**Issue by alwans** [berstend/puppeteer-extra#319]
When I use the default tab to open https://bot.sannysoft.com
------------------------------------------------------------
async function test(){
	const browser = await puppeteer.launch({
		executablePath: chromePaths.chrome,
		headless: false,
	})
	const pages = await browser.pages();
	const page = pages[0]
	// const page = await browser.newPage();
	await page.setViewport({ width: 1980, height: 800 });
	await page.goto('https://bot.sannysoft.com');
}
test();
----------------------------------------------------------
result：
WebDriver(New) | present (failed)
WebGL Vendor | Google Inc.

**Comment by Niek** [comment]
Don't use the existing tab, open a new page and the puppeteer-extra evasions will be used there.
