### ISSUE TITLE
Not detecting all recaptchas

### ISSUE THREAD

**Issue by Joxroxagain** [berstend/puppeteer-extra#32]
This plugin works great on some sites, but it seems to fail to detect the recaptcha on others. For example, it does not work for me on this site: https://demo.codeforgeek.com/google-captcha/

Any ideas as to why this is happening? Could I be doing something wrong? If not, how could I fix this?

**Comment by Joxroxagain** [comment]
I did some experimentation and it seems that the `findRecaptchas()` function can easily be modified to fix this issue for all the sites I have tested by removing the first step which searches for script tags.

**Comment by ilyadev3301** [comment]
what did you modify? I have a similar issue where findRecaptchas() isnt picking up anything.

**Comment by Joxroxagain** [comment]
@ilyadev3301 I don't remember exactly but it was something to do with removing the code that checks for script tags
