### ISSUE TITLE
Useless deepmerge

### ISSUE THREAD

**Issue by zdm** [berstend/puppeteer-extra#320]
Hi.
Are you sure, that deepmerge is needed here:
```
    async launch(options) {
        // Ensure there are certain properties (e.g. the `options.args` array)
        const defaultLaunchOptions = { args: [] };
        options = merge(defaultLaunchOptions, options);
```
Why not just write:
```
async launch(options = {}) {
    if (!options.args) options.args = [];
```

I am asking, because deepmerge works incorrectly in my case. I need to pass `options.proxy` as instance of `Proxy` class, but deepmerge converts it to the plain object.

**Comment by zdm** [comment]
Or do not merge, if object is not a plain object:
```
const isPlainObject = require('is-plain-object')
merge(target, source, {
    isMergeableObject: isPlainObject
});
```

**Comment by Niek** [comment]
Feel free to submit a PR, but please be aware that ``if (!options.args) options.args = [];`` is something very different than merging the two option arrays.

**Comment by zdm** [comment]
PR
https://github.com/berstend/puppeteer-extra/pull/322

**Comment by Niek** [comment]
Closing this in favor of #322
