### ISSUE TITLE
EvalError when using StealthPlugin

### ISSUE THREAD

**Issue by bmeloski** [berstend/puppeteer-extra#321]
Hello.

I came across strange issue - on some of the websites puppeteer alone works flawlessly but when I activate stealth plugin I get:

**Error: EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".**

    at <anonymous>:4:70
    at Array.map (<anonymous>)
    at <anonymous>:4:37
    at <anonymous>:8:9

code that gives me error:

    const puppeteer = require('puppeteer-extra');
    const stealthPlugin = require('puppeteer-extra-plugin-stealth');

    puppeteer.use(stealthPlugin());

code without error:

    const puppeteer = require('puppeteer-extra');

**Comment by AndrejGajdos** [comment]
+1

**Comment by trnj** [comment]
There is a bug in 2.6.1.  Wait for the next release. Also try in 2.6.0 and then report

**Comment by bmeloski** [comment]
I tried 2.6.0 and nothing changes. I even tried 2.50 and same results

**Comment by trnj** [comment]
Provide full code to reproduce this issue.

**Comment by bmeloski** [comment]
Can I send you private message? Its Data Sensitive.

**Comment by trnj** [comment]
Ok

**Comment by bmeloski** [comment]
I can't  find email on your profile @trnj , so I hopped on discord channel I will send it there

**Comment by trnj** [comment]
Ok, my nick is VT on this channel. Send code, I will dig today

**Comment by Niek** [comment]
Can you try to make a minimally reproducible page/script so we can check?

**Comment by trnj** [comment]
Ok, I've solved it. 

Just put this line and the error will disappear 
`await page.setBypassCSP(true)`

**Comment by Niek** [comment]
Thanks, closing this issue.
