### ISSUE TITLE
onPageCreated hooks should be called synchronously

### ISSUE THREAD

**Issue by zdm** [berstend/puppeteer-extra#323]
Hi.
Usually code in this hook used to setup new opened page (set user agent, timezone, configure viewport, ...), so users expected, that after `await browser.newPage()` call new page is completely configured and ready to use. 
But currently `onPageCreated` plugins method is called asynchronously from event, so some functionality can not be ready immediately after `newPage()` is finished.
I think, that better is to override `browser.newPage()` method and call `onPageCreated` synchronously from there.
What do you think?

**Comment by berstend** [comment]
Hey there, this behavior will change in #303 (instead of each plugin adding it's own event listener those events will be fired from the mothership). :-)
