### ISSUE TITLE
Idea: timezone plugin

### ISSUE THREAD

**Issue by trnj** [berstend/puppeteer-extra#325]
Hello,

I've found an issue on some OS, like ubuntu. 

Example: https://prnt.sc/ui2f8h  

The default timezone is
`Time zone: Etc/UTC (UTC, +0000)`

So the browser shows African timezone (which is UTC 0000),

We could detect timezone based on IP address and correct it like

> env: {
>                 TZ: 'Europe/London',
>                 ...process.env
>             }

As a safeguard, this could help in case server OS provides incorrect info. 

Also, it could potentially fix the problem when you connect via the proxy.

If I am correct, when you connect via the proxy, timezone will be the same as on your OS (even if you have a correct timezone).

**Comment by evading-bot-detection** [comment]
Yes, Pixelscan.net is detecting this as well. If the browser timezone does not match the IP timezone, it gets flagged. Very likely this is part of detection algorithms.

**Comment by trnj** [comment]
It is likely the end-user has an incorrect timezone, maybe false positive for bot protection, but a good indicator anyway. 

I think it is possible to get IP of the server and check in maxmind lib, then set timezone.

**Comment by Niek** [comment]
Simply set the TZ variable when launching your node script. For example: ``TZ="Europe/London"`` or ``TZ="Europe/Amsterdam"``. I don't think it's useful to make a separate script for it.

**Comment by trnj** [comment]
> Simply set the TZ variable when launching your node script. For example: `TZ="Europe/London"` or `TZ="Europe/Amsterdam"`. I don't think it's useful to make a separate script for it.

For example, when I launch Puppeteer in the new geographic area, I need to figure out the timezone for IP address. If launch Puppeteer in the US, I will need to set the correct timezone. 

Also, if I use proxy / VPN and change IP, the timezone will not be changed in the browser. For example, I have a server in the UK, with timezone TZ="Europe/London".  If I change proxy to the US IP address, the timezone is still "Europe/London".

**Comment by brunogaspar** [comment]
Can't you use the `page.emulateTimezone()` method?

**Comment by trnj** [comment]
> Can't you use the `page.emulateTimezone()` method?

Yes, but I need to know the current timezone to emulate. When I enable a new proxy from a new country, I need to know the correct timezone for the IP provided.

**Comment by brunogaspar** [comment]
Then just go get those details i guess :)

Not seeing why you would need a dedicated plugin for this?

**Comment by Niek** [comment]
I'm with @brunogaspar here, I don't see how a plugin would help. Seems like you need to write some logic to get your current IP, get the timezone location for this IP and then use that.

**Comment by trnj** [comment]
I thought maybe it would be useful to solve it out of the box.

**Comment by trnj** [comment]
When there is a change of proxy, set correct timezone automatically. Also, when people launch the browser on server with incorrect timezone, correct it. 

It is easy to implement, but I see people in the issue tracker provide screenshots with incorrect timezones.

**Comment by Niek** [comment]
Jus do something like this:
```js
const fetch = require('cross-fetch');

let info = await (await fetch('https://ipinfo.io/json')).json();
await page.emulateTimezone(info.timezone);
```
