### ISSUE TITLE
Captcha detected and solved... but not going away??

### ISSUE THREAD

**Issue by jeremythille** [berstend/puppeteer-extra#326]
I  believe I set up everything right, topped up my 2captcha account and all.

When I launch Puppeteer in non-headless mode, I can see the page opening with the captcha, which becomes purple (meaning it's been detected). Then, after a couple of seconds, it becomes green (meaning it's been solved). So far so good.

But then what? No navigation is happening. The captcha is green, granted, but visually it doesn't get a checkmark or a completion animation or anything. Nothing changes. If I try to reload the page or move on with my script, I stumble upon another captcha.

Example of captcha URL for the record : https://bit.ly/32AOhiR (I shortened the link because it's very long)

I'm not sure what to do now. My code :

```
const options = {
	headless: true,
	executablePath: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
	ignoreHTTPSErrors: true,
	args: [`--window-size=1024,768`]
}

const browser = await puppeteer.launch(options);

const page = await browser.newPage();

await page.goto(url, { waitUntil: 'networkidle2' });

console.log(`Awaiting captchas resolution...`);

const { captchas, solutions, solved, error } = await page.solveRecaptchas() // https://www.npmjs.com/package/puppeteer-extra-plugin-recaptcha

console.log(`CAPTCHAS = `, captchas); // Array of one object with the key "hasResponseElement":true
console.log(`SOLUTIONS = `, solutions); // Array of one object with the key "hasSolution":true
console.log(`SOLVED = `, solved); // Array of one object : { "responseElement": true, "responseCallback": false, "isSolved": true }
console.log(`ERROR = `, error); // no error
```

Is it a bug? Or am I doing something wrong?

**Comment by berstend** [comment]
Can you try again with the latest recaptcha plugin version? If that doesn't fix it please create a new issue with debug output (mentioned in the readme how to do that).
