### ISSUE TITLE
PixelScan fingerprint inconsistent

### ISSUE THREAD

**Issue by d3vnick** [berstend/puppeteer-extra#331]
What I'm doing wrong here? pixelscan.net says I have inconsistent fingerprint.
Code and pixelscan screenshot follows:

## Code
```js
const puppeteer = require('puppeteer-extra')
const StealthPlugin = require('puppeteer-extra-plugin-stealth')
puppeteer.use(StealthPlugin())
const AdblockerPlugin = require('puppeteer-extra-plugin-adblocker')
puppeteer.use(AdblockerPlugin({ blockTrackers: true }))

const headless = true

puppeteer.launch({
  headless: headless,
  ignoreHTTPSErrors: true,
  slowMo: 0,
  args: ['--window-size=1380,800',
    '--remote-debugging-port=9222',
    "--remote-debugging-address=0.0.0.0",
    '--disable-gpu', "--disable-features=IsolateOrigins,site-per-process", '--blink-settings=imagesEnabled=true'
  ]
})
  .then(async browser => {
  const url = 'https://pixelscan.net/'
  console.log(`Connecting to ${url}`)
  const page = await browser.newPage()
  await page.evaluateOnNewDocument( () => {
    Object.defineProperty(navigator, 'platform', {get: () => 'Linux x86_64'})
  })

  await page.goto(url)
  await page.waitForTimeout('5000')

  await getScreenshot(url);

  console.log(`Done`)
  await browser.close()
  process.exit(0)

  async function getScreenshot(url) {
    console.log('Get screenshot')
    const hostname = (new URL(url)).hostname
    const screenshot = `../screenshots/${hostname}.png`;
    await page.screenshot({path: screenshot, fullPage: true})
    console.log(`Screenshot saved: ${screenshot}`)
  }

})

```

## Pixelscan screenshot
![image](https://user-images.githubusercontent.com/35925468/93666876-7b02f680-fa79-11ea-93fe-54241b158eb4.png)

**Comment by prescience-data** [comment]
Chances are your hardware/webgl hash is not matching the known hash of that hardware profile. 
Can you run PixelScan on the same PC normally and screenshot the hash? I'd expect it matches the current hash but your renderer and webgl version are different.

![image](https://user-images.githubusercontent.com/65471523/93707830-162cc680-fb75-11ea-98e0-4efd1086e0c3.png)

**Comment by d3vnick** [comment]
Thank for the answer.
Here the normal result from my browser

![image](https://user-images.githubusercontent.com/35925468/93867500-0de1a200-fcc1-11ea-9a69-3d1a0c645338.png)

**Comment by prescience-data** [comment]
At first I thought it was strange they were different hashes, but then I realised it seems like you're booting the default Chromium install rather than Chrome. 

Can you add this to your puppeteer config and get the screenshot of the hashes again from puppeteer?

```js
{
	headless: false,
	executablePath: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
	// ...
}
```

**Comment by evading-bot-detection** [comment]
is there a solution to this yet? once this is fixed we can narrow down issues on other sites

**Comment by prescience-data** [comment]
> is there a solution to this yet? once this is fixed we can narrow down issues on other sites

Unlikely to get a short term solution to canvas renders coming up inconsistent when compared to known values if forging webgl renderer and vendor.

There may be other issues causing the inconsistent result, but that is the major one. 

Short-term, the only "solution" is to stop forging your webgl and renderer, however this is not practical for anyone executing from the cloud.

**Comment by d3vnick** [comment]
## Plus `executablePath`
This is the result adding: (I am not on Win, Ubuntu + kde plasma)
```
executablePath: '/usr/bin/google-chrome'
```

![image](https://user-images.githubusercontent.com/35925468/94250336-00265980-ff19-11ea-9bb1-1231cb856d06.png)

## Plus `executablePath` and `headless: false`
```
headless: false,
executablePath: '/usr/bin/google-chrome'

```

![image](https://user-images.githubusercontent.com/35925468/94250844-aa9e7c80-ff19-11ea-83e6-32e0b0ab212b.png)

**Comment by d3vnick** [comment]
>Additionally what was your use case for '--disable-gpu' ?
My understanding is that disabling the GPU consume less resources. I am thinking to use an Raspberry Pi to automate some scraping so resources are limited.

**Comment by prescience-data** [comment]
So if you look at your `Canvas Hash` output, you can see it's different despite the WebGL vendor and renderer being the same.

I wouldn't worry about it too much as there are privacy products that are starting to obfuscate fingerprints as plugins etc, so it's more of an "orange flag" than a "red flag". 

Unless you are experiencing any major issues with your actual production tasks, I wouldn't let it worry you.

**Comment by berstend** [comment]
The stealth plugin will change the WebGL vendor/renderer from one obviously used by headless browsers to one typically used in headful Chromes (can also be set to a custom one). Modifying generated canvas/webgl/audio hashes (also known as fingerprinting) is currently not covered by the stealth plugin.

We have stuff in the works to tackle fingerprinting but currently you'd need to use different hardware as prescience mentioned.

Closing in favor of #101
