### ISSUE TITLE
Puppeteer-extra does not perform `scrollIntoView` when `click` on element

### ISSUE THREAD

**Issue by aravael** [berstend/puppeteer-extra#335]
When I use puppeteer, this part of code goes to the page, clicks onto an element whenever it is visible or not:
```
await page.goto('http://my-url');
await Promise.all([
  page.click('#theLink'),
  page.waitForNavigation()
]);
```

With puppeteer-extra I can get the same behavior only with this:
```
await page.goto('http://my-url');
await page.evaluate(() => {
  document.querySelector('#theLink').scrollIntoView();
});
await Promise.all([
  page.click('#theLink'),
  page.waitForNavigation()
]);
```

An example code I grabbed from https://github.com/puppeteer/puppeteer/issues/2750

**Comment by berstend** [comment]
I wouldn't know how `puppeteer-extra` would affect this behavior, there's nothing in the code remotely touching this.

My guess is that it's a dependency issues (e.g. using an older pptr version with extra). Feel free to comment with more technical info (versions, which plugins, reproducible test case, etc).
