### ISSUE TITLE
Getting detected on http://arh.antoinevastel.com/bots/areyouheadless

### ISSUE THREAD

**Issue by FoonkG** [berstend/puppeteer-extra#337]
Puppeteer stealth is getting detected by areyouheadless.

I'm using puppeteer stealth with chrome (not chromium).

Any help is appreciated.

![image](https://user-images.githubusercontent.com/54715823/94187269-029c9b00-fea8-11ea-8445-a304bd2d8839.png)
![image](https://user-images.githubusercontent.com/54715823/94187323-12b47a80-fea8-11ea-988a-f65d90cd8571.png)

**Comment by evading-bot-detection** [comment]
I just tried with default settings and got a passing result on http://arh.antoinevastel.com/bots/areyouheadless but the same result on bot.sannysoft.com 

Are you sure you are using the latest version?

**Comment by prescience-data** [comment]
What launch flags are you passing to Chrome?

**Comment by FoonkG** [comment]
I'm only using `--no-sandbox`

**Comment by FoonkG** [comment]
Looks like setting an extra http header caused it to be detected
