### ISSUE TITLE
Puppeteer-extra-stealth totally fails the cat and mouse game!

### ISSUE THREAD

**Issue by yassermkali** [berstend/puppeteer-extra#339]
Browser fingerprint techniques are way more sophisticated than simple evasion methods here.

Check for example:

https://shop.coles.com.au

**Comment by prescience-data** [comment]
`extra` is designed to solve the "Are you using Puppeteer" problem, not the "Complete Anti-Fingerprinting" problem.

**Comment by berstend** [comment]
@yassermkali don't use it then :-)
