### ISSUE TITLE
HEADCHR_IFRAME fails in headless

### ISSUE THREAD

**Issue by FedericoMorrone** [berstend/puppeteer-extra#34]
The HEADCHR_IFRAME always fail in headless mode but works fine in headful mode

![testresult](https://user-images.githubusercontent.com/35099273/56094853-4af41300-5ed7-11e9-89d5-bc6931c94fd4.png)

**Comment by r1si** [comment]
Hi @FedericoMorrone have u resolved? 
I think u must use this old evasion https://github.com/berstend/puppeteer-extra/commit/849c0326ba456dbdc239c92ff3e3d2deaf7ec82a?_pjax=%23js-repo-pjax-container
