### ISSUE TITLE
puppeteer-extra-plugin-recaptcha method's solveRecaptcha is not working (at least, for me)

### ISSUE THREAD

**Issue by CarlosMunozDiaz** [berstend/puppeteer-extra#340]
In first place, sorry for my English. I have not written in English for too many months and, perhaps, I could make some mistakes.

I am writting this issue because, since August 14th, I am using this plugin to avoid recaptchas in a webpage to extract some HTML information. Until the last Friday (September 25th), everything was good: recaptchas were resolved and I could extract information I wanted. 

But today **it is not possible to avoid the recaptcha**. I have been using some page.waitFor(milliseconds) to see what was happening and it seems that the plugin is no longer capable to avoid it because the plugin 'clicks' on it but nothing happen after that. If I **console.log the solveRecaptcha()** response this appears:

`{
   captchas: [
     {
       sitekey: '6Lcj-R8TAAAAABs3FrRPuQhLMbp5QrHsHufzLf7b',
       callback: 'handleCaptcha',
       id: 'wpxk3jqhdjd2',
       widgetId: 0,
       display: [Object],
       url: 'https://www.example/com',
       hasResponseElement: true
     }
   ],
   solutions: [],
   solved: [],
   error: 'Error: Please provide a solution provider to the plugin.'
}`

I leave hear some parts of my code if it could help you to understand the problem (**maybe Google has improved their recaptchas during the last weekend?**):

**Dependencies**:
"puppeteer": "^5.2.0",
"puppeteer-extra": "^3.1.12",
"puppeteer-extra-plugin-recaptcha": "^3.1.10",
"puppeteer-extra-plugin-stealth": "^2.4.13"

**Code example**:
```
const puppeteer = require('puppeteer-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
var userAgent = require('user-agents');
puppeteer.use(StealthPlugin());
```
```
let scrape = async () => {
    const RecaptchaPlugin = require('puppeteer-extra-plugin-recaptcha');
    puppeteer.use(
        RecaptchaPlugin({
            provider: { id: '2captcha', token: 'XXXXXXX' },
            visualFeedback: true // colorize reCAPTCHAs (violet = detected, green = solved)
        });
    );


    const browser = await puppeteer.launch({ headless: true, defaultViewport: null });
    let page = await browser.newPage();
    await page.setDefaultNavigationTimeout(0);
    await page.setUserAgent(userAgent.toString());

    await page.goto('https://www.example.com/', {waitUntil: 'domcontentloaded', timeout: 0});
    let example= await page.solveRecaptchas();
    console.log(example); //Previous answer in this post

    //Extract code...
}

scrape();
```

**If you need the right URL, I could give you**. No problem.

Thank you for incredible job and sorry for any inconvenience I could haved caused.

**Comment by berstend** [comment]
Could you try again with the latest reCAPTCHA plugin version? There's also a debug mode that should give you more info (mentioned in the readme how to do that).

If the issue still persists please join our chat and mention it there: https://github.com/berstend/puppeteer-extra/wiki/Scraping-Chat

**Comment by GGWilliams** [comment]
This error could occur because you either didn't provide a token, typed the token in wrong, your token changed, you don't have anymore token uses left, or you deployed your code and didn't provide environment variables.
