### ISSUE TITLE
WhatLeaks.com shows inconsistent OS properties

### ISSUE THREAD

**Issue by evading-bot-detection** [berstend/puppeteer-extra#342]
Pixelscan.net has been showing an "inconsistent fingerprint" message. Whatleaks.com indicates that this is coming from the OS. 

According to WhatLeaks.com, this happens because:

"Checks inconsistency of your browser properties (operation system) (operation system in useragent does not correspond with navigator.oscpu; or operation system in useragent does not correspond with navigator.platform; or navigator.plugins property is undefined (this is only possible for IE in Windows) and operation system of useragent is not Windows; or there are properties of mobile browsers: "ontouchstart" in window, navigator.maxTouchPoints, navigator.msMaxTouchPoints, but useragent browser type is not mobile)"

![stealth - whatleaks](https://user-images.githubusercontent.com/68316580/94754330-cce33080-0345-11eb-90a8-d10ac710415f.png)

**Comment by evading-bot-detection** [comment]
I suspect this flag being set off is the reason behind detection on a number of sites.

**Comment by evading-bot-detection** [comment]
Also, this shows its not as simple as HTTP user agent must equal JS user agent. That is true for the browser I used, but still set off a flag. Normal chrome did not.

**Comment by berstend** [comment]
This is very theoretical, which exact properties are causing issue here?

**Comment by berstend** [comment]
Is your UA set to Windows?

**Comment by evading-bot-detection** [comment]
My UA was unmodified in this case. I am using all default settings.

Can you please try and see if you get the same result?

**Comment by berstend** [comment]
By default the `user-agent-override` plugin will set your OS to windows, I recommend experimenting with that.

Closing this until there's more technical content.
