### ISSUE TITLE
 puppeteer-extra-plugin-stealth get detected by an advanced antibot solution

### ISSUE THREAD

**Issue by MrBot45** [berstend/puppeteer-extra#348]
Hello, it looks like https://lhcdn.botprotect.io/ detect the module. Is there anyway round it?

**Comment by blacktippen** [comment]
No, botprotect has too many checks it'd be really hard to actually make something that can have a workaround for it

**Comment by MrBot45** [comment]
Can someone try atleast? 😞

**Comment by Limes420** [comment]
Yes, I have tried Spyglass Mosaic browser and it bypass's botprotect.

**Comment by blacktippen** [comment]
Spyglass Mosaic browser Wont work due to how botprotect is made

**Comment by heh** [comment]
Can anyone help with bypassing botprotect detections?

**Comment by berstend** [comment]
Guys 😄 This is not rocket science: Just check what the site in question is doing, either
- by analyzing their script files (they might be minified/obfuscated but this can often be reversed)
- setting up fake browser APIs (e.g. `HTMLCanvasElement`) that report back when being accessed

If you're unable to do that: I'm working on a paid `stealth-pro` plugin which will feature new and improved stealth features (no ETA yet, will finish playwright support first).

Closing this for now until there's more technical meat in this discussion.

**Comment by Limes420** [comment]
> Spyglass Mosaic browser Wont work due to how botprotect is made

It was sarcasm

**Comment by prescience-data** [comment]
Hmmmm.... 

`view-source:https://lhcdn.botprotect.io/`

![image](https://user-images.githubusercontent.com/65471523/95677359-ae681980-0c10-11eb-9b1f-b1d1ddf5958d.png)

![image](https://user-images.githubusercontent.com/65471523/95677384-e3746c00-0c10-11eb-8627-86bb3f7f52c8.png)

**Comment by MrBot45** [comment]
It doesn't work... I can't bypass it

**Comment by berstend** [comment]
@MrBot45 it looks like you forgot to add a disclaimer that the page you linked is yours. Given your wording it even seems like a cheap "advertising" attempt of sorts, which is bad form and yields you negative karma points on the interwebz. Please refrain from doing that in the future, thanks.
