### ISSUE TITLE
puppeteer-extra-plugin-stealth getting blocked by google

### ISSUE THREAD

**Issue by Arun-N** [berstend/puppeteer-extra#349]
Hi! I'm using puppeteer-extra-plugin-stealth along with a rotating proxy service. But I'm getting blocked by google ("Our systems have detected unusal traffic ......" page) quite frequently. I did a test with 24 runs out of which 16 got blocked. I have all the evasions enabled (default settings). Do I need to do something extra on top of this?

**Comment by itsdarrylnorris** [comment]
Hey @Arun-N ,

In my experience not getting detected by Google it could be hard sometimes. Do you have any type of code that you could shared with us to see if maybe there is something wrong with your code? Or at the very least which Google page / product you are trying to automated or scrape?

**Comment by Arun-N** [comment]
Hi @itsdarrylnorris, I can't post the exact code here since it contains some sensitive info without which it won't run; but it's quite simple. I am trying to go to a google 'search result' page (http://www.google.com/search?q=${query}&num=30&btnG=Search) and get all the links on that one page. This is being used as an api from lambda, so I'm using [chrome-aws-lambda](https://github.com/alixaxel/chrome-aws-lambda) instead of normal puppeteer, and have set it up correctly as shown [here](https://www.npmjs.com/package/puppeteer-extra) (using .use(StealthPlugin()), removing --disable-notifications from args etc.)
I also tested it out by going to https://intoli.com/blog/not-possible-to-block-chrome-headless/chrome-headless-test.html

What's happening is if I call the puppeteer code multiple times with different queries, some times it will work fine while others get bot blocked by google.

Also, is there some way to know what user agent and navigator details are being used by puppeteer-extra-stealth in the current run for debugging?

**Comment by berstend** [comment]
> Also, is there some way to know what user agent and navigator details are being used by puppeteer-extra-stealth in the current run for debugging?

It's in the documentation (each evasion has it's own readme).

Scraping Google SERPs is not easy, that's why specialized services exists that [command a premium price](https://serpapi.com/pricing) for that.

What you describe sounds like your IPs are being tainted (aka too often used to scrape SERPs).
