### ISSUE TITLE
Bug still exists in options

### ISSUE THREAD

**Issue by MrJmpl3** [berstend/puppeteer-extra#351]
@brunogaspar The bug still, I have update packages

Related: https://github.com/berstend/puppeteer-extra/issues/223

**Comment by brunogaspar** [comment]
That's quite vague.

We need reproducible code and exact versions you're using.

I personally can't reproduce the problem anymore.

**Comment by MrJmpl3** [comment]
Oh, I will reproduce the bug.

puppeteer@5.3.1
puppeteer-extra-plugin-stealth@2.6.2
puppeteer-extra@3.1.15
puppeteer-extra-plugin@3.1.7
@types/puppeteer@2.1.5

**Comment by itsdarrylnorris** [comment]
@MrJmpl3 ,

Can you include some code?

**Comment by MrJmpl3** [comment]
```ts
import puppeteer from "puppeteer-extra";
import StealthPlugin from "puppeteer-extra-plugin-stealth";
import { Page } from "puppeteer";

const startScraper = () => {
 const browser = await puppeteer.launch();
 await browser.newPage()
 await browser.close();
}

puppeteer.use(StealthPlugin());
startScraper();
```
