### ISSUE TITLE
Plugin: block-resources collides usage with adblocker. 

### ISSUE THREAD

**Issue by kirbdee** [berstend/puppeteer-extra#352]
If a resource is already being handled, could we have a flag to complain quietly and just continue?

**Comment by berstend** [comment]
Unfortunately it's an architectural limitation in puppeteer (and by extension in the Chrome Devtools Protocol). There are situations where having 2 plugins do request interception might cause unwanted side-effects.

Regarding blocking resources (and even ads) there's now a native way in CDP to accomplish that without request interception:

```js
const blockedResources = [
  // Assets
  '*/favicon.ico',
  '.css',
  '.jpg',
  '.jpeg',
  '.png',
  '.svg',
  '.woff',

  // Analytics and other fluff
  '*.optimizely.com',
  'everesttech.net',
  'userzoom.com',
  'doubleclick.net',
  'googleadservices.com',
  'adservice.google.com/*',
  'connect.facebook.com',
  'connect.facebook.net',
  'sp.analytics.yahoo.com',
]

await page._client.send('Network.setBlockedURLs', { urls: blockedResources });
```

I intent to make a super light-weight adblock plugin with the above method (whenever I find the time). :-)

**Comment by Write** [comment]
Thanks @berstend for the `Network.setBlockedURL`. I used your solution and it worked great until i updated to npm 6.14.8 today.

Acutally, I now have the same issue as here : https://github.com/berstend/puppeteer-extra/issues/352#issuecomment-714525801

If i set `setRequestInterception` to `true` page will just forever load (even if it's the first page, unlike the issue i linked)

I know it's not an issue on your side but i just wanted to give a heads up.

**Comment by kirbdee** [comment]
Does this currently work? seems that puppeteer had this at one point but decided to remove it

https://github.com/puppeteer/puppeteer/issues/1

**Comment by berstend** [comment]
I never had issues with `Network.setBlockedURL` 😄 

Closing in favor of #364
