### ISSUE TITLE
Incognito browser context shares the same cookies

### ISSUE THREAD

**Issue by jjason685** [berstend/puppeteer-extra#36]
When creating an incognito context with puppeteer-extra it shares the same cookies. However, the incognito context works fine with default puppeteer. 

Example server gist: https://gist.github.com/jjason685/20d83ab49bff9a40d1d9d41427145bbd
Example test gist: https://gist.github.com/jjason685/79bf37acba80a2c1f0af4f6c7a1cdf37

Log output: 

No cookie, sending.
Received cookie from instance

Clearly depicting that the cookies are shared.

**Comment by bernardo-unocero** [comment]
I'm having the same issue

**Comment by lijowilson** [comment]
@bernardo-unocero  with the above logic, was it opening chromium with incognito mode or default mode.. Becuase for me it was not opening incognito window with puppeteer-extra

**Comment by bernardo-unocero** [comment]
@lijowilson Yes, the issues is that context = browser.createIncognitoBrowserContext(); context.newPage() isn't opening an incognito window.

**Comment by berstend** [comment]
Fixed in `puppeteer-extra@2.1.6`
