### ISSUE TITLE
visibilityState evasion

### ISSUE THREAD

**Issue by andrisi** [berstend/puppeteer-extra#361]
I'm working with a site which seems to detect if the browser (puppeteer) window is visible or minimised. I tried to search for "visibilityState" in this repo, but I don't see references to it so I guess you don't do any magic tricks around it yet. I can assist if you message me.

**Comment by jeroenvisser101** [comment]
You might be able to use [page.bringToFront](https://pptr.dev/#?product=Puppeteer&version=v5.4.1&show=api-pagebringtofront) in headful mode. Maybe [Emulation.setFocusEmulationEnabled](https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setFocusEmulationEnabled) could help as well?

**Comment by andrisi** [comment]
Thanks, I'll try these. The page works even if it's not in focus/front, but not if it is minimised.

**Comment by jeroenvisser101** [comment]
If the page is marked as minimized, you might be able to set a different state with [Browser.setWindowBounds](https://chromedevtools.github.io/devtools-protocol/tot/Browser/#method-setWindowBounds), using `{windowId, bounds: {windowState: "minimized}}`

**Comment by andrisi** [comment]
The site I work with runs fine in the new Puppeteer (5.4.1) so I'm fine, though it does seem to care about visibilityState so you might still want to evade that in this plugin. Thanks.

**Comment by berstend** [comment]
Is there any potential downside to just always enable `Emulation.setFocusEmulationEnabled`? Otherwise we could make a quick evasion plugin for that.

**Comment by jeroenvisser101** [comment]
It might require calling `page.focus()` before a page becomes interactive again, like is the case on headful, but I'm not sure

**Comment by berstend** [comment]
Closing for now, if there's a way to detect headless through the visibility API please reopen.
