### ISSUE TITLE
Can't build TS project via tsc, on all versions the Debugger type is used - which does not exist.

### ISSUE THREAD

**Issue by sanderv1992** [berstend/puppeteer-extra#362]
Can't build TS project, on all versions the Debugger type is used - which does not exist.

**error:**
```
node_modules/puppeteer-extra-plugin/dist/index.d.ts:1:10 - error TS2305: Module '"../../../src/debug"' has no exported member 'Debugger'.

1 import { Debugger } from 'debug';
           ~~~~~~~~


Found 1 error.
```

**node:** v12.19.0
**packages:**
```
"puppeteer-core": "5.3.0",
"puppeteer-extra": "3.1.9",
"puppeteer-extra-plugin-stealth": "2.6.1",
"chrome-aws-lambda": "5.3.1",
"puppeteer": "5.3.1"
```

<img width="422" alt="Screenshot 2020-10-30 at 15 57 52" src="https://user-images.githubusercontent.com/13352120/97714168-7d6d5d00-1ac9-11eb-844c-e826371dae9f.png">

<img width="736" alt="Screenshot 2020-10-30 at 15 57 56" src="https://user-images.githubusercontent.com/13352120/97714172-7e9e8a00-1ac9-11eb-96f3-0488cc466a6a.png">

**Comment by berstend** [comment]
```node_modules/puppeteer-extra-plugin/dist/index.d.ts:1:10 - error TS2305: Module '"../../../src/debug"' ```

It seems like it's trying to require debug from your source folder instead of the node_modules? Try renaming your `src/debug` folder.
