### ISSUE TITLE
Captcha detected and solved, but (still) not going away with new version

### ISSUE THREAD

**Issue by jeremythille** [berstend/puppeteer-extra#368]
Hi, thanks for your reply on my first issue. Not sure why you asked to create a new one though, instead of continuing the same thread? But here goes.

I just upgraded to version `"puppeteer-extra-plugin-recaptcha": "^3.2.0"` and credited my 2captcha account again.

However, same behaviour :( The captcha turns violet, then green after a few seconds. The logs say "Solved", But no navigation occurs, and at next load I'm still stumbling upon a captcha.

As you suggested, I generated a debug output, attached.

[2020-11-04 0930 - Debug report.txt](https://github.com/berstend/puppeteer-extra/files/5486497/2020-11-04.0930.-.Debug.report.txt)

**Comment by berstend** [comment]
All that means the captcha solving works as expected.

![image](https://user-images.githubusercontent.com/1368633/98089400-f6323780-1e82-11eb-86e2-1a4a8292a8be.png)

I just checked manually and after solving the captcha you have to click the `Submit` button. Did you do that?

**Comment by berstend** [comment]
From the recaptcha plugin readme:

![image](https://user-images.githubusercontent.com/1368633/98089583-3a253c80-1e83-11eb-8b7e-f52224295ec1.png)

**Comment by jeremythille** [comment]
> After solving the captcha you have to click the Submit button. Did you do that?

Well of course I did not. The whole point of this is to automate captcha resolution. If I have to monitor the captcha and click the Submit button manually every 10 minutes, what's the point? I'm just paying 2captcha so they check the box for me and I just have to click the Submit button :)

**Comment by berstend** [comment]
I don't understand if your comment is aggressive or joking 😄 

In any regard, the official demo even clicks the submit button:
![image](https://user-images.githubusercontent.com/1368633/98091172-4f9b6600-1e85-11eb-8a7d-cb64d42dd98c.png)

`await page.solveRecaptchas()` is blocking until the captcha is solved so you don't need to "monitor" anything.

**Comment by jeremythille** [comment]
Oh no no, I'm not being agressive at all, apologies! I was just pointing out that, if I have to click the Submit button manually after the captcha is resolve, it defeats the purpose of automation.

But when you say _"I"_ have to click the button, you mean _the script_ has to? `page.click("#recaptcha-demo-submit")` ? That makes perfect sense, I believe I missed that in the documentation. I'll try it right away, many thanks :)à

**Comment by berstend** [comment]
Yes, I meant clicking on the button with your script. :-)

The site owner can configure their reCAPTCHAs to submit forms automatically after solving, the one in your case chose not to.

**Comment by jeremythille** [comment]
Oh yesssss that was it! I simply had to ask the script to click the submit button. That sounds _so_ silly now that you gave me the solution... Many thanks again, this plugin is fantastic. I owe you a beer :)

**Comment by berstend** [comment]
Haha, glad it turned out fine in the end. 😄 Sometimes it's the simple stuff that gets overlooked.
