### ISSUE TITLE
puppeteer_evaluation_script reveal headless browser quickly. please rename error to evaluation_script

### ISSUE THREAD

**Issue by IgorKurkov** [berstend/puppeteer-extra#371]
more info here: https://github.com/digitalhurricane-io/puppeteer-detection-100-percent
it's a problem because if you try to type in form if there is a condition to check the word 'puppeteer' in errors so it's very easy to detect a headless browser. 
Please rename it as soon as possible

**Comment by prescience-data** [comment]
Fixed ages ago: https://github.com/berstend/puppeteer-extra/issues/209#issuecomment-667741385

If you need to utterly remove you can patch the source as well #224 

Lastly I expect it might be a language barrier thing, but the phrasing "Please rename it as soon as possible" makes it sound like you are expecting an open source project to operate like something you are paying for. I'd suggest playing with your phrasing in the future to avoid bad reactions from the people who are essentially working for free to help you out. 

Better yet, as with all open source - if you find an issue - consider developing a fix yourself and submitting it! It's a team effort 👍🏻 

<img src="https://media.giphy.com/media/31DvxCyhx2FVK/giphy.gif" height="300"/>

**Comment by IgorKurkov** [comment]
I'm very sorry, yes, will keep in mind. 
Happy that it's fixed! :)
Thank you for your work and patience. I will delete this issue as unused
