### ISSUE TITLE
Question: When will Puppeteer Pro be available?

### ISSUE THREAD

**Issue by evading-bot-detection** [berstend/puppeteer-extra#374]
@berstend previously mentioned the future availability of an enhanced version of puppeteer stealth pro. Is there an update on when this will be available? Where will it be announced?

**Comment by prescience-data** [comment]
@evading-bot-detection 
Probably best asked in the Discord channel https://discord.gg/vz7PeKk rather than an issue / bug 💪.

**Comment by berstend** [comment]
@evading-bot-detection thanks for the interest in `stealth-pro` 😄 I unfortunately can't give an exact ETA when it'll land exactly, as my schedule is a bit unpredictable currently.

`stealth-pro` will be the first plugin to ship with playwright support so I have to finish up #303 first. I got hooked on the idea of overhauling how options are provided to the plugins (it's not very ergonomic currently) and making that type safe is a bit challenging.

In any case, just follow the repo or our discord channel - once `stealth-pro` is available I announce it there.
