### ISSUE TITLE
puppeteer-extra-plugin-recaptcha won't solve captcha

### ISSUE THREAD

**Issue by samplics** [berstend/puppeteer-extra#380]
No errors appear when running `await page.solveRecaptchas();`, but the captcha is never solved.

**Comment by berstend** [comment]
@samplics please provide more info:

- Sample code showing the issue
- Your puppeteer-extra and recaptcha-plugin versions
- The output of the debug mode (mentioned in the readme)

**Comment by berstend** [comment]
Closing until further info is provided.
