### ISSUE TITLE
Puppeteer hangs on content() call when using stealth plugin + socks proxy

### ISSUE THREAD

**Issue by juouy** [berstend/puppeteer-extra#381]
Hi,

I'm using puppeteer stealth plugin. 

`puppeteer.use(require('puppeteer-extra-plugin-stealth')());`

My pupeeter calls are using socks proxy while starting chrome browser using following argument.

`--proxy-server=socks5://IP:PORT`

After doing visit to cloudflare protected page the script using stealth plugin is hanging on page.content() call:

```
 let response = await page.goto(this.task.url, {waitUntil: 'domcontentloaded', timeout: 45000});
        this.logger.info("VISIT 2");

        let content = await page.content(); //HANGS HERE. When disabling stealth plugin, it works just fine. 
        this.logger.info("VISIT 3"); //will not be printed
```

Whenever i disable stealth-plugin, everything is working just fine and no longer hangs on content() call. 

If i start the script with visible chrome window, everything is working fine too.

Problem is when we're using headless mode, visiting cloudflare protected website (not sure if important) and using a proxy. Disabling stealth plugin resolves all issue or disabling proxy.

What might be the cause?

**Comment by berstend** [comment]
Please use [remote debugging](https://github.com/berstend/puppeteer-extra/wiki/How-to-debug-puppeteer-and-headless-browsers#use-remote-debugging) and debug output (explained in the readme) to provide more info

is the socks proxy relevant here? Does it work without the socks proxy?

**Comment by juouy** [comment]
I will add more info when i will be at the machine.
Yes, the proxy is relevant. 

Works:
- Plugin + no proxy
- No plugin + S5 proxy

Does not work:
- Plugin + S5 proxy

**Comment by juouy** [comment]
> 
> 
> Please use [remote debugging](https://github.com/berstend/puppeteer-extra/wiki/How-to-debug-puppeteer-and-headless-browsers#use-remote-debugging) and debug output (explained in the readme) to provide more info
> 
> is the socks proxy relevant here? Does it work without the socks proxy?

Would you be kind enough what you mean by "debug output"? I did the step one by opening debugging listener at port 9xxx.

modifying code to following:

```
 let content = await page.content(); //HANGS HERE. When disabling stealth plugin, it works just fine. 
        this.logger.info("VISIT 3"); //will not be printed
await page.WaitFor(400000) 
```


When i add remote target on my chrome browser i can see screencast of the page and inspect its elements.
When the plugin is enabled and the script hangs, all i can see is "about:blank" page to debug.
When the plugin is disabled, i can see the real webpage which script should visit.

**Comment by berstend** [comment]
> When the plugin is enabled and the script hangs, all i can see is "about:blank" page to debug.

That means the page is not even navigating to your target site? My intention was for you to check the console tab while remote debugging, to see if any errors are thrown.

Can you check which `puppeteer` and stealth plugin version you're using?

With debug output I meant running your script like so:
```
DEBUG=puppeteer-extra,puppeteer-extra-plugin:* node myscript.js
```

**Comment by juouy** [comment]
> hat means the page is not even navigating to your target site?

Seems like. All i can debug is about:blank page using chrome inspector. But it's stepping through "VISIT 2" debug message which is after page.goto() call.

If i disable plugin, i can see the page address and see it.

Here is debug output:

https://privnote.com/QMH5Ff1j#o6sVQYjmo

**Comment by berstend** [comment]
Unfortunately the debug output doesn't mention anything interesting :-/

Without the full code incl. socks proxy I won't be able to help here. If you're able to make a small self-containted script showing the issue and provide socks proxy credentials as well you can send me those in a PM [in our chat](https://github.com/berstend/puppeteer-extra/wiki/Scraping-Chat).
