### ISSUE TITLE
Question Imóvel Web

### ISSUE THREAD

**Issue by ronaldohoch** [berstend/puppeteer-extra#382]
Hello guys!
I'm trying to print this page: https://www.imovelweb.com.br/

My code: 

```
const puppeteer = require('puppeteer-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth')
puppeteer.use(StealthPlugin())

printFromUrl(url){
  const browser = await puppeteer.launch({ headless: true, args:[`--window-size=${1800},${1200}`, '--no-sandbox', '--disable-setuid-sandbox'] });
  const page = await browser.newPage();
  await page.goto(url,{waitUntil: 'load', timeout: 0});
  await page.waitFor(30000);
  await page.screenshot({path: `./print/${+new Date()}.png`});
  return await page.content();
}
```

My dependencies:
Node 10.
puppeteer" "^4.0.1",
puppeteer-extra: "^3.1.15",
puppeteer-extra-plugin-stealth: "^2.6.5"

What i Got:
![image](https://user-images.githubusercontent.com/2287371/100258256-9aa91600-2f25-11eb-968a-db92363a9420.png)

**Comment by berstend** [comment]
Most likely related to `iframe.contentWindow` :-)
Fix: https://github.com/berstend/puppeteer-extra/issues/137#issuecomment-685680787
