### ISSUE TITLE
Proposal:  Plugin for using tor with puppeteer extra

### ISSUE THREAD

**Issue by jstormail2** [berstend/puppeteer-extra#387]
In a previous project, I used [`tor-axios`](https://github.com/pelogvc/tor-axios), and I found the ability to rotate the proxy (change the tor ip) without much configuration was very helpful.  

Their implementation is available on [GitHub](https://github.com/pelogvc/tor-axios/blob/master/index.js).  

There are several examples of using tor with puppeteer online:
- https://medium.com/@jsilvax/running-puppeteer-with-tor-45cc449e5672
- https://levelup.gitconnected.com/anonymous-web-scrapping-with-node-js-tor-apify-and-cheerio-3b36ec6a45dc
- https://stackoverflow.com/questions/47402502/run-puppeteer-with-tor

But the `tor-axios` is the best example of `torNewSession` logic.

I will implement it in my own project and review the results.

**Comment by berstend** [comment]
@jstormail2 Is there a benefit of a plugin here? :-) Tor requires a locally installed client and the rest is just adding a proxy server to puppeteer right? Is there anything else a plugin could do to make this a better experience from your perspective?

**Comment by jstormail2** [comment]
Probably not worth it to make an official plugin.  Fun idea, closing.

**Comment by mdalma** [comment]
Hi @jstormail2, i am working on a project and I think is similar to yours. Could you think about making a repository with your's?
Thx!
