### ISSUE TITLE
can't use page.solveRecaptchas() or any other puppeteer-extra functions with TypeScript. Should we document this?

### ISSUE THREAD

**Issue by clouedoc** [berstend/puppeteer-extra#393]
Hi,

If you can't use any `puppeteer-extra`-specific function (e.g. `page.solveRecaptchas`), please add the following to your `tsconfig.json`:

```json
    "include": [
        "./node_modules/puppeteer-extra/*.d.ts",
        "./node_modules/puppeteer-extra-*/*.d.ts",
        "./src"
    ]
```

Your code needs to be located inside `./src`. Adding the `include` property in your `tsconfig.json` will ignore the existing `exclude` property.

It will include "ambient" typescript files so that the TypeScript compiler (and langage server) can resolve `puppeteer-extra` types.

I am not sure why I had to do this.
Here is my whole `tsconfig.json` for reference purposes:
```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "ES2020",
        "strictFunctionTypes": true,
        "moduleResolution": "node"
    },
    "include": [
        "./node_modules/puppeteer-extra/*.d.ts",
        "./node_modules/puppeteer-extra-*/*.d.ts",
        "./src"
    ]
}
```

I can create a wiki page if you think that it is appropriate, let me know and I'll resort to my best english skill to create it 😃.

**Comment by berstend** [comment]
@clouedoc Would be nice if you can add a new section to the existing wiki entry regarding fixing issues with the ambient declarations :-)
https://github.com/berstend/puppeteer-extra/wiki/TypeScript-usage

**Comment by clouedoc** [comment]
Hi,

The problem came back with the project going multiplayer-mode. 
Nowadays, I resort to massive use of `// @ts-ignore`, mostly because I'm too lazy to find the root cause.

Should I still create a wiki entry for reference purposes ?

**Comment by berstend** [comment]
> I resort to massive use of `// @ts-ignore`

Hmm, this does sound like there's an underlying issue with your TS config.

If you got the time it'd be nice to document your previous fix in the wiki, just in case anyone else runs into this. :-)

**Comment by prescience-data** [comment]
@berstend Added some info on adding to ambient types: 

https://github.com/berstend/puppeteer-extra/wiki/TypeScript-usage

@clouedoc

> Nowadays, I resort to massive use of `// @ts-ignore`, mostly because I'm too lazy to find the root cause. 

Je t'en prie, non!! 🙈

**Comment by berstend** [comment]
@prescience-data thanks!

> Je t'en prie, non!! 🙈

J'ai bien peur 🙈
