### ISSUE TITLE
[Feature] Wepage with all tests

### ISSUE THREAD

**Issue by Bllacky** [berstend/puppeteer-extra#394]
Hi guys,

I know you made a bunch of tests to test the evasion scripts, but is there a webpage/website where you can test how our evasions behave. I know there are a number of websites that test if the browser is headless, but I mean a website which does all the tests in this repo.

Just asking, I haven't found anything in the documentation.

Thank you

**Comment by prescience-data** [comment]
https://github.com/prescience-data/foundation/tree/master/core/tests

**Comment by Bllacky** [comment]
This won't help me. I am not using NodeJS, but ported all evasions to a Selenium project. Most of them work, it's very hard to test them individually.

**Comment by prescience-data** [comment]
Everything about this pains me 🤣

> not using NodeJS

> to a Selenium project

![](https://media1.tenor.com/images/722d98c96ebd6e4a0612f5a386605ac7/tenor.gif?itemid=5614504)

**Comment by Bllacky** [comment]
I would imagine. But my project is in Python. To be honest, it was fairly easy to port the evasions to my project and they seem to work well, I just have trouble testing them all individually.

**Comment by prescience-data** [comment]
I assume, though, if you managed to port the evasions over, you could port the flow of those tests?

**Comment by Bllacky** [comment]
Of course, I could, but I thought someone made a test page before me. I was thinking of something like this: https://bot.sannysoft.com/
If I ever manage to do it, I will share the code with you guys on Discord and you can host it wherever you want.

**Comment by berstend** [comment]
A publicly hosted page that combines all the different detection tests would be sweet, ping us on discord if you ever get around to making one. :-)
