### ISSUE TITLE
[Bug] Stealth Plugin Maximizing Ads

### ISSUE THREAD

**Issue by NicTron1** [berstend/puppeteer-extra#395]
The other day I decided to migrate over to the stealth plugin because my script was being detected. However, every time my script would go to various electronics websites, it would maximize advertisements. I thought it was my code at first, but after creating a new script that just goes to the URL, the same behavior is observed. I could just be missing something as I am new to stealth, and puppeteer plugins in general. Using the AdBlock plugin fixes this, but then clashes with block-resources plugin.

**Comment by Niek** [comment]
Can you try to disable the iFrame content window evasion?

```js
const pluginStealth = require('puppeteer-extra-plugin-stealth')()
pluginStealth.enabledEvasions.delete('iframe.contentWindow')
puppeteer.use(pluginStealth)
```

This evasion is known to cause issues with ad systems. See also: https://github.com/berstend/puppeteer-extra/issues/137

**Comment by NicTron1** [comment]
That fixed it, thank you
