### ISSUE TITLE
[Bug] Widevine reported as not installed

### ISSUE THREAD

**Issue by TensorTom** [berstend/puppeteer-extra#396]
Widevine reported as not installed in browser even though it is. Site is not allowing playback because of it.

**Comment by Niek** [comment]
Are you using the bundled Chromium that comes with puppeteer? Because that doesn't support widevine. If you want widevine support, set the `executablePath` to a full Chrome binary.

**Comment by TensorTom** [comment]
> Are you using the bundled Chromium that comes with puppeteer? Because that doesn't support widevine. If you want widevine support, set the `executablePath` to a full Chrome binary.

Will run a test today because it's actually pyppeteer and I the spotify player does load.

**Comment by berstend** [comment]
As Niek mentioned the solution is to use Chrome, which ships with proprietary codecs and DRMs like widevine.

If using Chrome for whatever reason is not an option here's an alternative: https://github.com/proprietary/chromium-widevine

**Comment by fokkerone** [comment]
Using Chrome/Canary with headless: false on MacOS Ventura also not enables Widevine as reported here https://niespodd.github.io/browser-fingerprinting/, when visitig the site on puppeteer controlled Window. 
same browser , different fingerprint 
Left started from dock, right side via Puppeteer. As you can see Puppeteer Chrome is without Widewine

<img width="1426" alt="Bildschirm­foto 2023-02-26 um 11 13 34" src="https://user-images.githubusercontent.com/96452/221404498-4eb84fda-fddc-46b8-8875-a90e6f993993.png">

Any ideas how to start it with widewine enabled?
