### ISSUE TITLE
[Bug] puppeteer-extra-plugin-stealth will make html page show error content

### ISSUE THREAD

**Issue by kingname** [berstend/puppeteer-extra#398]
**Describe the bug**

for example, for this url: https://www.folhadelondrina.com.br/geral/pesca-de-especies-nativas-no-parana-esta-proibida-ate-fevereiro-3023759e.html

when I visit it by normal chrome, it is like the below image:

![image](https://user-images.githubusercontent.com/5440523/102467442-41975280-408b-11eb-9d33-09799523b865.png)

However, when I use puppeteer-extra-plugin-stealth, the page become the one below:

![image](https://user-images.githubusercontent.com/5440523/102467688-8d49fc00-408b-11eb-85b0-b6e8a7617617.png)

Only a ad pic show. 

**Code Snippet**

```javascript
const puppeteer = require('puppeteer-extra')
const StealthPlugin = require('puppeteer-extra-plugin-stealth')
puppeteer.use(StealthPlugin())

async function main() {
    const browser = await puppeteer.launch({headless: false,
        executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'})
    let page = await browser.newPage()
    await page.setViewport({width: 1200, height: 800})
    await page.goto('https://www.folhadelondrina.com.br/geral/pesca-de-especies-nativas-no-parana-esta-proibida-ate-fevereiro-3023759e.html')
}

main()
```

**Versions**

```
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 1.08 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.4.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.15 - /usr/local/bin/npm
  npmPackages:
    puppeteer-autoscroll-down: ^0.1.6 => 0.1.6 
    puppeteer-core: ^5.5.0 => 5.5.0 
    puppeteer-extra: ^3.1.15 => 3.1.15 
    puppeteer-extra-plugin-stealth: ^2.6.5 => 2.6.5 
```

**Comment by apulidoc** [comment]
Im having problems also since 2 days ago... I was using stealth to inject mutation observers in bet365 to get certain alarms but is not working anymore with the same code... =(

**Comment by berstend** [comment]
This is related to the `iframe.contentWindow` evasion, see here for a fix: https://github.com/berstend/puppeteer-extra/issues/399#issuecomment-759387597
