### ISSUE TITLE
[Feature] I created a new Puppeteer / Playwright Bot Detection Test Page with Fresh Tests

### ISSUE THREAD

**Issue by NikolaiT** [berstend/puppeteer-extra#402]
**Feature request**

Hey boys, I am trying to give back a bit to the community.

[https://bot.sannysoft.com/](https://bot.sannysoft.com/) is a bit old, isn't it?

I am working a lot on creating new puppeteer & playwright detection tests.

I found a couple of new ways to detect puppeteer.

Check your bot here: https://bot.incolumitas.com/

I am not recording any analytics data on this site, unlike our dear Antoine. Might do so in the future though ;)

Best,
Nikolai

**Comment by berstend** [comment]
Closing as per discord discussion. :-)

**Comment by ShivanshSharma1** [comment]
how can i know that the value the tests are giving are right and my bot is not getting detected

**Comment by landaida** [comment]
> Closing as per discord discussion. :-)

What discord channel? I would like to help
