### ISSUE TITLE
Manipulate timezone

### ISSUE THREAD

**Issue by Bllacky** [berstend/puppeteer-extra#411]
I've used this website to test our evasions:
https://pixelscan.net/

Turns out that if you use a proxy, the Javascript timezone will be different from the IP's timezone. I was wondering if you can add a new evasion for manipulating the timezone?

Thanks

**Comment by berstend** [comment]
This is natively supported in puppeteer :-)

https://pptr.dev/#?product=Puppeteer&version=v5.5.0&show=api-pageemulatetimezonetimezoneid
