### ISSUE TITLE
[Feature] Better recaptcha callback

### ISSUE THREAD

**Issue by Revadike** [berstend/puppeteer-extra#412]
**Feature request**
Your recaptcha package seemed like a blessing to me, but unfortunately it turned out to be useless for my application. The site I was using it on, was using some very custom forms. Basically there were no standard html5 forms, so I had to rely purely on its callback function. A function that was anonymous and minified. After a lot of digging, I found that you can get the callback function from this:
`___grecaptcha_cfg.clients[0].o.o.callback(RECAPTCHA_RESPONSE)`

It would be nice if you can find a way to natively implement this into your plugin. I'm sure it would benefit a lot of people!

**Comment by berstend** [comment]
@Revadike the recaptcha plugin will extract and trigger this callback already?

Can you send the site in question so I can see if they implemented things in a weird way?

DM me on our discord channel if you want to keep the site private. :-)

**Comment by Revadike** [comment]
Do you require additional information?

**Comment by Revadike** [comment]
So, it differs quite a bit per captcha. I think you can use this to find callback function globally:
```js
let callbacks = Object.values(___grecaptcha_cfg.clients).map(client => {
  let { callback } = Object.values(Object.values(client).find(k => k.constructor.name === "RT"))[0];
  if (typeof callback === "string") {
    callback = window[callback];
  }
  return callback;
});
```
It requires some further testing though.

**Comment by berstend** [comment]
@Revadike thanks for the followup and additional info. 👍 

Overall the plugin does support callbacks, so it must be a new/weird/different implementation by the site owner.

Unfortunately I lack the time to properly debug this now, also the timing is bad as I want to get the [playwright rewrite](https://github.com/berstend/puppeteer-extra/pull/303) out the door first (as this will result in the current recaptcha plugin be obsolete and replaced with a new one).

It seems like you found a workaround for your current use-cases (by triggering the callback yourself). I made a not to look into this once I do more work on the new recaptcha plugin again.

**Comment by berstend** [comment]
For reference, heres' the current callback code:
https://github.com/berstend/puppeteer-extra/blob/master/packages/puppeteer-extra-plugin-recaptcha/src/content.ts#L261-L266

If anyone wants to expedite the process of improved callback support just do some debugging around that code and let me know your findings.
