### ISSUE TITLE
[Feature] Implement CapMonster as a Provider for puppeteer-extra-plugin-recaptcha

### ISSUE THREAD

**Issue by mss-repo** [berstend/puppeteer-extra#414]
CapMonster is a much faster and cheaper captcha solver than 2captcha.com. Their suggested solution to switch from 2captcha to CapMonster is to simply replace the host entries in your host files to redirect requests from http://2captcha.com to http://api.capmonster.cloud. I tried this however It doesn't seem to work with puppeteer-extra-plugin-recaptcha:

/etc/hosts:

```
# capmonster.cloud begin
159.69.49.144 2captcha.com
# capmonster.cloud end
```

I get this error:

```
[2021-01-31T19:54:39.809Z] PuppeteerExtraPluginRecaptcha: An error occured during "getRecaptchaSolutions": {
  _vendor: 'recaptcha',
  provider: '2captcha',
  id: 'bs9jllqyg0m',
  requestAt: 2021-01-31T19:54:38.338Z,
  error: 'Error: 2captcha error: ERROR_KEY_DOES_NOT_EXIST'
}
```

The redirection seems to be working correctly as you get this error when you go to http://api.capmonster.cloud/in.php which is their implementation of http://2captcha.com/in.php.

It seems like something is slightly off or needs to be changed to switch to CapMonster using this method but I can't seem to find it or put my finger on what that is.

If anyone can provide any feedback or help make this change, That'd be truly appreciated and useful for others as well! Thank you for your time!

**Comment by berstend** [comment]
Hey there, I kinda doubt this approach will work as this would result in SSL certificate issues? Overall I don't want to make changes to the recaptcha plugin right now, as a new playwright supporting version will be out soon. I'll revisit this issue at a later time.

**Comment by bsantos09** [comment]
Hi
Im also trying to use CapMonster has anyone been able to implement it?
Thank you

**Comment by KazzyAPI** [comment]
Did anyone find a fix / was this included?

**Comment by ItsCEED** [comment]
Any update soon on this? I have also tried switching the API Endpoints but it doesn't work.
