### ISSUE TITLE
Instagram detects puppeteer

### ISSUE THREAD

**Issue by EgorSigolaev** [berstend/puppeteer-extra#415]
want to make instagram account registration, but after clicking REGISTRATION button, instagram detects puppeteer as bot. 

I have tried to use proxy, changed user-agent, but nothing changed. 

Here is the code: [CODE](https://pastebin.com/7YH06xu8)
Here is network request ans response: 
[request](https://prnt.sc/xyyomn)
[response](https://prnt.sc/xyysrz)

First time all was ok, but after few attempts, instagram blocked me.

System:
    OS: Windows 10 10.0.19041
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 10.15 GB / 15.95 GB
  Binaries:
    Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    puppeteer: ^5.5.0 => 5.5.0
    puppeteer-core: ^5.5.0 => 5.5.0
    puppeteer-extra: ^3.1.16 => 3.1.16
    puppeteer-extra-plugin-stealth: ^2.6.7 => 2.6.7
    puppeteer-page-proxy: ^1.2.8 => 1.2.8
    puppeteer-proxy: ^2.1.1 => 2.1.1

If i need more details, i will sent.

**Comment by berstend** [comment]
Hey there, it's tough to say what the issue might be without debugging this (which is not part of what we do as open-source maintainers). I recommend asking around in our discord if someone else has issues with that site as well.
