### ISSUE TITLE
Headless being detected by Amazon

### ISSUE THREAD

**Issue by radixdev** [berstend/puppeteer-extra#42]
```
const puppeteer = require("puppeteer-extra")
// Enable stealth plugin with all evasions
puppeteer.use(require("puppeteer-extra-plugin-stealth")())

  try {
    (async () => {
      const browser = await puppeteer.launch({
        headless: true,
        slowMo: 25,
        args: ['--no-sandbox', '--disable-setuid-sandbox']
      })
      const page = await browser.newPage()

      await page.setViewport({ width: 1280, height: 800 })

      // goto the provided list
      await page.goto('https://www.amazon.com/hz/wishlist/dl/invite/3gq5Qfx?ref_=wl_share')

      // login
      await page.type('#ap_email', "amazon email here")
      await page.type('#ap_password', "amazon password here")
      await page.click('#signInSubmit')

      await browser.close()
    })()
  } catch (err) {
    console.error(err)
    return Promise.reject(new Error("Mission failed, we'll get em next time"));
  }
```

The interesting bit is that `headless: false` is not being detected. Is there a way to figure out how only the headless mode is being detected?

**Comment by Eastkap** [comment]
Besides your the fact you're missing a " here ` await page.type('#ap_password', "amazon password here")`, I cannot replicate the issue. Keep me posted, I'm sure we'll find a fix!

**Comment by radixdev** [comment]
I don't follow, what is missing?

**Comment by Eastkap** [comment]
the quote in the end of `"amazon password here`. I don't believe that is your issue, but I can't replicate the real one neither

**Comment by radixdev** [comment]
Oh yes, I swapped out my real password and I guess trimmed that last quote. I added more countermeasures in the interim. I think they have account level behavioral checks as well.
