### ISSUE TITLE
[Bug] Using the first tab/page at launch fail to bypass the stealth detection

### ISSUE THREAD

**Issue by oom-** [berstend/puppeteer-extra#420]
**Describe the bug**

If I use the tab opened at the browser launch the security bypass are not applied: 
![image](https://user-images.githubusercontent.com/11071671/106888439-d9f2a080-66e6-11eb-82e6-c5507434c11e.png)

If it's a normal behavior could an explicitly warning be added to the README.md ?

**Code Snippet**

```javascript
puppeteer.launch({ headless: true }).then(async browser => {
  console.log('Running tests..')
  const page = (await browser.pages())[0];
  await page.goto('https://arh.antoinevastel.com/bots/areyouheadless')
  await page.waitFor(5000)
  await page.screenshot({ path: 'testresult.png', fullPage: true })
  await browser.close()
  console.log(`All done, check the screenshot. ✨`)
})
```

**Versions**
* node: v12.16.1
* puppeteer: ^5.5.0
* puppeteer-extra: ^3.1.16
* puppeteer-extra-plugin-stealth: ^2.6.7

**Comment by berstend** [comment]
Duplicate of https://github.com/berstend/puppeteer-extra/issues/88

Above includes a workaround, though it's recommended to just open a new tab.

I agree this should be mentioned in the readme.
