### ISSUE TITLE
[Bug] Typescript compilation errors on Ubuntu only, can't find exported namespaces and modules

### ISSUE THREAD

**Issue by sctgraham** [berstend/puppeteer-extra#422]
**Describe the bug**

I've got a project up and running without any issues on my local dev mac. 
However, when pushing my code to a Ubuntu server and trying to compile the typescript there (via the CLI), I'm getting get 19 compilation errors due to:
- Namespace "node_modules/puppeteer/cjs-entry" having no exported members "Browser", "Target", etc. (this error is in "node_modules/puppeteer-extra-plugin/dist/index.d.ts")
- Module "../../puppeteer/cjs-entry" having no exported members "Page", "ConnectOptions", etc. (this error is in "node_modules/puppeteer-extra/dist/puppeteer.d.ts")

My NodeJS, Typescript CLI and npm package versions are identical between both environments. 

**Code Snippet**

I'm running the basic typescript setup as advertised in the docs (albeit without the AdblockerPlugin).

**Versions**

  Binaries:
    Node: 15.0.1 - ~/.nvm/versions/node/v15.0.1/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 7.0.3 - ~/.nvm/versions/node/v15.0.1/bin/npm
  npmPackages:
    puppeteer: ^7.0.1 => 7.0.1
    puppeteer-extra: ^3.1.16 => 3.1.16
    puppeteer-extra-plugin-stealth: ^2.7.4 => 2.7.4

**Comment by berstend** [comment]
Can't test right now but this might be related to puppeteer starting to ship with types since v7 (although it seems to be broken):
https://github.com/puppeteer/puppeteer/releases/tag/v7.0.1

```
* typescript: ship .d.ts file in npm package (#6811) (a7e3c2e). We didn't expose the right d.ts file which caused TypeScript to not pick up our type definitions. This should fix it for ES imports - we are still working on providing typedefs to CommonJS consumers.
```

Could you try with puppeteer@5 and see if that makes a difference? 🤔

**Comment by berstend** [comment]
> My NodeJS, Typescript CLI and npm package versions are identical between both environments.

Not entirely sure why this would behavior differently between platforms though, if it's 100% guaranteed the versions are the same

**Comment by sctgraham** [comment]
Ah yes ! Reverting to puppeterr@5 worked. And yes, I can confirm that the versions were the same between both environments, which is indeed very puzzling. So hopefully these faulty typings will be fixed in an upcoming release of puppeteer then ? Thanks in any case for your quick answer.

**Comment by berstend** [comment]
> So hopefully these faulty typings will be fixed in an upcoming release of puppeteer then?

Yeah, it seems like an issue on their end they would need to fix. If they don't do that in time I'll see if we can fix that problem differently :-)
