### ISSUE TITLE
[Feature] Supply proxy to 2captcha [recaptcha plugin]

### ISSUE THREAD

**Issue by roachadam** [berstend/puppeteer-extra#423]
**Feature request**

Is there no current way to send the proxy for the recaptcha plugin? I'm looking through the code and there appears to be 'extraData' but I don't see any public methods to access it.

So, is there a way to send proxy info to 2captcha?

If there is I apologize for the issue.
Thanks

**Comment by roachadam** [comment]
Hopefully there isn't a way to do this because I spent a few hours getting a custom solution to work. For anyone looking for this as well, here's how I did it:


```ts
function handleCaptcha(){
	await this.page.waitForSelector('textarea[name="h-captcha-response"]', {timeout: 10000});
	let {captchas} = await this.page.findRecaptchas();
	if(!captchas){
		this.log('JS challenge detected, solving...');
		return;
	}
		
	this.log('hCaptcha detected, solving...');
	var requestAt = new Date();
	//* my custom 2captcha handle method
	//* returns {id, data} from 2captcha api
	var capSol = await this.solveHCaptcha(captchas[0].sitekey);//todo: check null or timeout
	var responseAt = new Date();
	var duration = (responseAt.getTime() - requestAt.getTime()) / 1000;
	var solutions: CaptchaSolution[] = [
              {
	              _vendor: 'hcaptcha',
	              provider: '2captcha',
	              id: captchas[0].id,
	              requestAt: requestAt,
	              providerCaptchaId: capSol.id,
	              text: capSol.data,
	              responseAt: responseAt,
	              hasSolution: true,
	              duration: duration,
              }
	];
	let { solved, error } = await this.page.enterRecaptchaSolutions(solutions);
	return !error && solved && solved[0].isSolved;
}
```

**Comment by berstend** [comment]
@roachadam adding proxy support to the recaptcha plugin is high on the todo list, unfortunately right now is not a good time to do it: I'm in the process of finishing up our [playwright rewrite](https://github.com/berstend/puppeteer-extra/pull/303) which also means switching to new plugins as well, so there's little benefit of adding proxy support now in the current recaptcha plugin. :-/

I made a note to add proxy support to the recaptcha plugin once the above mentioned PR is released.
