### ISSUE TITLE
[Bug] iframe.contentWindow issue

### ISSUE THREAD

**Issue by vladtreny** [berstend/puppeteer-extra#430]
Hello,
Here's why we have to disable `iframe.contentWindow`
`stealth.enabledEvasions.delete('iframe.contentWindow');`

```
var iframe = document.createElement('iframe');
iframe.style.height = '0px';
iframe.style.height = '0px';
iframe.srcdoc = "page intentionally left blank";
document.body.appendChild(iframe);

console.log(iframe.contentWindow[0]);
```

Real Browser: `Undefined`
Stealth: `Window {window: Window, self: Window, document: document, name: "", location: Location, …`

**Comment by regseb** [comment]
@berstend @vladtreny The pull request https://github.com/berstend/puppeteer-extra/pull/545 has fixed this issue.

**Comment by berstend** [comment]
Closing as #545 has landed
