### ISSUE TITLE
[Bug] isNotSecure value (iframe disables runtime)

### ISSUE THREAD

**Issue by vladtreny** [berstend/puppeteer-extra#431]
Hello,

Sometimes iframe could disable runtime. 

```
<!DOCTYPE html>
<html lang="en">
<head>
    <title>File Upload</title>
</head>
<body>
<iframe src="about:blank" title="12">
</iframe>
</body>
</html>

```

https://github.com/berstend/puppeteer-extra/blob/704502b1005fbe1ac1e2149ffd3715cc7629b50c/packages/puppeteer-extra-plugin-stealth/evasions/chrome.runtime/index.js#L42
On this line we can receive `window.location` like `about:blank` from iframe.

Seems like it should be `let isNotSecure = window.location.protocol === 'http'` or `let isNotSecure = !(window.location.protocol.startsWith('https') || window.location.protocol.startsWith('about'))`

**Comment by berstend** [comment]
Uhm, `about:blank` is not considered a secure origin so the current check is correct?

![image](https://user-images.githubusercontent.com/1368633/111087504-46e92980-8522-11eb-8c02-71507f2639da.png)

![image](https://user-images.githubusercontent.com/1368633/111087510-4ea8ce00-8522-11eb-951f-aa0f212e215c.png)

**Comment by berstend** [comment]
![image](https://user-images.githubusercontent.com/1368633/111087706-603ea580-8523-11eb-9629-38c776d8967a.png)
