### ISSUE TITLE
[Bug]  Module '"../../puppeteer/lib/types"' has no exported member 'FetcherOptions'.

### ISSUE THREAD

**Issue by NintendoEngineer** [berstend/puppeteer-extra#433]
**Describe the bug**

Install puppeteer (7.1.0) and puppeteer-extra (3.1.17) in a TypeScript project. Run npm start.

**Expected behavior**
Project builds fine.

**Actual behavior**
During build error gets thrown: Module '"../../puppeteer/lib/types"' has no exported member 'FetcherOptions'.

When inspecting **node_modules/puppeteer-extra/dist/puppeteer.d.ts**, you can see that the FetcherOptions that are being exported are no longer valid to be imported from puppeteer.

**Versions**

System:                                                                                                        OS: Windows 10 10.0.18363                                                                                    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz                                                       Memory: 2.33 GB / 7.80 GB                                                                                  Binaries:                                                                                                      Node: 14.15.4 - C:\Program Files\nodejs\node.EXE                                                             npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD                                                              npmPackages:                                                                                                   puppeteer: ^7.1.0 => 7.1.0                                                                                   puppeteer-autoscroll-down: ^0.1.6 => 0.1.6                                                                   puppeteer-core: ^7.1.0 => 7.1.0                                                                              puppeteer-extra: ^3.1.17 => 3.1.17                                                                           puppeteer-extra-plugin-stealth: ^2.6.2 => 2.6.2

**Comment by berstend** [comment]
Mentioned in the readme:

![image](https://user-images.githubusercontent.com/1368633/108391353-ea8c3600-7211-11eb-8dbb-2a52c2c02b2b.png)

https://github.com/berstend/puppeteer-extra/issues/428#issuecomment-778679665
