### ISSUE TITLE
Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (848005).

### ISSUE THREAD

**Issue by Tahadaboussi** [berstend/puppeteer-extra#435]
**Describe the bug**

**Code Snippet**

```javascript
const puppeteer = require('puppeteer-extra')

;(async () => {
  const browser = await puppeteer.launch()
  // ...
})()
```

**Versions**

**Comment by Tahadaboussi** [comment]
it was working fine, i downloaded the latest version and it suddenly stopped

**Comment by berstend** [comment]
Really? :-/ Why didn't you select "Bug report" when opening this issue, as you would've seen this:

> Run the following command in your project directory, and paste its results here:

```npx envinfo@latest --system --binaries --npmPackages '*(puppeteer*|playwright*|automation-extra*|@extra*)'```

Without this info this issue is useless.

**Comment by berstend** [comment]
Actually even worse: You've used the template but didn't bother posting your versions here.

**Comment by sintanial** [comment]
System:
    OS: macOS 11.2.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 2.10 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.14.0 - /usr/local/bin/node
    npm: 7.7.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    puppeteer: ^8.0.0 => 8.0.0 
    puppeteer-core: ^8.0.0 => 8.0.0 
    puppeteer-extra: ^3.1.18 => 3.1.18 
    puppeteer-extra-plugin-stealth: ^2.7.6 => 2.7.6
