### ISSUE TITLE
[Feature] Puppeteer Stealth does not pass geocaptcha

### ISSUE THREAD

**Issue by Edweis** [berstend/puppeteer-extra#437]
**Feature request**
`puppeteer-extra-plugin-stealth` works well and I have used it for many website, however I got caught scraping [this website](https://www.dicksmith.com.au/da/). Returning an iframe from  `https://geo.captcha-delivery.com` with:
![Gotcha](https://user-images.githubusercontent.com/18052624/108713638-162d5a00-754b-11eb-956c-6f9b12527663.png)

Any idea on how I can bypass such protection? If so I can contribute with a PR.

Thanks !

**Comment by sanchobouillant** [comment]
You can use puppeteer-extra-plugin-recaptcha.

**Comment by berstend** [comment]
This is being shown when opening a bug report:
> NOTE: "SiteA.com stopped working" is not a valid stealth-plugin bug report, unless used as an example to show a technical issue while providing specific example code of the problem.
For general purpose usage discussions please use the community discord: http://scraping-chat.cf
