### ISSUE TITLE
How to set download dir using puppeteer-extra-plugin-user-preferences

### ISSUE THREAD

**Issue by kailashkrish** [berstend/puppeteer-extra#44]
`puppeteer.use(require('puppeteer-extra-plugin-user-data-dir')())
  puppeteer.use(require('puppeteer-extra-plugin-user-preferences')({prefs: {
  download: {
      prompt_for_download: false,
      default_directory: OUTDIR,
  }
}
}))`. This wasn't successful. Any idea to set download behaviour at browser level. Btw great wrapper for puppeteer.

**Comment by leblancmeneses** [comment]
This worked for me.

```
import * as UserPreferencesPlugin from 'puppeteer-extra-plugin-user-preferences';
puppeteer.use(UserPreferencesPlugin({
  userPrefs: {
    download: {
      prompt_for_download: false,
      default_directory: '/tmp',
    },
    webkit: {
      webprefs: {
        default_font_size: 22
      }
    }
  }
}));
```

**Comment by berstend** [comment]
Assuming that what @leblancmeneses provided (thanks!) I'm gonna close this issue now. :)

**Comment by tlecoz** [comment]
Unfortunately, it doesn't work for me and I'm becoming crazy...

**Comment by berstend** [comment]
> Unfortunately, it doesn't work for me and I'm becoming crazy...

try to make a small demo script and share it here

**Comment by uzair004** [comment]
this worked for me, using `puppeteer` extra with a `puppeteer-extra-plugin-user-preferences` plugin
```
const UserPreferencesPlugin = require("puppeteer-extra-plugin-user-preferences");

const downloadImageDirectoryPath = process.cwd()

puppeteer.use(
  UserPreferencesPlugin({
    userPrefs: {
      download: {
        prompt_for_download: false,
        open_pdf_in_system_reader: true,
        default_directory: downloadImageDirectoryPath,
      },
      plugins: {
        always_open_pdf_externally: true,
      },
    },
  })
);
```
