### ISSUE TITLE
[Bug] 2captcha API calls not using HTTPS

### ISSUE THREAD

**Issue by wywywywy** [berstend/puppeteer-extra#442]
For security & privacy reasons, API calls to 2captcha should use SSL.  At the moment any MITM can get your API key.

https://github.com/berstend/puppeteer-extra/blob/704502b1005fbe1ac1e2149ffd3715cc7629b50c/packages/puppeteer-extra-plugin-recaptcha/src/provider/2captcha-api.ts#L10-L11

**Comment by wywywywy** [comment]
Automation-extra also has the same problem

**Comment by berstend** [comment]
Oh good point - most of that specific code was quick copy/pasta as mentioned in the top comment of that file.

I'll collect some more issues and will fix that in one of the next updates, thanks for reporting.

**Comment by berstend** [comment]
Fixed in `puppeteer-extra-plugin-recaptcha@3.3.5`
