### ISSUE TITLE
[Bug] Args --user-data-directory not loaded when using puppeteer-extra stealth

### ISSUE THREAD

**Issue by rolim91** [berstend/puppeteer-extra#443]
**Describe the bug**

I was trying to see if I could get Puppeteer to open chrome profiles using multiple methods.
The one I have closely accomplished was to use the `--user-data-directory` argument.

https://stackoverflow.com/questions/57623828/in-puppeteer-how-to-switch-to-chrome-window-from-default-profile-to-desired-prof/57662769#57662769

I tried it with Stealth on at first and it didn't work. I then removed the stealth option and noticed it worked. Is there are reason for this?

**Versions**

  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 18.22 GB / 31.94 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE     
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD       
  npmPackages:
    puppeteer: ^5.5.0 => 5.5.0 
    puppeteer-extra: ^3.1.17 => 3.1.17 
    puppeteer-extra-plugin-stealth: ^2.7.5 => 2.7.5

**Comment by Niek** [comment]
You need to use the `userDataDir` launch option instead: https://pptr.dev/#?product=Puppeteer&version=v5.5.0&show=api-puppeteerlaunchoptions

**Comment by rolim91** [comment]
Thank you this actually worked!

**Comment by kotsh23** [comment]
> You need to use the `userDataDir` launch option instead: https://pptr.dev/#?product=Puppeteer&version=v5.5.0&show=api-puppeteerlaunchoptions

its still working ?

**Comment by shixish** [comment]
This still seems to be the case.

It doesn't work with either `--user-data-dir` arg flag or `userDataDir` launch option. Disabling the stealth plugin gets it working again.

**Comment by igorovisk** [comment]
Having the same ploblem
