### ISSUE TITLE
[Bug] Incapsula + ReCapcha stopped working in march 2021

### ISSUE THREAD

**Issue by ikamil** [berstend/puppeteer-extra#444]
**Describe the bug**

Website https://ozon.ru
Any page for item, like https://www.ozon.ru/context/detail/id/201062520/

Uses InCapsula + ReCapcha technologies for detecting headless puppeteer.

Plugin worked nice till March 2021.

Starting from march, content of website is similar as without using plugin - "Please Pass Re-Capcha".

Assuming changes for anti-recapcha, but not quite sure.

**Comment by prescience-data** [comment]
When logging the issue this message would have come up:
 
>NOTE: "SiteA.com stopped working" is not a valid stealth-plugin bug report, unless used as an example to show a technical issue while providing specific example code of the problem.
For general purpose usage discussions please use the community discord: http://scraping-chat.cf/

**Comment by berstend** [comment]
@ikamil are you saying that
 a) stealth is being detected, or
 b) the recaptcha plugin isn't detecting captchas on that site?

If it's a) then what @prescience-data applies, if it's b) then it's a bug we're interested in fixing.

**Comment by berstend** [comment]
Reading the PR again it seems like it's a stealth related issue: Please provide more technical info.

We as maintainers can't debug every site for stealth related problems, that'd be a full-time job.
