### ISSUE TITLE
[Bug] Electron codesigning trips over "chrome.app" folder

### ISSUE THREAD

**Issue by water-a** [berstend/puppeteer-extra#445]
**Describe the bug**
When codesigning my Electron application, it gets blocked because of the directory called "chrome.app"

This is resolved when you rename that directory to something else e.g. "chromeapp".

**Comment by berstend** [comment]
Wow, this must be one of the weirdest bugs to date. :-)

**Comment by water-a** [comment]
[redacted].app/Contents/Resources/app/node_modules/puppeteer-extra-plugin-stealth/evasions/chrome.app: bundle format unrecognized, invalid, or unsuitable

**Comment by berstend** [comment]
@water-a is one of those issues/fixes related?
https://stackoverflow.com/questions/25835443/xcode-swift-domain-nsposixerrordomain-code-22/26617294#26617294
https://stackoverflow.com/a/38751921

**Comment by water-a** [comment]
I don’t think so, because I think it’s confusing the folder as an application instead of just a folder so it can’t verify it’s not malware.

**Comment by berstend** [comment]
This seems to be the canonical upstream issue: https://github.com/electron-userland/electron-builder/issues/3790

A fix allowing to exclude stuff has been merged it seems:
https://github.com/electron-userland/electron-builder/issues/5500

Please report back if that fixes this problem, thanks

**Comment by water-a** [comment]
I don't think it's specific to `electron-builder` necessarily either. I think it uses Apple's codesigning tool to do it.

**Comment by berstend** [comment]
@water-a did it work? :-)

**Comment by water-a** [comment]
Yup, that worked! Thank you so much! I probably could have googled that myself haha.

**Comment by berstend** [comment]
Great, now we have it here for reference in case someone else experiences this issue. :-)

**Comment by kbourro** [comment]
> I don't think it's specific to `electron-builder` necessarily either. I think it uses Apple's codesigning tool to do it.
> 
> But will do, thanks!

Did you use the following ?
`"signIgnore": ".*chrome\\.app$"`

**Comment by water-a** [comment]
@kbourro 
I specifically just used this:
```
      "signIgnore": [
        "node_modules/puppeteer-extra-plugin-stealth/evasions/chrome.app"
      ],
```

**Comment by kbourro** [comment]
@water-a thanks for this solution.
Now i have a different issue with mac notarization failed. I see the following error.
Did you encounter the same issue ?
`{
      "severity": "error",
      "code": null,
      "path": "SEO+Autopilot.zip/SEO Autopilot.app/Contents/Resources/app/dist/node_modules/puppeteer/.local-chromium/mac-1036745/chrome-mac/Chromium.app/Contents/MacOS/Chromium",
      "message": "The binary is not signed.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087721",
      "architecture": "x86_64"
    },`

**Comment by limerickgds** [comment]
@kbourro did it work？

**Comment by andyl-db** [comment]
> @water-a thanks for this solution. Now i have a different issue with mac notarization failed. I see the following error. Did you encounter the same issue ? `{ "severity": "error", "code": null, "path": "SEO+Autopilot.zip/SEO Autopilot.app/Contents/Resources/app/dist/node_modules/puppeteer/.local-chromium/mac-1036745/chrome-mac/Chromium.app/Contents/MacOS/Chromium", "message": "The binary is not signed.", "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087721", "architecture": "x86_64" },`

I think you need to not bundle "Chromium" that's installed with puppeteer. You should ideally use a local version of Chrome/Chromium instead of bundling it with the app.

I didn't see this until @limerickgds replied.

**Comment by water-a** [comment]
> @water-a thanks for this solution. Now i have a different issue with mac notarization failed. I see the following error. Did you encounter the same issue ? `{ "severity": "error", "code": null, "path": "SEO+Autopilot.zip/SEO Autopilot.app/Contents/Resources/app/dist/node_modules/puppeteer/.local-chromium/mac-1036745/chrome-mac/Chromium.app/Contents/MacOS/Chromium", "message": "The binary is not signed.", "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087721", "architecture": "x86_64" },`

@kbourro I think you need to not bundle "Chromium" that's installed with puppeteer. You should ideally use a local version of Chrome/Chromium instead of bundling it with the app.

I didn't see this until @limerickgds replied.

**Comment by kbourro** [comment]
So i used `"afterSign": ".erb/scripts/notarize.js"` in package.json and the following script

`const { notarize } = require('@electron/notarize');
const { signAsync } = require('@electron/osx-sign');
const { build } = require('../../package.json');

exports.default = async function notarizeMacos(context) {
  const { electronPlatformName, appOutDir } = context;
  if (electronPlatformName !== 'darwin') {
    return;
  }

  if (process.env.CI !== 'true') {
    console.warn('Skipping notarizing step. Packaging is not running in CI');
    return;
  }

  if (!('APPLE_ID' in process.env && 'APPLE_ID_PASS' in process.env)) {
    console.warn(
      'Skipping notarizing step. APPLE_ID and APPLE_ID_PASS env variables must be set'
    );
    return;
  }

  const appName = context.packager.appInfo.productFilename;
  await signAgainFunction(appOutDir, appName);
  await notarize({
    appBundleId: build.appId,
    appPath: `${appOutDir}/${appName}.app`,
    appleId: process.env.APPLE_ID,
    appleIdPassword: process.env.APPLE_ID_PASS,
  });
};

// electron-builder vendors its own private version of electron-osx-sign, but unfortunately it is
// broken (https://github.com/electron-userland/electron-builder/issues/5190).  To get around this,
// we install electron-osx-sign ourselves and invoke it in electron-builder's afterSign callback:
// https://www.electron.build/configuration/configuration#aftersign.
async function signAgainFunction(appOutDir, appName) {
  //const identity = 'Developer ID Application: ' + build.mac.certificateIdentity;
  const entitlements = build.mac.entitlements;
  const entitlementsInherit = build.mac.entitlementsInherit;
  const hardenedRuntime = build.mac.hardenedRuntime;
  const gatekeeperAssess = build.mac.gatekeeperAssess;
  try {
    await signAsync({
      app: `${appOutDir}/${appName}.app`,
      entitlements,
      hardenedRuntime,
      'entitlements-inherit': entitlementsInherit,
      'gatekeeper-assess': gatekeeperAssess,
      ignore: (file) =>
        file.includes(
          '/node_modules/puppeteer-extra-plugin-stealth/evasions/chrome.app'
        ),
    });
    console.log('Second application of electron-osx-sign succeeded!');
  } catch (err) {
    console.error('Second application of electron-osx-sign failed');
    console.error(err);
  }
}
`
