### ISSUE TITLE
How to click the captcha only

### ISSUE THREAD

**Issue by swassapparel1** [berstend/puppeteer-extra#446]
Hi everyone! Just wondering on how to use the plugin without the captcha providers. I just want to auto click the captcha box and answer them manually. Thanks!

**Comment by prescience-data** [comment]
Hey @swassapparel1 
As you might have read when you opened this ticket, the Issue Tracker is not a place for support questions. 

Please close and ask in the Discord.

![image](https://user-images.githubusercontent.com/65471523/110623489-040d1600-81f1-11eb-830d-f307ff358fbb.png)

**Comment by berstend** [comment]
@swassapparel1 currently the recaptcha plugin only supports solving through a provider - you might want to look into emulating mouse movements.
