### ISSUE TITLE
[Bug] stealth evasion `navigator.webdriver` needs to be updated following the Chrome v89 release

### ISSUE THREAD

**Issue by starrify** [berstend/puppeteer-extra#448]
The behavior of the `navigator.webdriver` property has been changed in [commit `bfe0108` of Chrome](https://chromium.googlesource.com/chromium/src/+/bfe010892fac3d7731da88478b93ae19953aff1c) like this:

|          | before    | after |
|----------|-----------|-------|
| headful  | undefined | false |
| headless | true      | true  |

Therefore [the `navigator.webdriver` evasion here](https://github.com/berstend/puppeteer-extra/blob/master/packages/puppeteer-extra-plugin-stealth/evasions/navigator.webdriver/index.js) shall be updated accordingly.

This specific commit `bfe0108` has been part of Chrome since major version 89, and recently the stable channel of release has advanced to major version 89, making the fix seemingly more important than before.

**Comment by berstend** [comment]
Without having verified it, isn't `--disable-blink-features=AutomationControlled` fixing this?

**Comment by starrify** [comment]
Apologies in advance for I also submitted this issue before further verification. :sweat-smile:

I'm aware of the current code and the extra arguments for Chrome version `88.0.4291.0` and newer. What I had in mind when creating this ticket was actually these lines of code:

https://github.com/berstend/puppeteer-extra/blob/704502b1005fbe1ac1e2149ffd3715cc7629b50c/packages/puppeteer-extra-plugin-stealth/evasions/navigator.webdriver/index.js#L18-L23

I see that potentially erroneous since that deletes the property unconditionally.

**Comment by starrify** [comment]
Plus at least the unit tests still expect an `undefined` value unconditionally:

https://github.com/berstend/puppeteer-extra/blob/704502b1005fbe1ac1e2149ffd3715cc7629b50c/packages/puppeteer-extra-plugin-stealth/evasions/navigator.webdriver/index.test.js#L20

My proposal would be to parse the browser version before applying the evasion:
- If that's Chrome v88 or before, let's make sure `navigator.webdriver === undefined`
- If that's Chrome v89 or later, let's make sure `navigator.webdriver === false`

**Comment by berstend** [comment]
Ah gotcha :-) This line will just fail/do nothing in `chrome >= 88.0.4291.0`, this could be added to the comment to make that clear and avoid confusion. :-)

> Plus at least the unit tests still expect an undefined value unconditionally:
Oh, good catch - this would make CI fail in the future once we use more recent chrome versions

**Comment by starrify** [comment]
> This line will just fail/do nothing in chrome >= 88.0.4291.0 (as the prop is immutable)

Hmm sorry but I might have got other ideas..

```
$ cat test.js 
// puppeteer@6.0.0 -- bundled Chromium 89.0.4389.0
// puppeteer-extra@3.1.17
// puppeteer-extra-plugin-stealth@2.7.5
(async () => {
  const { addExtra } = require('puppeteer-extra');
  const puppeteer = addExtra(require('puppeteer'));
  if (process.env.TEST_EVASION == 'true') {
    puppeteer.use(
      require('puppeteer-extra-plugin-stealth/evasions/navigator.webdriver')()
    );
  }
  const browser = await puppeteer.launch({
    headless: process.env.TEST_HEADLESS == 'true',
  })
  const page = await browser.newPage();
  const result = await page.evaluate(() => navigator.webdriver);
  console.log(result);
  await page.close();
  await browser.close();
})();

$ TEST_EVASION=false TEST_HEADLESS=true node test.js 
true

$ TEST_EVASION=false TEST_HEADLESS=false node test.js 
true

$ TEST_EVASION=true TEST_HEADLESS=true node test.js 
undefined

$ TEST_EVASION=true TEST_HEADLESS=false node test.js 
undefined
```
