### ISSUE TITLE
My name and email is in the LICENSE file

### ISSUE THREAD

**Issue by flexdinesh** [berstend/puppeteer-extra#45]
Hey there —

Someone sent me an email asking questions about this repo. Then we realized that my name and email is listed in the LICENSE file in the repo. Please update it.

[Link to LICENSE](https://github.com/berstend/puppeteer-extra/blob/c5828dd01333b6dbb15d74e63d9b866b2b2ff2a6/LICENSE#L3)

**Comment by berstend** [comment]
@flexdinesh my sincere apologies, fixed now.
