### ISSUE TITLE
Button cached after performing .click() once

### ISSUE THREAD

**Issue by 74staz** [berstend/puppeteer-extra#450]
I recently switched to puppeteer-extra because of the StealthPlugin. I am trying to the value of dynamic button, it has 2 values (Run & Running). I am trying to grab its value this way:

```
const btnText = await page.$eval('.run-button', el => el.innerText);
if(btnText.includes('Running')) {
	console.log("~already running");
	await browser.close();
	return;
}
```

Now the first time I click the Run button, the request runs fine and response is all good but the next time I press the button through click() it prints out "~already running" because the innerText is still Running somehow(I stopped the run manually so it shows Run for me in Firefox). This didn't happen in puppeteer when I was testing manually. I would be grateful if someone can help on this. Thanks.

**Comment by berstend** [comment]
@74staz can you make a small complete test case?

This would also allow you to comment out stealth or switch to regular puppeteer to compare and verify your issue is related to our project (pretty sure it isn't) :-)

**Comment by berstend** [comment]
I'm closing this as it doesn't adhere to our bug report requirements (as outlined in the issue template).
