### ISSUE TITLE
Nike detects headless puppeteer.

### ISSUE THREAD

**Issue by abokizh** [berstend/puppeteer-extra#453]
I was trying to make a bot for Nike, and it was working before, but apparently, they have updated their protection and now Nike detects puppeteer and does not let me log in (page loads, it just does not let me log in). It use puppeteer stealth and ghost mouse to make my bot act like a real person, but it still does not work. It work when I use headful mode on my Mac, but not with headless on the server. (puppeteer-extra-plugin-stealth@2.7.6)

**UPDATE**

It also work in HEADLESS mode on my Mac, but does not on the server.

**Comment by brunogaspar** [comment]
@abokizh Your best bet is to ask around on our Discord server.

You can find all the information [here](https://github.com/berstend/puppeteer-extra/wiki/Scraping-Chat)

**Comment by Androbin** [comment]
Nike blocks me in headful Chrome/Chromium with stealth enabled but not with stealth disabled. Almost all evasions trigger it. You can this very easily by trying to register at https://www.nike.com/register and see if you get a navigation or an error.

**Comment by berstend** [comment]
Our Github issues are meant for technical discussions:
```
  - NOTE: "SiteA.com stopped working" is not a valid stealth-plugin bug report, unless used 
    as an example to show a technical issue while providing specific example code of the problem.
    For general purpose usage discussions please use the community discord: http://scraping-chat.cf/
```
Site specific discussions are better suited for https://extra.community
