### ISSUE TITLE
Page not navigation after resolve capcha

### ISSUE THREAD

**Issue by Kmax4ever** [berstend/puppeteer-extra#458]
hi everybody, when code resolve capcha (screenshot i see capcha image color is green, debug not see error) , but page not auto navigation ( i used waitForNavigation() ==>time out error,  waitForNavigation({ waitUntil: 'networkidle2' }) ==> infinity time), what i should do to navigator my page

url : https://www.walmart.com/ip/Farberware-Programmable-Digital-Pressure-Cooker-6-Quart/46543314

my code 

`async function processLink(link) {
    const browser = await puppeteer.launch({
        ignoreDefaultArgs: ['--disable-extensions'], headless: true,
        args: [
            '--disable-gpu',
            '--disable-dev-shm-usage',
            '--disable-setuid-sandbox',
            '--no-first-run',
            '--no-sandbox',
            '--no-zygote',
            '--single-process',
        ],
        executablePath: "/usr/bin/chromium-browser"
    });
    const page = await browser.newPage();
    await page.goto(link,
        {
            waitUntil: 'networkidle2'
        }
    );

    await page.solveRecaptchas();

    await page.screenshot({ path: 'after.png' });
    await Promise.all([page.waitForNavigation({ waitUntil: 'networkidle2' })])

    await page.screenshot({ path: 'end.png' });
    await browser.close()

}`

**Comment by brunogaspar** [comment]
As far as i know, the plugin does not perform any auto click or navigation to another page after solving, you need to do it yourself.

Check the [usage](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-recaptcha#usage) for example.

**Comment by berstend** [comment]
As per documentation:
![image](https://user-images.githubusercontent.com/1368633/111980129-2f073c00-8b06-11eb-9f94-1ccae0fb4162.png)

That means the reverse is also true: If no navigation/form submit happens automatically you will need to trigger that yourself.

Just do it manually once and you will see if the captcha is configured to automatically submit a form when solved.
