### ISSUE TITLE
Cvs is detecting puppeteer[Bug] 

### ISSUE THREAD

**Issue by bfp4** [berstend/puppeteer-extra#460]
I'm trying to see if I can schedule a vaccine appointment with puppeteer from cvs. My code was working fine for a while as I was writing, but now I seem to have run into a bug and my code keeps on getting blocked. It gets redirected to a page saying there is technical error, though before this was not happening.

`      
      import puppeteer from "puppeteer-extra"
      import StealthPlugin from 'puppeteer-extra-plugin-stealth'

    const zipCodes = [95020, 95037, 95111, 95119, 95138, 95139, 95121, 95122, 95148, 95135, 95138, 95116, 95122, 95127, 95148, 95127, 95131, 95132, 95133, 95035, 95112, 95128, 95050, 95051, 95054, 95110, 95111, 95112, 95116, 95126, 95128, 95124, 95125, 95126, 95111, 95121, 95122, 95123, 95136, 95120, 95008, 95118, 95124, 95008, 95117, 95128, 95130, 95030, 95032, 95070, 95014, 95129, 94085, 94086, 94087, 94089, 95118, 95030, 95033, 95037]

    async function scraper(){
        puppeteer.use(StealthPlugin())
        const browser = await puppeteer.launch({
            headless: false,
            defaultViewport: null,
            slowMo: 10,
        });
        const page = await browser.newPage();
        // await page.setDefaultNavigationTimeout(0);
        // await page.setDefaultTimeout(0);

        await page.goto("https://www.cvs.com/vaccine/intake/store/cvd-store-select/first-dose-select");

        //https://www.cvs.com/vaccine/intake/store/covid-screener/covid-qns
        await page.evaluate(() => {
            const firstQ = document.getElementById("q7_2")
            firstQ.click()
            const secondQ = document.getElementById("q8_2")
            secondQ.click()
            const thirdQ = document.getElementById("q9_2")
            thirdQ.click()
            const nextButton = document.querySelector(".btn-control")
            nextButton.click()
        })

        // https://www.cvs.com/vaccine/intake/store/imz-select
        await page.waitForSelector("#cvdVacLink")
        await page.evaluate(() => {
            const nextButton = document.getElementById("cvdVacLink")
            nextButton.click()
        })

        //https://www.cvs.com/immunizations/covid-19-vaccine
        await page.waitForSelector(".modal--cta")
        await page.evaluate(() => {
            const stateButton = document.querySelector(".modal--cta")
            stateButton.click()
            const nextButton = document.querySelector(".modal--active .link__text")
            nextButton.click()
        })

        //https://www.cvs.com/vaccine/intake/store/covid-screener/covid-qns second time
        await page.waitForSelector("#q7_2")
        await page.evaluate(() => {
            const firstQ = document.getElementById("q7_2")
            firstQ.click()
            const secondQ = document.getElementById("q8_2")
            secondQ.click()
            const thirdQ = document.getElementById("q9_2")
            thirdQ.click()
            const nextButton = document.querySelector(".btn-control")
            nextButton.click()
        })

        //https://www.cvs.com/vaccine/intake/store/cvd/dose-select
        await page.waitForSelector("#customRadio_1")
        await page.evaluate(() => {
            const dose = document.getElementById("customRadio_1")
            dose.click()
            const nextButton = document.querySelector(".btn-control")
            nextButton.click()
        })

        //https://www.cvs.com/vaccine/intake/store/eligibility-screener/eligibility-covid
        await page.waitForSelector("select")
        await page.select("#jurisdiction", "4: EID_CA")
        await page.evaluate(() => {
            const nextButton = document.querySelector(".btn-control")
            nextButton.click()
        })

        //https://www.cvs.com/vaccine/intake/store/eligibility-screener/eligibility-qns
        await page.waitForSelector("#q1_0")
        await page.type("#q1_0", "41")
        await page.evaluate(() => {
            const option = document.getElementById("q21")
            option.click()
            const consent = document.getElementById("qconsent")
            consent.click()
            const nextButton = document.querySelector(".btn-control")
            nextButton.click()
        })

        //https://www.cvs.com/vaccine/intake/store/cvd/how-to-schedule
        await page.waitForSelector(".dose-content")
        await page.evaluate(() => {
            const nextButton = document.querySelector(".btn-control")
            nextButton.click()
        })

        //https://www.cvs.com/vaccine/intake/store/cvd-store-select/first-dose-select
        await page.waitForSelector("#address")
        for(let el of zipCodes){
            await page.type("#address", el.toString())
            await page.evaluate(() => {
                const searchButton = document.querySelector(".search-icon")
                searchButton.click()
            })
            await page.waitForSelector(".info-text.bold")
            await page.evaluate(() => {
                const infoText = document.querySelector(".info-text.bold").innerText
                const notFound = "None of your selected vaccines are available nearby"
                if(infoText != notFound){
                    const nextButton = document.querySelector(".btn-control")
                    nextButton.click()
                    return
                }
                const input = document.getElementById("address")
                input.value = ""
            })
            console.log("Done: " + el)
        }
    }

    scraper()`

**Comment by prescience-data** [comment]
@bfp4 
When you created this ticket, it should have been impossible to miss this message:
```text
  - NOTE: "SiteA.com stopped working" is not a valid stealth-plugin bug report, unless used 
    as an example to show a technical issue while providing specific example code of the problem.
    For general purpose usage discussions please use the community discord: http://scraping-chat.cf/
```

**Comment by bfp4** [comment]
Dang sorry my bad

**Comment by bfp4** [comment]
close
