### ISSUE TITLE
[HELP] how to call callback function after get captcha token (walmart)

### ISSUE THREAD

**Issue by Kmax4ever** [berstend/puppeteer-extra#463]
hi everybody, i try to reslove captcha in page walmart, in last step, i can't call callbackfunction to reslove captcha, i try use page.evaluate or add button to call callback function but not work, what i have to do to reslove this problem

- callback function in walmart  `data-callback="handleCaptcha"` 
- ![image](https://user-images.githubusercontent.com/38153452/112366533-7d395c80-8d0b-11eb-8053-586a120ad0f6.png)
- my code to call callbackfunction
- method 1
 `    await page.evaluate(async (token) => {
        await handleCaptcha(token);
    }, token);
`
- method 2
`       await page.evaluate((token) => {
        const button = document.createElement("BUTTON")
        button.innerHTML = "CLICK ME";
        button.id = 'submit_function'
        button.addEventListener('click', () => handleCaptcha(token))
        document.getElementById("px-captcha").appendChild(button)

    }, token);
    await page.click('#submit_function')
`
 does someone has experience with walmart captcha, it took me 2 days to try to resolve thiss (''__")

**Comment by berstend** [comment]
Have you considered using the recaptcha plugin which does all of this for you?
https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-recaptcha

**Comment by Kmax4ever** [comment]
i use this plugin , and i DONT RESLOVE WALMART CAPTCHA (both use page.solveRecaptchas() and manual by token recieve), this a reason i write topic here, you think if i dont use that how can i here, have you ever check this problem, instead simply ignore it.

**Comment by berstend** [comment]
@Kmax4ever You don't mention the recaptcha plugin anywhere and you didn't follow the issue template which we've created which would have made that clear (it asks you to give a test snippet as well as to list your installed packages).

It doesn't seem like you were reading the readme either? It clearly states it's taking care of the callback:
![image](https://user-images.githubusercontent.com/1368633/112473391-9a534700-8d6e-11eb-9f29-e9535222ffca.png)

If it doesn't that's a bug but I have trouble reading you bug report.

The readme also mentions this:
![image](https://user-images.githubusercontent.com/1368633/112473468-b0f99e00-8d6e-11eb-993d-c2781f408e74.png)

Overall: Please create a new issue and follow the `[Bug]` template and directions.

**Comment by ejames17** [comment]
Also walmart uses a different type of captcha that the plugin does not support. I have contacted 2captcha and they said they are currently working on a solution for this type of captcha.
Its by perimeter x and its called perimeter x human challenge.
More info can be found here: https://www.perimeterx.com/downloads/product-briefs/PerimeterX-Product-Brief-Human-Challenge.pdf
