### ISSUE TITLE
[Bug] Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (856583).

### ISSUE THREAD

**Issue by sintanial** [berstend/puppeteer-extra#471]
**Describe the bug**
Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (856583).
    at ChromeLauncher.launch (/node_modules/puppeteer-core/src/node/Launcher.ts:112:32)
    at PuppeteerExtra.launch (/node_modules/puppeteer-extra/src/index.ts:172:21)
[nodemon] app crashed - waiting for file changes before starting...

**Code Snippet**

```javascript
import puppeteer from 'puppeteer-extra';
import StealthPlugin from 'puppeteer-extra-plugin-stealth';

(async () => {
    const browser = await puppeteer
        .use(StealthPlugin())
        .launch({});
})();
```

**Versions**

  System:
    OS: macOS 11.2.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 1.10 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.14.0 - /usr/local/bin/node
    npm: 7.7.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    puppeteer: ^8.0.0 => 8.0.0 
    puppeteer-core: ^8.0.0 => 8.0.0 
    puppeteer-extra: ^3.1.18 => 3.1.18 
    puppeteer-extra-plugin-stealth: ^2.7.6 => 2.7.6

**Comment by berstend** [comment]
Remove `puppeteer-core` from your dependencies.

We need to lazy load the puppeteer library and -core has precedence currently. This will be changed in #303.

**Comment by sintanial** [comment]
Thx, worked for me

**Comment by u10k** [comment]
Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (856583).
  
  ```
browser = await puppeteer
            .use(StealthPlugin())
            .launch({});
```
  System:
    OS: Windows 10 10.0.19041
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 4.34 GB / 15.87 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    puppeteer: ^8.0.0 => 8.0.0
    puppeteer-extra: ^3.1.18 => 3.1.18
    puppeteer-extra-plugin-stealth: ^2.7.8 => 2.7.8

**Comment by flashjames** [comment]
I need puppeteer-core when running in docker-aws-lambda and dont want seperate package.json files and I also reuse same file between docker-aws-lambda and regular for setting up puppeteer => I can't import puppeteer in top level in file setting up puppeteer between regular docker and docker-aws-lambda.

My solution is this:
  ```
    const launchOptions = {
        headless: headless,
        devtools: (headless === true) ? false : true,
        ignoreDefaultArgs: ["--enable-automation"],
        args: launchArgs
      }

      let puppeteer = null
      let executablePath
      if(awsLambda) {
        puppeteer = addExtra(chromium.puppeteer)
        executablePath = await chromium.executablePath

        launchOptions["args"] = [...launchOptions.args, ...chromium.args]
      } else {
        // This is needed because we have puppeteer-core as a dependency
        // which doesnt download + setup chromium binary
        // And in the case of awsLambda (if-case above) we dont want puppeteer
        // downloaded
        const { default: mainPuppeteer }  = await import("puppeteer")
        executablePath = mainPuppeteer.executablePath()
        puppeteer = puppeteerFromExtra
      }

      launchOptions["executablePath"] = executablePath

```
