### ISSUE TITLE
[Bug] hCaptcha Detection broken on Cloudflare (@extra/recaptcha)

### ISSUE THREAD

**Issue by spyfly** [berstend/puppeteer-extra#472]
**Describe the bug**
Cloudflare has changed the hCaptcha `baseUrl` to `https://newassets.hcaptcha.com/captcha/v1/` on all my crawled pages, which causes the selector based detection to fail.
https://github.com/berstend/puppeteer-extra/blob/ba40be554e01757fd60a8de61e256cbaecde4287/packages/puppeteer-extra-plugin-recaptcha/src/content-hcaptcha.ts#L19

Replacing this URL with the new baseUrl manually in `@extra/recaptcha` allows solving the captchas again.

**Versions**
```
System:
    OS: Linux 5.11 Ubuntu 20.10 (Groovy Gorilla)
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 18.31 GB / 31.28 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 15.14.0 - /usr/bin/node
    npm: 7.8.0 - /usr/local/bin/npm
  npmPackages:
    playwright: ^1.10.0 => 1.10.0 
    playwright-extra: ^4.2.1-next.616 => 4.2.1-next.616+846b2f2 
```

**Comment by berstend** [comment]
Fixed in `puppeteer-extra-plugin-recaptcha@3.3.8`
