### ISSUE TITLE
[Bug]  Error When using  `puppeteer.use(StealthPlugin());` Then using pkg.

### ISSUE THREAD

**Issue by pp-aio** [berstend/puppeteer-extra#475]
When using extra-plugin-stealth then making an exe with pkg it crashes.
Then when I take it out my exe works fine.
```javascript
const puppeteer = require('puppeteer-extra')
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
 puppeteer.use(StealthPlugin());
;(async () => {
   const browser = await puppeteer.launch({
        headless: false,
     //etc
      });
          const page = await browser.newPage();
          await page.setViewport({ width: 1920, height: 1080 })
// more code 
})()

**Comment by berstend** [comment]
Why are you launching twice?

**Comment by berstend** [comment]
From what I've heard nexe works better then pkg with puppeteer

**Comment by pp-aio** [comment]
> Why are you launching twice?

Error when putting my code into GitHub but nexe wont work for me

**Comment by berstend** [comment]
Unfortunately this bug report doesn't contain enough info or code to make it easy to reproduce or figure out what the issue might be. I'm closing this for now, if you're serious about finding a solution here I recommend making a demo repo with complete code & package.json.
