### ISSUE TITLE
[Feature] others captcha solvers providers

### ISSUE THREAD

**Issue by allandiego** [berstend/puppeteer-extra#481]
**Feature request**
I was checking 2captcha plugin code and found this todo:
https://github.com/berstend/puppeteer-extra/blob/master/packages/puppeteer-extra-plugin-recaptcha/src/provider/2captcha-api.ts#L2

Whats the plan for this own API wrapper? 
I was thinking about improve the recaptcha plugin with a common interface for captcha solvers so it ll be possible implement others providers and they respective APIs like anti-captcha, deathbycaptcha, azcaptcha etc
all have similar behavior you queue a captcha and recieve a queue ID to repetidely request the answer

**Comment by berstend** [comment]
Currently we have no plans on adding more captcha providers, I want to get the automation-extra branch released first as we otherwise have to maintain 2 recaptcha plugins. :-)
