### ISSUE TITLE
[Bug] recaptcha.net domain-based captchas are not detected

### ISSUE THREAD

**Issue by NicolasMarlier** [berstend/puppeteer-extra#483]
Some websites now replace `www.google.com` in their captcha iframe with `www.recaptcha.net` (See https://developers.google.com/recaptcha/docs/faq#can-i-use-recaptcha-globally)

`puppeteer-extra-plugin-recaptcha` does not detect those.

I did a workaround consisting in replacing the iframe domains before calling `page.solveRecaptchas()`, but it would be usefull that regexps used to detect recaptchas can detect this domain as well.

**Comment by brunogaspar** [comment]
@NicolasMarlier Thanks for the report!

Do you mind to share one of those websites? I personally have not seen any website with this behaviour so far :)

Also, if you are up to create a pull request to address this issue, that would be fantastic and highly appreciated!

**Comment by berstend** [comment]
Someone created a PR for this only hours ago 😄 #482

Before we implement anything we need better demo pages to run our tests against, contributions are welcome: https://github.com/berstend/puppeteer-extra/pull/482#issuecomment-825561702

**Comment by berstend** [comment]
Fixed in `puppeteer-extra-plugin-recaptcha@3.3.9`
