### ISSUE TITLE
[Bug] Issue when using puppeteer-extra with `type: module` in package.json

### ISSUE THREAD

**Issue by HuHguZ** [berstend/puppeteer-extra#491]
i use `type: module` in my package.json and get this error:
```javascript
import RecaptchaPlugin from 'puppeteer-extra-plugin-recaptcha';
import puppeteer from "puppeteer-extra";

const { use, launch } = puppeteer;

use(
    RecaptchaPlugin({
        provider: {
            id: '2captcha',
            token: captcha2Token
        },
        visualFeedback: true // colorize reCAPTCHAs (violet = detected, green = solved)
    })
);
```
```
TypeError: Cannot read property '_plugins' of undefined
    at use (C:\Users\Илья\Desktop\work\listener\node_modules\puppeteer-extra\dist\index.cjs.js:68:14)
    at file:///C:/Users/%D0%98%D0%BB%D1%8C%D1%8F/Desktop/work/listener/src/listenThread.js:10:1
    at ModuleJob.run (node:internal/modules/esm/module_job:154:23)
    at async Loader.import (node:internal/modules/esm/loader:177:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
```

**Comment by prescience-data** [comment]
@HuHguZ please add a descriptive title

**Comment by prescience-data** [comment]
@berstend 
![image](https://user-images.githubusercontent.com/65471523/116796629-53046700-ab21-11eb-8c35-8e307d210cd0.png)

**Comment by berstend** [comment]
I think this issue might be specific to `type: module`. Technically we should support ES module usage:
![image](https://user-images.githubusercontent.com/1368633/117086262-634c5a00-ad4c-11eb-8234-70fc704afea8.png)

But I haven't really tested this. Not sure if we need to add/update some more things in our bundler config or package.json here.

For now I recommend using `commonjs`, which is still the standard in Node.js

If someone wants to chime in with more info please do so.

**Comment by berstend** [comment]
PS, from your stack trace: `puppeteer-extra\dist\index.cjs.js` - this should be `index.esm.js` which we correctly point to in the `package.json`:

![image](https://user-images.githubusercontent.com/1368633/117086453-cfc75900-ad4c-11eb-8680-295506d5cb87.png)

**Comment by HuHguZ** [comment]
The problem was that I was using the instance methods of the class separately from the instance.

**Comment by berstend** [comment]
@HuHguZ not sure what that means? so the issue was user error an can be closed?

**Comment by winston01** [comment]
This ticket shouldn't have been closed, as the problem persists (still today).
