### ISSUE TITLE
Feature request: add accept-language header in headless mode

### ISSUE THREAD

**Issue by glestel** [berstend/puppeteer-extra#51]
Hi and thanks for the work

I've noticed that when puppeteer is run in headless mode, it doesn't send the `accept-language` header, which can can be a give-away in bot detection. It would be nice to have it added in the stealth plugins.
Current workaround is adding to the code : 
```
await page.setExtraHTTPHeaders({
    'accept-language': 'fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7'
});
```

Best regards

**Comment by deadNightTiger** [comment]
Better workaround is:
```
puppeteer.launch({ args: ['--lang=en-US'] })
```
It actually enables the browser to send the header instead of emulating it with `setExtraHTTPHeaders` and passes [this test](https://arh.antoinevastel.com/bots/areyouheadless). The difference is proper case of `Accept-Language` and the order of headers.

**Comment by berstend** [comment]
Fixed in latest stealth version (using request modification, so it works with `connect`'ed browsers as well) ;)

**Comment by abacaj** [comment]
@glestel I don't think that's true, go to: https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending

When headless, I can see accept, accept-encoding, as well as accept-language.
