### ISSUE TITLE
[Bug] Google login blocks browser when launching it with a single tab (without "about:blank" page)

### ISSUE THREAD

**Issue by ScriptyChris** [berstend/puppeteer-extra#518]
Hello, i am trying to use `puppeteer-extra-plugin-stealth` to be able to login to Google services. It generally works, except i noticed a bug that my browser is considered as insecure (bot) related to how i declare `page` variable.

**Describe the bug**

Simplified scenario is that i just run the app, which launches browser and navigates to the `https://accounts.google.com/` page. In there i am manually typing my (valid) username and am trying to proceed. The issue is that i get error "Couldn't sign you in" 
![image](https://user-images.githubusercontent.com/18393526/121951001-a857a900-cd5a-11eb-8959-ae9086cd7c69.png)

I noticed that the way of declaring `page` variable has impact.

**Code Snippet**

The reproducible code is below - notice swappable `page` variable declaration lines:

```js
const puppeteer = require('puppeteer-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
puppeteer.use(StealthPlugin());

const CHROMIUM_BROWSER_PATH = 'C:\\Program Files\\BraveSoftware\\Brave-Browser\\Application\\brave.exe';
const BROWSER_PROFILE_PATH = 'C:\\Users\\Krzysiek\\AppData\\Local\\BraveSoftware\\Brave-Browser\\User Data\\Test-profile';

(async () => {
  const browser = await puppeteer.launch({
    headless: false,
    defaultViewport: null,
    executablePath: CHROMIUM_BROWSER_PATH,
    args: [
      `--user-data-dir=${ BROWSER_PROFILE_PATH }`, '--no-first-run', '--no-default-browser-check'
    ],
  });

  /*
    The bug appears depending on below code - it's either [1] or [2]
  */
  const page = await browser.newPage(); // <-- [1] this works
  //const [page] = await browser.pages(); // <-- [2] this doesn't work

  await page.goto('https://accounts.google.com/');
})();

```

The difference in browser GUI is that approach [1] creates two tabs: with `about:blank` empty page and the target with Google page. Approach [2] creates just one tab with target page loaded. I don't know what are technical differences between these two states, but it makes the bug to happen.

I am able to repeatedly swap those two mentioned lines of code (comment one and uncomment the other) while using the same browser's user profile path and the issue interchangeably appears and disappears. It's reproducible for me every time.

I would like to use the way with a single tab (without initial `about:blank` page), to avoid opening tab that won't be used in the app.

**Versions**

>  System:
    OS: Windows 7 6.1.7601
    CPU: (4) x64 Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
    Memory: 10.24 GB / 15.95 GB
  Binaries:
    Node: 14.15.5 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    puppeteer-core: ^10.0.0 => 10.0.0
    puppeteer-extra: ^3.1.18 => 3.1.18
    puppeteer-extra-plugin-stealth: ^2.7.8 => 2.7.8

P.S. I use `puppeteer-core` instead of `puppeteer`, because i make use of Brave browser **[**Version 1.25.72 Chromium: 91.0.4472.101 (Official Build) (64-bit)**]** and i don't need whole boilerplate of packaged Chromium. However, i checked that case on latest Chromium provided by `puppeteer` library (swapping it temporary with `puppeteer-core`) and issue still exists.

**Comment by ScriptyChris** [comment]
Oh, i just noticed that #513 is pretty much the same issue, though i am using headful (not headless) mode.

**Comment by berstend** [comment]
Using existing tabs won't trigger plugin callbacks, workaround is mentioned in the recaptcha plugin readme
