### ISSUE TITLE
How to spoof window.screen api?

### ISSUE THREAD

**Issue by dave-dm** [berstend/puppeteer-extra#56]
Have you given some thought to the screen API? Seems like it could de-anonymize you. For example my mac gives me this:
```
availHeight: 972
availLeft: 0
availTop: 23
availWidth: 1680
colorDepth: 24
height: 1050
orientation: ScreenOrientation {angle: 0, type: "landscape-primary", onchange: null}
pixelDepth: 24
width: 1680
```
What if I wanted to emulate a windows computer? How can I know what is correct "avail" values?

**Comment by berstend** [comment]
Hmmm, not sure how this could be used to detect headless vs headful browsers (what the stealth plugin is all about). Spoofing a different OS is not currently in the scope (happy to merge in PRs for that though). :) Closing for now.
