### ISSUE TITLE
[Bug] devtools plugin not working in headless mode

### ISSUE THREAD

**Issue by abowcut** [berstend/puppeteer-extra#566]
Hi team!

I've started using the puppeteer-extra-plugin-devtools package for remote debugging but have found that when running headless I receive 404 errors when attempting to view pages at the tunnel url.
When running headful everything works as expected however.

To reproduce the issue you can run the code below, visit the public tunnel url, enter the credentials.
You'll see something like the below screenshot:

![landingpage](https://user-images.githubusercontent.com/55000162/134673942-e3f5d4ee-04d6-460c-8fd2-cccd9e47f818.png)

But when clicking on one of the pages you'll see the below 404 error.

![404error](https://user-images.githubusercontent.com/55000162/134673939-b352f6ea-11f7-4400-aede-99e301fe9ef4.png)

**Code Snippet**

```javascript
const puppeteer = require('puppeteer-extra');
const devtools = require('puppeteer-extra-plugin-devtools')();
puppeteer.use(devtools);

(async () => {
    const browser = await puppeteer.launch({ headless: true });
    await devtools.createTunnel(browser);
    const page = await browser.newPage();
    // this could be any url below, I just put a small example webpage to load as an example
    await page.goto('https://meyerweb.com/eric/tools/dencoder/');
    await page.waitForTimeout(60000);
    await browser.close();
    process.exit(0);
})();
```

I'm running recent versions of everything but have tried with some older versions of puppeteer and can't get headless devtools to work.
Also I run macOS but have had the same issue running on amazon linux 2.

**Versions**

  System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 1.64 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.10.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 7.24.0 - /usr/local/bin/npm
  npmPackages:
    puppeteer: ^10.2.0 => 10.4.0
    puppeteer-extra: ^3.1.18 => 3.2.1
    puppeteer-extra-plugin-devtools: ^2.3.0 => 2.3.1
    puppeteer-extra-plugin-stealth: ^2.7.10 => 2.8.1
    puppeteer-page-proxy-abowcut: ^1.2.14 => 1.2.15

**Thank you!**
Thank you for all of your hard work on these plugins, they really are the best and you guys are the best!

**Comment by abowcut** [comment]
I believe I've found the issue but can't seem to find where in the code the problem is sneaking in.
Seems to just be a url formatting issue on the /json/list page (the default page when loading the public tunnel).

When running headful the url's for each of the websocket targets from /json/list look like below (tunnel id and page id obviously will change), and they work properly.
https://devtools-tunnel-jmfdkw6nbf.loca.lt/devtools/inspector.html?wss=devtools-tunnel-jmfdkw6nbf.loca.lt/devtools/page/E006D615B84BA41DBBDDFC502F0E8FC1

However when running headless those same urls for each websocket from /json/list look like the below.
https://chrome-devtools-frontend.appspot.com/serve_file/@70f5d88ea95298a18a85c33c98ea00e02358ad75/inspector.html?wss=devtools-tunnel-zmcypciutj.loca.lt/devtools/page/C8DF50DE28F26F34FC02D2375A5EFA93&remoteFrontend=true

If I adjust the broken url above to the correct format we saw with the headful url then the page properly loads no problem. Ie:
https://devtools-tunnel-zmcypciutj.loca.lt/devtools/inspector.html?wss=devtools-tunnel-zmcypciutj.loca.lt/devtools/page/C8DF50DE28F26F34FC02D2375A5EFA93

What's strange as well is the initial public url for the tunnel is correctly formatted, it's just the websocket targets from /json/list that get messed up.

So seems to me the tunnelHost is somehow getting messed up in the DevToolsTunnel class in RemoteDevTools.js but not sure how or at what point.

Any help here would be much appreciated!
Thanks again!

**Comment by abowcut** [comment]
I've definitely found the problem. The issue arises from the onLoad() function that is called on the html body when running in headless mode.

I can't find where the source code for the index.js file that served up with the page is located though. Seems like it isn't in the puppeteer-extra repo, maybe connected to the appspot app running on gcp that is serving these pages it seems.

Seems like the index.js file served with the page for headful browsers should be the one also served for headless.
Or at least the portion that sets the url of the a tags (on line 27 of the file) should be updated to use the same format the headful one uses, see my comment above.

**Comment by berstend** [comment]
I can confirm the issue with headless:
```js
const puppeteer = require('puppeteer-extra')
const devtools = require('puppeteer-extra-plugin-devtools')()
devtools.setAuthCredentials('user', 'user')
puppeteer.use(devtools)

puppeteer
  .launch({ headless: true, defaultViewport: null })
  .then(async browser => {
    console.log('Start')
    const tunnel = await devtools.createTunnel(browser)
    console.log(tunnel.url)

    const page = await browser.newPage()
    await page.goto('https://example.com')
    console.log('All setup.')
  })
```

The index/devtools page in question is built into the browser, but we have means to modify it already.

You can get a better feel for what's happening by enabling debug logging:
```
DEBUG=remote-devtools node demo.js
```

When running headless the index (`/`) page served is completely different, looking into fixing this now:
```
  remote-devtools proxyReq / +4s
  remote-devtools proxyRes / +5ms
  remote-devtools fetch:after <html>
<head>
<title>Headless remote debugging</title>
<style>
</style>

<script>
const fetchjson = (url) => fetch(url, {credentials: 'include'}).then(r => r.json());

function loadData() {
  const getList = fetchjson("/json/list");
  const getVersion = fetchjson('/json/version');
  Promise.all([getList, getVersion]).then(parseResults);
}

function parseResults([listData, versionData]){
    const version = versionData['WebKit-Version'];
    const hash = version.match(/\s\(@(\b[0-9a-f]{5,40}\b)/)[1];
    listData.forEach(item => appendItem(item, hash));
}

function appendItem(item, hash) {
  let link;
  if (item.devtoolsFrontendUrl) {
    link = document.createElement("a");
    var devtoolsFrontendUrl = item.devtoolsFrontendUrl.replace(/^\/devtools\//,'');
    link.href = `https://chrome-devtools-frontend.appspot.com/serve_file/@${hash}/${devtoolsFrontendUrl}&remoteFrontend=true`;
    link.title = item.title;
  } else {
    link = document.createElement("div");
    link.title = "The tab already has active debugging session";
  }

  var text = document.createElement("div");
  if (item.title)
    text.textContent = item.title;
  else
    text.textContent = "(untitled tab)";
  if (item.faviconUrl)
    text.style.cssText = "background-image:url(" + item.faviconUrl + ")";
  link.appendChild(text);

  var p = document.createElement("p");
  p.appendChild(link);

  document.getElementById("items").appendChild(p);
}
</script>
</head>
<body onload='loadData()'>
  <div id='caption'>Inspectable WebContents</div>
  <div id='items'></div>
</body>
</html>
```

**Comment by berstend** [comment]
@abowcut you are correct, without the weird client-side post processing in `appendItem` on the headless index page everything works well - this wasn't an issue when I first developed the plugin so I assume it's a relatively recent change

**Comment by berstend** [comment]
Should be fixed in #567- thanks @abowcut 👍 
```
Successfully published:
 - puppeteer-extra-plugin-devtools@2.3.2
```

**Comment by kurohoan** [comment]
puppeteer-page-proxy-abowcut

Can I use the above modules?
I tried to use it in combination with the puppeteer-extra-plugin, but it doesn't work.

Or if there is another proxy module, please let me know.

**Comment by abowcut** [comment]
> puppeteer-page-proxy-abowcut
> 
> Can I use the above modules? I tried to use it in combination with the puppeteer-extra-plugin, but it doesn't work.
> 
> Or if there is another proxy module, please let me know.


You can use the puppeteer-page-proxy-abowcut module, I am currently using it on projects I work on.

And you can use it with puppeteer-extra just fine, as long as you aren't using any of the puppeteer-extra packages that implement their own page.on("request") methods (like puppeteer-extra-plugin-adblocker) or else you'll get an error when you attempt to catch the same request more than once.

It's usage is pretty straightforward, I'll put an example below (the strings passed into the function are the connection strings for your proxies).
But to be clear puppeteer-page-proxy-abowcut is useful when you have two different proxies that you want to attempt to use.
One proxy as your primary proxy (normally this would be a cheap datacenter proxy pool) and then a second proxy to try if you receive an error message from the server after trying the first proxy (this second proxy would normally be a residential proxy pool that's more expensive but more reliably is able to load pages).
It basically enables you to waterfall requests through two different proxies without needing the proxy provider itself to support this and you can do so with proxy pools from two different providers, which they would never allow you to easily do.
You could also use something like squid to forward and cache your http requests but I find this method easier to implement and more reliable without the middleware.


```
const useProxy = require("puppeteer-page-proxy-abowcut");
...
await page.setRequestInterception(true);
page.on("request", (request) => {
    if (proxyStringTwo) useProxy(request, proxyStringOne, proxyStringTwo);
    else request.continue();
});
```

**Comment by kurohoan** [comment]
I tried with two different proxies, neither of which worked in my environment.

Is there a possibility to use "puppeteer-extra-plugin-devtools" to identify the cause?

**Comment by abowcut** [comment]
Seems like it should be possible by checking the network tab in the devtools using "puppeteer-extra-plugin-devtools" and checking the status of those requests.

I would guess it's an issue with your proxies though, either connecting to the proxy server or failed requests through the proxy.

Best of luck!

**Comment by kurohoan** [comment]
Thanks for your comments.
Sorry for the delay in contacting you due to the New Year holidays.
In the meantime, I used "proxy-chain" and I could access via proxy, so I don't think it's a problem with the proxy.
I will try "puppeteer-page-proxy-abowcut" again when I have more time.

**Comment by kurohoan** [comment]
I'm using "puppeteer-extra-plugin-stealth", could that be the reason why "puppeteer-page-proxy-abowcut" doesn't work?

**Comment by kurohoan** [comment]
I'm using "puppeteer-extra-plugin-stealth", could that be the reason why "puppeteer-page-proxy-abowcut" doesn't work?

**Comment by kurohoan** [comment]
I tried again, but I could not access the site via proxy using abowcut.
It is not a problem with the proxy, because I can access it with proxy-chain.

Next, I tried to use "puppeteer-extra-plugin-devtools", but I got the following error and could not use it.
This error was not improved by reinstalling the node module.
Can you tell me what it is?


```
INFO  Launching Electron...
App threw an error during load
Error: Cannot find module 'kind-of'
    at webpackEmptyContext (webpack:///./node_modules/merge-deep/node_modules/clone-deep_sync?:2:10)
    at Function.getter [as typeOf] (webpack:///./node_modules/lazy-cache/index.js?:39:29)
    at cloneDeep (webpack:///./node_modules/merge-deep/node_modules/clone-deep/index.js?:14:17)
    at mergeDeep (webpack:///./node_modules/merge-deep/index.js?:19:16)
    at new PuppeteerExtraPlugin (webpack:///./node_modules/puppeteer-extra-plugin/dist/index.esm.js?:59:22)
    at new Plugin (webpack:///./node_modules/puppeteer-extra-plugin-devtools/index.js?:36:5)
    at module.exports (webpack:///./node_modules/puppeteer-extra-plugin-devtools/index.js?:240:10)

```

**Comment by kurohoan** [comment]
@abowcut 
Mr. Berstend no longer replies to me.
I've been struggling for a long time to implement a proxy switch after a browser launch.
Please help me.

**Comment by abowcut** [comment]
> @abowcut Mr. Berstend no longer replies to me. I've been struggling for a long time to implement a proxy switch after a browser launch. Please help me.

Although I'm likely not as busy as berstend is I also don't have a ton of time but if you send over your code to me I'll take a look when I have time.
Sorry I can't be more help.

**Comment by kurohoan** [comment]
@abowcut 
Thanks for the reply.
I am a developer at Electron.
I will contact you again as we create the code for the demo.

**Comment by kurohoan** [comment]
@abowcut
Do you understand Electron?

**Comment by kurohoan** [comment]
@abowcut 
If you'd like to see it in an Electron environment, I'll invite you to the private repository of the demo I've created.

**Comment by kurohoan** [comment]
@abowcut 
I would like a reply when you are available.

**Comment by triposat** [comment]
Need help - what to fill in below fields?

<img width="239" alt="Screenshot 2023-10-19 084610" src="https://github.com/berstend/puppeteer-extra/assets/69134468/ca68e1d3-ff3e-460b-a9a5-cc2f7105dffc">



I'm running below code. What to fill in the username and password?

```javascript
const puppeteer = require('puppeteer-extra')
const devtools = require('puppeteer-extra-plugin-devtools')()
puppeteer.use(devtools)

puppeteer.launch().then(async browser => {
    devtools.setAuthCredentials('bob', 'swordfish')
    const tunnel = await devtools.createTunnel(browser)
    console.log(tunnel.url)

    const page = await browser.newPage()
    await page.goto('https://www.nytimes.com/international/')
    console.log('All setup.')
  })
```
