### ISSUE TITLE
[Feature] Potential puppeteer detection in Accept-Language? 

### ISSUE THREAD

**Issue by ikhvjs** [berstend/puppeteer-extra#568]
**Feature request**

The website I try to access seems to check if the header ```Accept-Language``` is upper case or not. 
If ```Accept-Language``` is upper case, it would not be detected as puppeteer. Otherwise, it would be detected as puppeteer.
It seems that the `Accept-Language` header is always in lowercase in the puppeteer as ```accept-language```.

Somehow, the example below cannot set the accept-language to uppercase.
```
await page.setExtraHTTPHeaders({
  "Accept-Language": "en-US;q=0.7",
});
```
I hope there is a way to change the ```Accept-Language``` in uppercase.

**Comment by ikhvjs** [comment]
My workaround approach:

```js
await page.setRequestInterception(true);
page.on("request", request => {
  // Override headers
  const headers = Object.assign({}, request.headers(), {
    "Accept-Language": "en-US;q=0.7",
  });
  request.continue({ headers });
});
```

**Comment by berstend** [comment]
Did you confirm this is an issue with stealth? AFAIR we fixed this by using the `user-data-dir` plugin to specify a locale.

**Comment by berstend** [comment]
https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth/evasions/user-agent-override

> By default puppeteer will not set a Accept-Language header in headless: It's (theoretically) possible to fix that using either page.setExtraHTTPHeaders or a --lang launch arg. Unfortunately page.setExtraHTTPHeaders will lowercase everything and launch args are not always available. :)

**Comment by berstend** [comment]
PS: 
https://github.com/berstend/puppeteer-extra/blob/a2189e9f2164cb39ce828e1b75e57a7a796886e9/packages/puppeteer-extra-plugin-stealth/evasions/user-agent-override/index.js#L168-L170

**Comment by ikhvjs** [comment]
Sorry, My mistake.

It turns out ```setExtraHTTPHeaders``` make the ```accept-language``` lowercase.
