### ISSUE TITLE
[puppeteer-extra-stealth] does not work on  https://www.badmeubelnet.nl

### ISSUE THREAD

**Issue by MarcelHoogAntink** [berstend/puppeteer-extra#570]
Activating stealth on this site ha no effect at all, the recaptcha is still popping up:

[example4 (2).pdf](https://github.com/berstend/puppeteer-extra/files/7267855/example4.2.pdf)
)

**Comment by berstend** [comment]
Unfortunately this issue doesn't adhere to our guidelines (not enough info). For general support try raising a question in the community discord.
