### ISSUE TITLE
[Bug] Got conflict

### ISSUE THREAD

**Issue by x066it** [berstend/puppeteer-extra#572]
I'm trying to use puppeteer-extra and Got http client in one project.
This code works as expected:
```
import got from "got";
got("https://google.com");
```
But when I import puppeteer-extra:
```
import got from "got";
import { addExtra } from "puppeteer-extra";
got("https://google.com");
```
I get "RequestError: connect ECONNREFUSED 127.0.0.1:443"

**Comment by x066it** [comment]
I did nothing, but everything is working now. Perhaps this was due to the influence of the phases of the moon or something.

**Comment by berstend** [comment]
> I did nothing, but everything is working now. Perhaps this was due to the influence of the phases of the moon or something.

Thanks for the follow-up though :) Kinda sad this issue went away, this would definitely be a strong contender for the weirdest issue the year award 😄
