### ISSUE TITLE
Recaptcha stopped working

### ISSUE THREAD

**Issue by eibrahim** [berstend/puppeteer-extra#58]
For some reason, the recaptcha stopped working on samsclub.com.  It was working fine and then it just stopped working.  Any thoughts?

**Comment by shirshak55** [comment]
I don't think he will support for specific website as they may have bot detection heuristic. Have u tried the example berstend has given?

**Comment by berstend** [comment]
I published a couple of fixes for the recaptcha plugin, please report if this issue still persists with the latest version.
