### ISSUE TITLE
Support for older node version (v8.10.x)

### ISSUE THREAD

**Issue by NWRichmond** [berstend/puppeteer-extra#59]
I have other packages which require use of node `8.10.x` for the time being.

It looks like plugins such as `puppeteer-extra-plugin-stealth` are compatible with node 8, but that the base `puppeteer-extra-plugin` requires node `>=9.11.2` (see packages/puppeteer-extra-plugin/package.json).

Is there any way to make `puppeteer-extra-plugin` compatible with lesser versions of node?

**Comment by NWRichmond** [comment]
@berstend it looks like the change was made with 549427be70c9c64b76df9580ae189746d8623aca when the base plugin was refactored to Typescript and saw a version bump to from `2.0.1` to `3.0.1`.

**NOTE**
I can use `puppeteer-extra-plugin-stealth` version `2.1.6`, which appears to be the last version to use `puppeteer-extra-plugin` version `2.0.1`, but I can't use `puppeteer-extra-stealth` as all versions require `puppeteer-extra-plugin` version `3.0.1` and higher.

**Comment by shirshak55** [comment]
any reason to support node8 which will be out of maintenance after 2020 which is too near imho.

https://nodejs.org/en/about/releases/

By the way you don't need to use stealth plugin you can use this for stealth

https://github.com/shirshak55/scrapper-tools/blob/master/src/fastPage/pageStealth.ts

**Comment by NWRichmond** [comment]
@shirshak55 I agree that the end of Node 8 maintenance is too close to justify support. With that in mind, it's probably best to close this issue.

P.S. - My use case requires the recaptcha plugin also, but I appreciate the link to the other stealth package.

**Comment by shirshak55** [comment]
@NWRichmond i was thinking of making new recaptcha one that due to financial issue I was unable to make it as those api requires payment etc ...
