### ISSUE TITLE
iframe.contentWindow evasion need again

### ISSUE THREAD

**Issue by r1si** [berstend/puppeteer-extra#60]
With this commit, evasions of chrome iframe will be removed: 
https://github.com/berstend/puppeteer-extra/commit/849c0326ba456dbdc239c92ff3e3d2deaf7ec82a?_pjax=%23js-repo-pjax-container

I have test today with fresh simple project (like descript here): https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth ) 
and attach the result.... has u can seen chrome iframe test failed!
![testresult](https://user-images.githubusercontent.com/6353773/63636001-8ebb0e00-c669-11e9-833f-3938966a80b9.png)

**Comment by dokugo** [comment]
Having the same issue. Try `npm i puppeteer-extra-plugin-stealth@2.1.3` for a quick fix.

**Comment by invkrh** [comment]
Yes, I have the same problem too. My bot was detected due to this.
Although we can make it work by adding in client code ...
```
await this.page.evaluateOnNewDocument(() => {	
      // eslint-disable-next-line	
      Object.defineProperty(HTMLIFrameElement.prototype, 'contentWindow', {	
        get: function () {	
          return window	
        }	
      })	
    })
```
It would be better to add it back.

**Comment by momala454** [comment]
> 
> 
> Yes, I have the same problem too. My bot was detected due to this.
> Although we can make it work by adding in client code ...
> 
> ```
> await this.page.evaluateOnNewDocument(() => {	
>       // eslint-disable-next-line	
>       Object.defineProperty(HTMLIFrameElement.prototype, 'contentWindow', {	
>         get: function () {	
>           return window	
>         }	
>       })	
>     })
> ```
> 
> It would be better to add it back.

no this break some website that use iframes

**Comment by daynejones** [comment]
This also breaks my code.

**Comment by berstend** [comment]
> no this break some website that use iframes

Yup, that was the (unfortunate) reason I removed that a while back. :-/

**Comment by berstend** [comment]
We can either find a solution with no breakage or we might consider adding a "tinfoil" preset (opt-in) in the stealth plugin to enable this fix when breaking iframes is not a problem.

**Comment by Nothing4You** [comment]
Wouldn't this "fix" also easily be detectable because iframes are not working anymore?
So it would easily be detectable if someone just checks for this.

**Comment by dokugo** [comment]
I have managed to pass the `HEADCHR_IFRAME` test on [this page](https://antoinevastel.com/bots) with `"puppeteer-extra-plugin-stealth": "^2.1.3`. Note that these tests aren't running if you're doing `script` type request interception, but I guess that the most users of Puppeteer need scripts enabled.

[This test](https://arh.antoinevastel.com/bots/areyouheadless) is also passable.

But for some reason [there](https://bot.sannysoft.com/) is `MQ_SCREEN` test failing (even in normal headful Chrome installed on W10).

**Comment by momala454** [comment]
> 
> 
> I have managed to pass the `HEADCHR_IFRAME` test on [this page](https://antoinevastel.com/bots) with `"puppeteer-extra-plugin-stealth": "^2.1.3`. Note that these tests aren't running if you're doing `script` type request interception, but I guess that the most users of Puppeteer need scripts enabled.
> 
> [This test](https://arh.antoinevastel.com/bots/areyouheadless) is also passable.
> 
> But for some reason [there](https://bot.sannysoft.com/) is `MQ_SCREEN` test failing (even in normal headful Chrome installed on W10).

WebGL Vendor test also fails for me because of "Google Inc.'" on legit chrome headful

**Comment by flunkman** [comment]
Why this test pass with 2.1.3 and not anymore with 2.2.x/2.3.x?

**Comment by berstend** [comment]
I just released a larger change (re-writing the core to TypeScript), next on my list is #78 to make the whole stealth plugin situation more tested and "academic". 😄

**Comment by berstend** [comment]
I think I found a way to fix this without breaking other frame related stuff!

Please checkout `v2.4.0` of the stealth plugin ([Changelog](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth#v240)) which contains a boat load of other fixes as well. :)

Closing this for now, please open a new issue if you experience any issues with the new release.

**Comment by netbroom** [comment]
A little late but, this might be more elegant and simple, and introduce fewer bugs. Basically when the contentWindow getter is called, we run the getter ourselves, and modify the resulting object.

```
	let cwGetter = Object.getOwnPropertyDescriptor(HTMLIFrameElement.prototype, 'contentWindow').get;
	
	Object.defineProperty(HTMLIFrameElement.prototype, 'contentWindow', {
		get() {
			let contentWindow = cwGetter.call(this, arguments);
			contentWindow.chrome = window.chrome;
			return contentWindow;
		}
	});
	
	const iframe = document.createElement('iframe');
	iframe.srcdoc = 'blank page';
	document.body.appendChild(iframe);
	
	console.log(iframe.contentWindow);
	console.log(iframe.contentWindow.chrome);
	console.log(iframe.srcdoc);
	
```

**Comment by netbroom** [comment]
A little late but, this might be more elegant and simple, and introduce fewer bugs. Basically when the contentWindow getter is called, we run the getter ourselves, and modify the resulting object.

For the actual evasion, you can run in evaluateOnNewDocument. The testing code fails because it can't add the iframe until the document is created but it's just to demonstrate in JS that we can proxy the contentWindow getter function.

```
	let cwGetter = Object.getOwnPropertyDescriptor(HTMLIFrameElement.prototype, 'contentWindow').get;
	
	Object.defineProperty(HTMLIFrameElement.prototype, 'contentWindow', {
		get() {
			let contentWindow = cwGetter.call(this, arguments);
			contentWindow.chrome = window.chrome;
			return contentWindow;
		}
	});
	
	// for testing in regular JS to demonstrate modified object, this won't work with puppeteer's evaluateOnNewDocument until document is created
	const iframe = document.createElement('iframe');
	iframe.srcdoc = 'blank page';
	document.body.appendChild(iframe);
	
	console.log(iframe.contentWindow);
	console.log(iframe.contentWindow.chrome);
	console.log(iframe.srcdoc);
	
```

**Comment by vladtreny** [comment]
This will detect you. 

```
Object.getOwnPropertyDescriptor(HTMLIFrameElement.prototype, 'contentWindow').get.toString().includes('[native code]')
```

Better wrap into proxy, but still detectable by some anti-bots.
