### ISSUE TITLE
[Bug] Chromium crashes on browser.close() when using plugin-stealth 2.9.0

### ISSUE THREAD

**Issue by josep11** [berstend/puppeteer-extra#601]
Chromium crashes on browser.close() when using plugin-stealth.
I tried it using another plugin like puppeteer-extra-plugin-adblocker and it doesn't crash.
It happens in a similar fashion as with #421.
It obviously doesn't happen when headless launch option is set to false.

**Code Snippet**

```javascript
const puppeteer = require('puppeteer-extra')

// const AdblockerPlugin = require('puppeteer-extra-plugin-adblocker');
// puppeteer.use(AdblockerPlugin());
const StealthPlugin = require('puppeteer-extra-plugin-stealth')
puppeteer.use(StealthPlugin());

const url = "https://github.com/berstend/puppeteer-extra/issues/421";

(async () => {
    const browser = await puppeteer.launch({
        headless: false,
        slowMo: 150,
        ignoreHTTPSErrors: true
    })

    const page = await browser.newPage();

    await page.goto(url, { waitUntil: 'domcontentloaded' });

    await browser.close();
})()
```

**Versions**

@types/puppeteer@5.4.4
child-process-async@1.0.1
colors@1.4.0
dotenv@10.0.0
eslint@8.5.0
fs@0.0.1-security
is-internet-available@3.0.0
jsonpath@1.1.1
mocha-junit-reporter@2.0.2
mocha@9.1.3
puppeteer-extra-plugin-adblocker@2.12.0
puppeteer-extra-plugin-stealth@2.9.0
puppeteer-extra@3.2.3

**Comment by berstend** [comment]
Should be fixed through #656
