### ISSUE TITLE
[Bug] No longer stealth, need update

### ISSUE THREAD

**Issue by okofishe** [berstend/puppeteer-extra#604]
Hello bro,
Your stealth is no longer stealth. Try it at (https://fingerprintjs.com/)
Just bringing this to your attention.
Thanks a lot

**Describe the bug**

**Code Snippet**

```javascript
const puppeteer = require('puppeteer-extra')

;(async () => {
  const browser = await puppeteer.launch()
  // ...
})()
```

**Versions**

**Comment by mendoanjoe** [comment]
@okofishe do you add this ?
```js
// add stealth plugin and use defaults (all evasion techniques)
const StealthPlugin = require('puppeteer-extra-plugin-stealth')
puppeteer.use(StealthPlugin())
```

**Comment by guyschlider** [comment]
I see detection as well using StealthPlugin

**Comment by lellywang** [comment]
I'm finding the same. My Visitor ID is the same even when I use different windows with different IPs. Try: https://fingerprintjs.com/demo/
