### ISSUE TITLE
Captcha solves but iframe doesn't disappear

### ISSUE THREAD

**Issue by rostgoat** [berstend/puppeteer-extra#61]
Intermittently, I get this behaviour where a captcha is solved (purple turns to green) and `solved` returns some result but the captcha element doesn't hide afterwards, causing my test to fail.

anyone had this before?

![Screenshot from 2019-08-26 10-54-26](https://user-images.githubusercontent.com/22672124/63711366-1df22e00-c7f0-11e9-992a-2443cf287f9a.png)

**Comment by jonkratz** [comment]
I am also running into an issue where I seem to have a solved reCaptcha with green visual cue, but the reCaptcha is still failing. I'm wondering if I'm experiencing this same issue. Are there other things that need to happen besides simply adding the solution to reCaptcha (such as the frame needing time to disappear or something?).

**Comment by antonioiliev** [comment]
I run into the same issue. I use both 2Captcha and manual solving (clicking it with my mouse). The result is always the same - the recaptcha reappears again and again, it simply does not believe I am a human.

I am using it on Ebay though. I am also not sure what causes that.

**Comment by berstend** [comment]
I published a couple of fixes for the stealth plugin, please report if this issue still persists with the latest version.
