### ISSUE TITLE
[Bug] puppeteer-extra-plugin-adblocker: upgrade adblocker-puppeteer

### ISSUE THREAD

**Issue by NightTsarina** [berstend/puppeteer-extra#616]
Hi!

I noticed that puppeteer-extra-plugin-adblocker depends on [@cliqz/adblocker-puppeteer](https://www.npmjs.com/package/@cliqz/adblocker-puppeteer) v1.22.6, which in turn depends on puppeteer <= v10.

could you update the dependency to the current version (v1.23.4), which supports puppeteer up to v13?

Thanks

**Comment by berstend** [comment]
Fixed :)

```
Successfully published:
 - puppeteer-extra-plugin-adblocker@2.13.0
 ```
