### ISSUE TITLE
Downloading PDF using Puppeteer Extra

### ISSUE THREAD

**Issue by ags4436** [berstend/puppeteer-extra#619]
Hi @berstend, 

We are trying to download PDF using Puppeteer for a long time, and we finally found that Puppeteer-Extra is the only way to do that. Is there anything which we can develop from our end to replicate PDF download alone from Puppeteer Extra ?
We are looking to use puppeteer-core only and aspiring to create in-house functionality to download the documents.
Could you please give some insights on this ?

**Comment by berstend** [comment]
This is better suited for https://extra.community :)
