### ISSUE TITLE
disconnected event does not work with puppeteer-extra-plugin-stealth [Bug] 

### ISSUE THREAD

**Issue by CarmenLexa** [berstend/puppeteer-extra#620]
When using the puppeteer-extra-plugin-stealth plugin the disconnected event does not work, it does not fire.

const puppeteer = require('puppeteer-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
const pluginStealth = StealthPlugin();
puppeteer.use(pluginStealth);

const navegar = await puppeteer.launch({
              executablePath: padre.PATH_EXECUTABLE_LOCAL,
              headless: false,
              ignoreHTTPSErrors: true,
              devtools: false,
              defaultViewport: null, 
              slowMo: 0,
              ignoreDefaultArgs: ["--enable-automation"],
              args: [  
                '--start-maximized', 
                '--mute-audio',
                '--disable-features=IsolateOrigins,site-per-process',
                '--flag-switches-begin',
                '--disable-site-isolation-trials',
                '--flag-switches-end',

                '--disable-crash-reporter',
                '--disable-dev-profile',
                '--disable-gpu',
                '--disable-notifications',
                '--disable-offer-store-unmasked-wallet-cards',
                '--disable-offer-upload-credit-cards',
                '--disable-password-generation',
                '--disable-setuid-sandbox',
                '--disable-speech-api',
                '--disable-suggestions-ui',
                '--disable-web-security',
                '--enable-async-dns',

                '--allow-file-access-from-files', 
                '--allow-file-access', 
                '--allow-cross-origin-auth-prompt',
                
                '--enable-tcp-fast-open',
                // Hide scrollbars from screenshots.
                '--hide-scrollbars',
                '--no-default-browser-check',
                '--no-experiments',
                '--no-pings',
                '--no-sandbox',
                '--no-zygote',
                '--prerender-from-omnibox=disabled',
                '--disable-features=SameSiteByDefaultCookies,CookiesWithoutSameSiteMustBeSecure',

                '--user-agent='+`${padre.USER_AGENT}`,
                '--disable-extensions-except='+`${padre.PATH_EXTENSION_LOCAL}`,
                '--load-extension='+`${padre.PATH_EXTENSION_LOCAL}`,
            ]
        });
       navegar.on('disconnected', async () => {
             console.log("disconnected");
       });

**Comment by berstend** [comment]
This issue is better suited for our discord chat as it doesn't contain any debug info:
https://github.com/berstend/puppeteer-extra/wiki/Scraping-Chat
