### ISSUE TITLE
[Feature] Allow setting the HOST header

### ISSUE THREAD

**Issue by gcleaves** [berstend/puppeteer-extra#626]
**Feature request**

Please consider altering Puppeteer-Extra so as to allow overwriting the HOST header. Currently, it is not possible as discussed in this bug: https://github.com/puppeteer/puppeteer/issues/6167

**Comment by berstend** [comment]
Closing this as "wont fix" for now until more info is provided on how an integration like this is meant to look like.

There's also workarounds mentioned in the linked issue
