### ISSUE TITLE
[Bug] potential mistake on newbie tutorial

### ISSUE THREAD

**Issue by EthanTheMathmo** [berstend/puppeteer-extra#627]
When running the newbie tutorial, [here](https://github.com/berstend/puppeteer-extra/wiki/Newbie-Guide-To-Scraping-With-Puppeteer), the following code generated a 'UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: __awaiter is not defined' error. However, both code snippets worked when I tested it in browser console.

```
const lessonList = await page.evaluate(async () => {
    let results = []

    // Get all the divs with the class "page", this is our list of Lessons.
    const lessons = document.querySelectorAll("div.page")

    // Parse the important information from each div.
    lessons.forEach((lesson) => {
      results.push({
        title: lesson.querySelector("h3.page-title").innerText,
        description: lesson.querySelector("p.lead").innerText,
      })
    })

    // Return the results we have scraped.
    return results
  })
```

This was fixed for me by removing the async, i.e. going to:

```
const lessonList = await page.evaluate(() => {
    let results = []

    // Get all the divs with the class "page", this is our list of Lessons.
    const lessons = document.querySelectorAll("div.page")

    // Parse the important information from each div.
    lessons.forEach((lesson) => {
      results.push({
        title: lesson.querySelector("h3.page-title").innerText,
        description: lesson.querySelector("p.lead").innerText,
      })
    })

    // Return the results we have scraped.
    return results
  })

```
System information requested. (I am running it using repl.it, a link to the repl is  [here](https://replit.com/join/phcwkjepqz-ethanhorsfall)
**npx envinfo@latest --system --binaries --npmPackages '*(puppeteer*|playwright*|automation-extra*|@extra*)'
npx: installed 1 in 1.621s

  System:
    OS: Linux 5.13 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (4) x64 AMD EPYC 7B12
    Memory: 17.06 GB / 31.35 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 14.17.1 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 6.14.15 - /usr/bin/npm
  npmPackages:
    puppeteer: ^2.1.1 => 2.1.1 
    puppeteer-extra: ^3.2.3 => 3.2.3 
    puppeteer-extra-plugin-stealth: ^2.9.0 => 2.9.0 
**

Many thanks for the tutorial, apologies if this is an oversight on my part.

**Comment by Gylesie** [comment]
Most likely your async function is being transpiled. However the function that was transpiled now runs in a totally different execution context - the browser. That doesnt have polyfills in the global namespace and thus throws you this error. The snippet should be fine as long as you turn of the transpiler.

**Comment by berstend** [comment]
Closing as per above comment
