### ISSUE TITLE
[Bug] Headless Chrome is added after link is clicked

### ISSUE THREAD

**Issue by ghost** [berstend/puppeteer-extra#633]
**Describe the bug**

I have connected the stealth plugin.
According to my expectations, I go to the site and click on the link, after that I go to a new page and intercept it, and at the same time its useragent should be without headless.
Run my code.

**Code Snippet**

```
const puppeteer = require('puppeteer-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth')
puppeteer.use(StealthPlugin())

(async () => {
  const browser = await puppeteer.launch({
    headless: true,
    defaultViewport: null,
    executablePath: '/usr/bin/chromium'
  });

  const page = await browser.newPage();
  await page.setDefaultNavigationTimeout(0);

  let newPage;

  await page.goto('https://localhost/tests.html', {waitUntil: 'networkidle0'});

let newPagePromise = new Promise(x => browser.once('targetcreated', target => x(target.page())));
let s1 = await page.evaluate(() => navigator.userAgent)
console.log(s1)
await page.click('.link');
newPage = await newPagePromise;
let s2 = await newPage.evaluate(() => navigator.userAgent)
console.log(s2)

  await browser.close();
})();

```

Output:
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/100.0.4896.88 Safari/537.36
```

As you can see they are different and that's why I can't make not noticeable bots.

tests.html:
```
<a class="link" href="/tests2.html" target="_blank">url</a>

```
tests2.html:
```
test
```

**Versions**

System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 1.53 GB / 16.0 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.15.0 - /snap/bin/node
    Yarn: 1.22.18 - /snap/bin/yarn
    npm: 8.5.5 - /snap/bin/npm
  npmPackages:
    puppeteer: ^13.5.2 => 13.5.2 
    puppeteer-core: ^13.5.2 => 13.5.2 
    puppeteer-extra: ^3.2.3 => 3.2.3 
    puppeteer-extra-plugin-stealth: ^2.9.0 => 2.9.0

**Comment by berstend** [comment]
The example code is iffy, closing this
