### ISSUE TITLE
[Bug] Does not detect and solve V2 Enterprise

### ISSUE THREAD

**Issue by salehasadi** [berstend/puppeteer-extra#635]
**I used this plugin to solve v2 captcha following document instructions and it was working as expected, but now target changed to V2 Enterprise and plugin cannot detect and solve it anymore**

![image_2022_05_05T14_14_24_672Z](https://user-images.githubusercontent.com/14921568/166944004-883dbd0e-c68d-438a-adbf-b69b75743d3c.png)

could you please check if there is an issue or help me about how I can pass this? thanks

**Comment by avimar** [comment]
This image is V2 enterprise?

I'm currently having no luck with this type of captcha also.

**Comment by salehasadi** [comment]
> This image is V2 enterprise?
> 
> I'm currently having no luck with this type of captcha also.

yes that's V2 enterprise. we could bypass it using audio captcha but they disabled that, and added another layer of cloud flare detection.

**Comment by gencoglutugrul** [comment]
I am experiencing the same issue. Also, I've figured out there is no support for the enterprise captcha on the 2captcha-api npm package which is a dependency of puppeteer-extra-plugin-recaptcha. Solution is simple we just need to pass 'enterprise=1' as a parameter to request that calls `http://2captcha.com/in.php`

**Comment by berstend** [comment]
The plugin supports all configurations found here: https://berstend.github.io/static/recaptcha/

If one is faulty or missing please create a new issue with demo code, thanks!

**Comment by berstend** [comment]
PPS: In cases like this it'd be good to already differentiate if the detection is the issue or if 2captcha is just unable to solve it. The readme mentions how to enable debug logging to get more insights

**Comment by avimar** [comment]
... apparently the first reason I was having so much trouble is that it was actually datadome which uses recaptcha.

Currently trying anticaptcha for this.

**Comment by gencoglutugrul** [comment]
> > gencoglutugrul
> 
> we tested both 2Captcha and Anticaptcha services for that, but provided tokens were not satisfying the portal.

That's answered here: https://anti-captcha.com/faq/494_everything_about_recaptcha_enterprise#:~:text=Why%20my%20Enterprise%20tokens%20are%20not%20working%3F
Short answer: you need to try until it success and pay for every attempt.
