### ISSUE TITLE
[Bug] Hijacking createElement breaks functionality on some sites

### ISSUE THREAD

**Issue by andywaite** [berstend/puppeteer-extra#636]
**Describe the bug**
Using the stealth plugin to download this site https://www.therapiezeit-duelmen.de/ causes the cookie banner plugin installed on the site to become unresponsive. This appears to be down to the Stealth plugin hijacking the createElement API in the `iframe.contentWindow` evasion.

Without stealth plugin: It's possible to click on the cookie banner to dismiss it, no additional console errors.
![Screenshot 2022-04-26 at 18 53 36](https://user-images.githubusercontent.com/6773151/167005178-200c3c84-b086-4a24-a457-9ab28ba63181.png)

With stealth plugin: it's not possible to click on the cookie banner to dismiss it and there are additional errors.
![Screenshot 2022-04-26 at 18 53 04](https://user-images.githubusercontent.com/6773151/167005174-2b1828f4-ba2b-4524-bddc-0887873b577f.png)

I've traced this as far back as the `iframe.contentWindow` evasion hijacking the `document.createElement` API. The page in question seems to be attempting to do its own hijacking of this API, and it falls over as a result of the property being read only.

Would like to contribute further but at this point I'm a little out of my depth.

**Code Snippet**

***With stealth***
```javascript
const puppeteer = require('puppeteer-extra')
const StealthPlugin = require('puppeteer-extra-plugin-stealth')

;(async () => {
  const browser = await puppeteer.use(StealthPlugin()).launch()

  const page = await browser.newPage()

  const response = await page.goto('https://www.therapiezeit-duelmen.de/', {
    waitUntil: 'networkidle2'
  })

    await page.click('#infobar-acceptCookiesBtn')
    await page.screenshot({path: 'with-stealth.png'})
  // ...
})()
```

***Without stealth***
```javascript
const puppeteer = require('puppeteer-extra')
const StealthPlugin = require('puppeteer-extra-plugin-stealth')

;(async () => {
  const browser = await puppeteer.launch()

  const page = await browser.newPage()

  const response = await page.goto('https://www.therapiezeit-duelmen.de/', {
    waitUntil: 'networkidle2'
  })

    await page.click('#infobar-acceptCookiesBtn')
    await page.screenshot({path: 'without-stealth.png'})
  // ...
})()
```

Check the resulting screenshots and notice how one has a cookie banner, the other does not.

**Versions**

  System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 106.50 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  npmPackages:
    puppeteer-core: ^10 => 10.4.0 
    puppeteer-extra: ^3.2.3 => 3.2.3 
    puppeteer-extra-plugin-block-resources: ^2.3.0 => 2.3.0 
    puppeteer-extra-plugin-stealth: ^2.9.0 => 2.9.0 
    puppeteer-extra-plugin-user-data-dir: ^2.3.1 => 2.3.1

**Comment by andrei0x309** [comment]
I faced the same issue with that evasion I just disabled it I saw this PR https://github.com/berstend/puppeteer-extra/pull/565 don't know if it addresses this it would be nice if this evasion is changed not to break sites.
