### ISSUE TITLE
[Bug] 2captcha API Return "503 Service Unavailable"

### ISSUE THREAD

**Issue by signaldev1** [berstend/puppeteer-extra#639]
Hello ,

i use "**puppeteer-extra-plugin-recaptcha**" plugin but Recently i recieved to many times this error "**503 Service Unavailable**"

**code:** 

```
const RecaptchaPlugin = require('puppeteer-extra-plugin-recaptcha')

await puppeteer.use(
                    RecaptchaPlugin({
                      provider: {
                        id: '2captcha',
                        token: 'API KEY'
                      },
                      visualFeedback: true 
                    })
                  )
                  ....

```
**How  i resolve the captcha** 

                await page.waitForSelector('iframe[src*="recaptcha/"]', { visible:true })
                await page.waitForTimeout(1000)
                for (const frame of page.mainFrame().childFrames()){
                    let { captchas, error }   = await frame.findRecaptchas()
                    let { solutions, error1 } = await frame.getRecaptchaSolutions(captchas)
                    let { solved, error2 }    = await frame.enterRecaptchaSolutions(solutions)
                    await frame.solveRecaptchas()
                    await frame.waitForSelector('button[id="recaptcha-submit"]', { visible:true })
                    await frame.click('button[id="recaptcha-submit"]')
                }

**Error recieved**

```
PuppeteerExtraPluginRecaptcha: An error occured during "getRecaptchaSolutions": {
  _vendor: 'recaptcha',
  provider: '2captcha',
  id: '8l8.....',
  requestAt: 2022-05-25T19:11:04.770Z,
  error: 'Error: 2captcha error: 503 Service Unavailable\n'
}

```
thank you

**Comment by berstend** [comment]
I assume this was a temporary issue? If not create a new issue please
