### ISSUE TITLE
Works in !headless, fails in Headless..

### ISSUE THREAD

**Issue by Exoplanet3000** [berstend/puppeteer-extra#64]
Sign in on *redacted* works on !headless, but rejects login while headless...
I'm using the standard plugins + the language fix. Anybody know of a possible solution? 

`const puppeteer = require("puppeteer-extra");
const StealthPlugin = require("puppeteer-extra-plugin-stealth");
puppeteer.use(StealthPlugin());

const UserAgentPlugin = require("puppeteer-extra-plugin-anonymize-ua");
puppeteer.use(UserAgentPlugin({ makeWindows: true }));

(async () => {
  const browser = await puppeteer.launch(
    { headless: true },
    { args: ["--lang=en-US,en;q=0.9"] }
  );
  const page = await browser.newPage();
  await page.setViewport({ width: 800, height: 600 });

await page.goto(
    "redacted",
    { waitUntil: "networkidle2" }
  );`

**Comment by Exoplanet3000** [comment]
Soo, I evaded this apparent bot security implementation by utilizing userDataDir!

**Comment by Exoplanet3000** [comment]
I mean by using the`args`

**Comment by berstend** [comment]
By pointing pptr to use your existing Chrome profile you might bypass certain checks (as you already have a session, cookie, etc for that site). :)
