### ISSUE TITLE
[Bug] the function page.frameLocator doesn't work

### ISSUE THREAD

**Issue by TrixTM** [berstend/puppeteer-extra#642]
**Describe the bug**
 page.frameLocator doesn't work
-->

**Code Snippet**
await page.frameLocator('text=Text hereeeeee >> iframe').locator('div[role="checkbox"]').click();

**Versions**
latest

**Comment by recurrence** [comment]
@TrixTM Please give this a better subject, "[Bug]" is not helpful :)

**Comment by TrixTM** [comment]
> @TrixTM Please give this a better subject, "[Bug]" is not helpful :)

Done

**Comment by berstend** [comment]
This is not a good bug report, please create a new one with expected behavior and confirmation it works in puppeteer but not puppeteer-extra
