### ISSUE TITLE
[puppeteer-extra-plugin-adblocker] Missing `puppeteer` peer dependency

### ISSUE THREAD

**Issue by rtritto** [berstend/puppeteer-extra#644]
`puppeteer` is a peer dependency of `@cliqz/adblocker-puppeteer`, so must include it as peer dependency (transitive peer dependencies).

## Changes
`package.json`
```diff
"peerDependencies": {
+  "puppeteer": "*",
  ...
}
```

**Comment by berstend** [comment]
@rtritto reopening this, can you give an example on how this is an issue?
