### ISSUE TITLE
Can't bypass Cloudflare protection. Anyway to do that?

### ISSUE THREAD

**Issue by Croodo** [berstend/puppeteer-extra#648]
I'm trying to scrape data from a website having Cloudflare protection. Everything works good when on local host but doesn't work on a server like Heroku. 

Anyone give me a suggestion, please.

**Comment by Verz1Lka** [comment]
You need to solve this issue  to bypass it https://github.com/berstend/puppeteer-extra/issues/451

**Comment by Croodo** [comment]
**Solved:** Simply adding random-useragent solved the issue !
