### ISSUE TITLE
[Bug] "TypeError: page._client.send is not a function" when running npx extract-stealth-evasions

### ISSUE THREAD

**Issue by decaffeinatedio** [berstend/puppeteer-extra#651]
**Describe the bug**
When running `npx extract-stealth-evasions` on a variety of systems (PopOS 22 locally), I receive the error:

```
TypeError: page._client.send is not a function
    at Plugin.onPageCreated (/home/ian/.npm/_npx/352800/lib/node_modules/extract-stealth-evasions/node_modules/puppeteer-extra-plugin-stealth/evasions/user-agent-override/index.js:180:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Plugin._onTargetCreated (/home/ian/.npm/_npx/352800/lib/node_modules/extract-stealth-evasions/node_modules/puppeteer-extra-plugin/dist/index.cjs.js:496:21)
```

If I exclude the user-agent-override evasion, the command runs successfully. 

**Code Snippet**

**Versions**

```
  System:
    OS: Linux 5.17 Pop!_OS 22.04 LTS
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 6.48 GB / 30.98 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 14.9.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
```

**Comment by Miosame** [comment]
`If I exclude the user-agent-override evasion, the command runs successfully.`

Can you describe how you do that?

**Comment by decaffeinatedio** [comment]
@Miosame Sure can:

`npx extract-stealth-evasions -e user-agent-override`

**Comment by Miosame** [comment]
@decaffeinatedio does that remove the error for you entirely? or does it still happen at the first launch

**Comment by aemla** [comment]
Try to downgrade to puppeteer 14.3.0. It solved `TypeError: page._client.send is not a function` error for me.

**Comment by MohamadKh75** [comment]
Any updates?

**Comment by berstend** [comment]
This should now be fixed in the latest update

**Comment by decaffeinatedio** [comment]
Now working on my end, thanks @berstend !

**Comment by berstend** [comment]
Thanks for confirming, closing this ticket now :)

**Comment by adinvadim** [comment]
Dont fix for me with 15.3.0 and ghost-cursor
```
Falling back to JS scroll method TypeError: page._client.send is not a function
```

**Comment by berstend** [comment]
@adinvadim ghost-cursor has nothing to do with our project, raise that issue with them: https://github.com/Xetera/ghost-cursor

**Comment by alecellis1985** [comment]
const client = await page.target().createCDPSession();
await client.send('Emulation.clearDeviceMetricsOverride')

**Comment by Lovely-Ruby** [comment]
that is useful in 2024-02-19, thanks a lot
