### ISSUE TITLE
[Bug] Error get printed in the console when launching multiple instanced with StealthPlugin

### ISSUE THREAD

**Issue by philhk** [berstend/puppeteer-extra#658]
**Describe the bug**
When launching multiple puppeteer extra instances with StealthPlugin and both opening and closing them fast a error gets thrown in the console.
`Warning: Failure writing file C:\Users\letsp\AppData\Local\Temp\puppeteer_dev_profile-goDDS8\Default\Preferences {
  target: 'Profile',
  file: 'Preferences',
  contents: '{\n  "intl": {\n    "accept_languages": "en-US,en"\n  }\n}'
} [Error: ENOENT: no such file or directory, open 'C:\Users\letsp\AppData\Local\Temp\puppeteer_dev_profile-goDDS8\Default\Preferences'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\letsp\\AppData\\Local\\Temp\\puppeteer_dev_profile-goDDS8\\Default\\Preferences'
}`

**Code Snippet**

```javascript
for (let index = 0; index < 10; index++) {
    (async function redo() {
        const browser = await puppeteer
            .use(StealthPlugin())
            .launch()

        browser.close()

        redo()
    }())
}
```

**Versions**

The command doesn't work for me for some reason however I'm still gonna try to list the versions I used.
```
puppeteer@^15.0.1
puppeteer-extra@^3.3.0
puppeteer-extra-plugin@^3.2.0
puppeteer-extra-plugin-user-preferences@^2.3.1
puppeteer-extra-plugin-user-data-dir@^2.3.1
puppeteer-extra-plugin-stealth@^2.10.1
```

**Comment by berstend** [comment]
You need to use `addExtra` as mentioned in the `puppeteer-extra` readme :)
