### ISSUE TITLE
[Bug] Stealth is detected by cloudflare

### ISSUE THREAD

**Issue by elandorr** [berstend/puppeteer-extra#659]
This site is using cloudflare for testing:
https://nowsecure.nl/

puppeteer-stealth can't get through it.

puppeteer-extra-plugin-stealth: ^2.10.1 => 2.10.1
Node: 16.15.1

This one can, may be useful for figuring outhow:
https://github.com/ultrafunkamsterdam/undetected-chromedriver

**Comment by berstend** [comment]
Stealth is a complex topic, our [our discord server](https://github.com/berstend/puppeteer-extra/wiki/Scraping-Chat) is a better place to discuss these issues (the Github issue tracker is for concrete code related discussions). :)

**Comment by elandorr** [comment]
Thank you, but discord is a hard no-go. If you're interested, I can confirm that the linked repo can get the hardmode CF to pass. Have a nice weekend.

**Comment by berstend** [comment]
If undetected-chromedriver is passing that's accidental, they use a whole lot less stealth. Happy to discuss specific issues with code references (new issue would be best for that)
