### ISSUE TITLE
Add support for puppeteer-core

### ISSUE THREAD

**Issue by jtmilne** [berstend/puppeteer-extra#66]
Can we add a constructor option for using `puppeteer-core` instead of `puppeteer` to avoid the chromium download when connecting to a remote chromium instance?

**Comment by berstend** [comment]
Fix:

> according to ["puppeteer vs puppeteer-core"](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteer-vs-puppeteer-core) [](/GoogleChrome/puppeteer/blob/HEAD@{2019-09-29T16:37:13Z}/docs/api.md#puppeteer-vs-puppeteer-core) they have two main differences...
> 
> > To sum up, the only differences between puppeteer-core and puppeteer are:
> > 
> > * puppeteer-core doesn't automatically download Chromium when installed.
> > * puppeteer-core ignores all PUPPETEER_* env variables.
> 
> You can avoid downloading chrome using the [`PUPPETEER_SKIP_CHROMIUM_DOWNLOAD`](https://github.com/GoogleChrome/puppeteer/blob/v0.10.2/docs/api.md#environment-variables) [](/GoogleChrome/puppeteer/blob/HEAD@{2019-09-29T16:37:13Z}/docs/api.md#environment-variables) environment variable during installation. This makes `puppeteer` almost identical to `puppeteer-core` with the added benefit of convenient env vars.
> 
> e.g. `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1 npm install puppeteer`

:)

**Comment by bronson** [comment]
This doesn't work when someone on my team does a `git pull; yarn install`.

For me, this issue still exists.
