### ISSUE TITLE
[Bug] Firefox browser keeps crashing

### ISSUE THREAD

**Issue by TrixTM** [berstend/puppeteer-extra#661]
**Describe the bug**
  - So everything was working fine and a few days ago i started to get this error: browserType.launch: Protocol error (Browser.enable): Browser closed.
  - The firefox browser doesn't open, other browsers work perfectly, i manually opened the firefox browser from C:\Users\xCrysti\AppData\Local\ms-playwright\firefox-1225\firefox\firefox.exe and it opens without problems. 
  - This is the full error:
  - ERROR: The process "1668" not found.
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^
browserType.launch: Protocol error (Browser.enable): Browser closed.
==================== Browser output: ====================
<launching> C:\Users\xCrysti\AppData\Local\ms-playwright\firefox-1225\firefox\firefox.exe -no-remote -wait-for-browser -foreground -profile E:\Temp\playwright_firefoxdev_profile-RWwxYO -juggler-pipe -silent  
<launched> pid=1668
[out]
[out] Juggler listening to the pipe
[out] console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
[err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
[err] JavaScript error: resource://activity-stream/lib/ASRouterNewTabHook.jsm, line 61: TypeError: this._router is null
[out] console.error: Region.jsm: "Error fetching region" (new TypeError("NetworkError when attempting to fetch resource.", "chrome://juggler/content/NetworkObserver.js", 421))
[out] console.error: Region.jsm: "Failed to fetch region" (new Error("NO_RESULT", "resource://gre/modules/Region.jsm", 422))
[err]
[err] ###!!! [Child][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost
[err]
=========================== logs ===========================
<launching> C:\Users\xCrysti\AppData\Local\ms-playwright\firefox-1225\firefox\firefox.exe -no-remote -wait-for-browser -foreground -profile E:\Temp\playwright_firefoxdev_profile-RWwxYO -juggler-pipe -silent  
<launched> pid=1668
[out]
[out] Juggler listening to the pipe
[out] console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
[err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
[err] JavaScript error: resource://activity-stream/lib/ASRouterNewTabHook.jsm, line 61: TypeError: this._router is null
[out] console.error: Region.jsm: "Error fetching region" (new TypeError("NetworkError when attempting to fetch resource.", "chrome://juggler/content/NetworkObserver.js", 421))
[out] console.error: Region.jsm: "Failed to fetch region" (new Error("NO_RESULT", "resource://gre/modules/Region.jsm", 422))
[err]
[err] ###!!! [Child][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost
[err]
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at Connection.sendMessageToServer (C:\Users\xCrysti\Desktop\HCaptcha Solver\node_modules\playwright-core\lib\client\connection.js:69:15)
    at Proxy.<anonymous> (C:\Users\xCrysti\Desktop\HCaptcha Solver\node_modules\playwright-core\lib\client\channelOwner.js:44:61)
    at C:\Users\xCrysti\Desktop\HCaptcha Solver\node_modules\playwright-core\lib\client\browserType.js:61:73
    at BrowserType._wrapApiCall (C:\Users\xCrysti\Desktop\HCaptcha Solver\node_modules\playwright-core\lib\client\channelOwner.js:72:34)
    at BrowserType.launch (C:\Users\xCrysti\Desktop\HCaptcha Solver\node_modules\playwright-core\lib\client\browserType.js:52:21)
    at PlaywrightExtra._launchOrConnect (C:\Users\xCrysti\Desktop\HCaptcha Solver\node_modules\automation-extra\dist\index.cjs.js:444:52)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PlaywrightExtra._launch (C:\Users\xCrysti\Desktop\HCaptcha Solver\node_modules\automation-extra\dist\index.cjs.js:402:16)

**Code Snippet**

const { firefox } = require('playwright-extra')
const HumanizePlugin = require('@extra/humanize')
firefox.use(
  HumanizePlugin({
    mouse: {
      showCursor: true // Show the cursor (meant for testing)
    }
  })
)
firefox.launch({headless: false, 
        proxy: {
            server: proxyserver, 
            username: proxyuser, 
            password: proxypass
            }
    }).then(async browser => {
    // context
    const page = await browser.newPage()
    await page.route('https://site.com/')

**Versions**

  System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 14.71 GB / 23.91 GB
  Binaries:
    Node: 16.15.1 - F:\NodeJS\node.EXE
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.11.0 - F:\NodeJS\npm.CMD
  npmPackages:
    @extra/humanize: ^4.2.2-next.616 => 4.2.2-next.616+846b2f2
    @playwright/test: ^1.22.2 => 1.22.2
    axios: ^0.27.2 => 0.27.2
    node-fetch: ^2.6.1 => 2.6.7
    playwright: 1.8.0 => 1.8.0
    playwright-extra: ^4.2.1-next.616 => 4.2.1-next.616+846b2f2
    playwright-firefox: ^1.22.2 => 1.22.2-->

**Comment by berstend** [comment]
Hey, the playwright beta version you're using outdated - a new version is being released soon: https://github.com/berstend/puppeteer-extra/issues/454#issuecomment-1169678855
