### ISSUE TITLE
[Bug] I want to know how to solve reCaptcha with no submit button.

### ISSUE THREAD

**Issue by kurohoan** [berstend/puppeteer-extra#663]
In the following page, solveRecaptchas() is used, but unlike a regular reCaptcha, the page transition trigger does not fire after the captcha is released because there is no submit button.
How should this be handled in this case?

https://www.omni7.jp/cart/OP_OSE0100_001_01.do

**Comment by berstend** [comment]
As mentioned in the recaptcha plugin readme:
> After solving the reCAPTCHAs the plugin will automatically detect and trigger their [optional callback](https://developers.google.com/recaptcha/docs/display#render_param). This might result in forms being submitted and page navigations to occur, depending on how the site owner implemented the reCAPTCHA.

If you think you experience a bug let me know (please provide debug logs as mentioned in the readme) :)

Closing for now

**Comment by kurohoan** [comment]
https://github.com/berstend/puppeteer-extra/blob/master/packages/puppeteer-extra/readme.md

Specifically, the symbol changes to purple after detecting a recaptcha and then stops.
The code seems to be proceeding to the next process after solveRecaptchas(), but the redirection process after resolving the captcha is not done on screen, so it ends with an error at the point where the next element is detected.
I read the readme above but could not find where the error log is output.
