### ISSUE TITLE
[Bug] Package playwright-extra v4.3 breaks on node v10

### ISSUE THREAD

**Issue by jojovem** [berstend/puppeteer-extra#670]
Hi ppl,

The node engine version for the playwright-extra is set to 8:
https://github.com/berstend/puppeteer-extra/blob/5b39abb432e3d86675a899f3a5ba351d11b7b7ba/packages/playwright-extra/package.json#L38-L40

but new code in the v4.3 breaks with node v10.
One example of breaking code is:

https://github.com/berstend/puppeteer-extra/blob/5b39abb432e3d86675a899f3a5ba351d11b7b7ba/packages/playwright-extra/src/helper/loader.ts#L19

It uses the Object.fromEntries that is only available in node v12.

I observed that the github workflows use the node v14 as its minimum version.
Maybe its better to upgrade all node engine versions to "node": ">=14"?

Only for reference, our application crashed after upgrading from the v4.2.1-next.616 (now deprecated) to the v4.3. 
It is a legacy application using node v10.

**Comment by berstend** [comment]
I tried it:
```
You are running Node.js 10.24.1.
Playwright requires Node.js 12 or higher. 
Please update your version of Node.js.
```

**Comment by berstend** [comment]
@jojovem this makes no sense, even the first playwright version `0.9.1` requires Node.js > 14
