### ISSUE TITLE
[Bug] puppeteer-extra-plugin-stealth causes newPage to hang indefinitely

### ISSUE THREAD

**Issue by CoyDurie** [berstend/puppeteer-extra#676]
I believe this is similar/the same as #637 Running in AWS Lambda image from `amazon/aws-lambda-nodejs:14`, the following works fine
  
```js
const chromium = require('@sparticuz/chrome-aws-lambda');
const { addExtra } = require('puppeteer-extra')
const puppeteerExtra = addExtra(chromium.puppeteer)
const AdblockerPlugin = require('puppeteer-extra-plugin-adblocker')
const BlockResourcesPlugin = require('puppeteer-extra-plugin-block-resources')

const plugins = [
  AdblockerPlugin(),
  BlockResourcesPlugin({blockedTypes: new Set(['image','media'])})
];
const browser = await puppeteerExtra.launch({
  args: chromium.args,
  defaultViewport: chromium.defaultViewport,
  executablePath: await chromium.executablePath,
  headless: chromium.headless
});
for (const plugin of plugins) {
    await plugin.onBrowser(browser);
}
const page = await browser.newPage();
for (const plugin of plugins) {
    await plugin.onPageCreated(page);
}
await page.goto(url, {waitUntil: 'networkidle2'});
```

This is trimmed from the rest of the function which is just saving a screenshot of the requested page to an S3 bucket.
  
However, adding `puppeteer-extra-plugin-stealth` causes the script to hang indefinitely on `const page = await browser.newPage();` to whatever timeout is set for the lambda, regardless of timeout or ram allowed. Changing the above code to this, results in the hang:  
  
```js
const chromium = require('@sparticuz/chrome-aws-lambda');
const { addExtra } = require('puppeteer-extra')
const puppeteerExtra = addExtra(chromium.puppeteer)
const AdblockerPlugin = require('puppeteer-extra-plugin-adblocker')
const BlockResourcesPlugin = require('puppeteer-extra-plugin-block-resources')
const StealthPlugin = require('puppeteer-extra-plugin-stealth')

const plugins = [
  AdblockerPlugin(),
  StealthPlugin(),
  BlockResourcesPlugin({blockedTypes: new Set(['image','media'])})
];
const browser = await puppeteerExtra.launch({
  args: chromium.args,
  defaultViewport: chromium.defaultViewport,
  executablePath: await chromium.executablePath,
  headless: chromium.headless
});
for (const plugin of plugins) {
    await plugin.onBrowser(browser);
}
const page = await browser.newPage();   //execution hangs here
for (const plugin of plugins) {
    await plugin.onPageCreated(page);
}
await page.goto(url, {waitUntil: 'networkidle2'});
```

Package versions used in this are:
```js
        "@sparticuz/chrome-aws-lambda": "^14.4.1",
        "puppeteer-core": "^14.4.1",
        "puppeteer-extra": "^3.3.0",
        "puppeteer-extra-plugin-adblocker": "^2.13.1",
        "puppeteer-extra-plugin-block-resources": "^2.4.1",
        "puppeteer-extra-plugin-stealth": "^2.10.4"
```  
  
There is no relevant log/debug data that I know of to include, the error that results is simply a timeout due to the newPage() never returning.

**Comment by CoyDurie** [comment]
After further testing I think it may be the `plugin.onPageCreated(page)` that's actually hanging, not `browser.newPage()`, but I'd need some guidance on how to verify specifically where the failure is happening if no one is able to reproduce it.

**Comment by berstend** [comment]
Is there a specific reason you're calling thr onBrowser and onPage handlers manually? This is done automatically by the plugin framework as long as `.newPage()` is being used 🤔

**Comment by CoyDurie** [comment]
It's entirely possible I'm just dumb, if I don't do that (as below, unless I'm misunderstanding) none of the plugins are actually being used, the screenshots have ads - so I'm pretty sure adblock isn't running, and bot detection tests fail so I'm pretty sure stealth isn't running.
```js
const browser = await puppeteerExtra.launch({
  args: chromium.args,
  defaultViewport: chromium.defaultViewport,
  executablePath: await chromium.executablePath,
  headless: chromium.headless
});
/*for (const plugin of plugins) {
    await plugin.onBrowser(browser);
}/*
const page = await browser.newPage();
/*for (const plugin of plugins) {
    await plugin.onPageCreated(page);
}
await page.goto(url, {waitUntil: 'networkidle2'});*/
```  
  
Am I just completely misunderstanding how I should be loading plugins?

**Comment by berstend** [comment]
> Am I just completely misunderstanding how I should be loading plugins?

Kinda 😄 I just noticed you're not using `puppeteerExtra.use(plugin)`, which is the main/only way to load plugins

**Comment by berstend** [comment]
So in your case it'd be:
```js
const chromium = require('@sparticuz/chrome-aws-lambda');
const { addExtra } = require('puppeteer-extra')
const puppeteerExtra = addExtra(chromium.puppeteer)

const AdblockerPlugin = require('puppeteer-extra-plugin-adblocker')

puppeteerExtra.use(AdblockerPlugin())

const browser = await puppeteerExtra.launch()
// (...)
```

PS: does lambda support top-level `await`?

**Comment by berstend** [comment]
Ah, `Using with chrome-aws-lambda` doesn't load in any plugins - maybe that's the source of the confusion. Thought that part was clear with all the other examples :)

**Comment by CoyDurie** [comment]
> Kinda 😄 I just noticed you're not using `puppeteerExtra.use(plugin)`, which is the main/only way to load plugins

😒... well... that explains a lot haha.  
  
>PS: does lambda support top-level await?  
  
Yes  
  
>Ah, Using with `chrome-aws-lambda` doesn't load in any plugins - maybe that's the source of the confusion. Thought that part was clear with all the other examples :)  
  
I must've entirely missed that, maybe by choice. My only defense is I think - although I can't find it now - that method came from an example specifically trying to use puppeteer-extra and chrome-aws-lambda together.  
  
There is some weirdness though, using the janky way originally listed, it *does* work a lot of the time, just not consistently. Using `.use()` it sort of flips that around, it fails the majority of the time by just timing out again although not on loading plugins anymore, but... works totally fine sometimes. It also seems to be using the plugins mostly, https://i.imgur.com/F60LPjY.png the only test here it's failing is for the webdriver, that's with everything loaded via `.use()`, compared to loading all plugins by manually calling the handlers for onBrowser and onPage, https://i.imgur.com/rkkKnV7.png which passes completely.  
  
Seems like it's so close to working, just beyond my ability to figure out 😅

**Comment by berstend** [comment]
At this point I'm assuming user error, sorry 😅 

Try with a more minimal code that only loads one plugin in and confirm that's working.
There's also debug logging that can be enabled (explained in the readme) to take the guess work out of this.

This might be better suited for our discord community (linked in the wiki).

Feel free to create a new issue if you've found a reproducible bug :)
