### ISSUE TITLE
Fingerprint difference between MacOs and Linux Ubuntu

### ISSUE THREAD

**Issue by lolo169** [berstend/puppeteer-extra#68]
Hi,

I'm developing a puppeteer script using puppeteer-extra and puppeteer-extra-plugin-stealth to scrap some datas.
Running that script under MacOS is successfull but it is not with Ubuntu.

Is there a fingerprint difference between MacOs and Ubuntu?
May it be a problem of version? 

Thanks for your help
Laurent

**Comment by shirshak55** [comment]
finger print is calculated on basis of ua also and there are many several factor. U can change fingerprint by changing ua and many other stuff.

**Comment by lolo169** [comment]
Yes, I rotate UA + Accept_language + I use StealthPlugin. 
Then running the same code of Ubuntu and MacOs gives you different result.

**Comment by shirshak55** [comment]
lol is it how did u calculated fingerprints?

**Comment by lolo169** [comment]
??

**Comment by shirshak55** [comment]
i mean how did u calculated fingerprints?

**Comment by lolo169** [comment]
Sorry I think I'm not clear.
I wrote a script to scrap data.
Running that script from Ubuntu is not successfull but it is OK from  MacOS.
As I use Puppeteer + stealth + I rotate UA + Accept-Language: 
I'm asking me how it is possible to detect that? 
Is there differences with Puppeteer between various OS?

**Comment by shirshak55** [comment]
i don't think so. What u can do is like check request header and check some suspicious request. May be u get a clue what is causing u trouble. But I don't think there is difference between osx browser and ubuntu chrome except UA.

**Comment by Warren772** [comment]
Even if you change your browser user-agent, if you run the "window.navigator.platform" javascript command, your OS be exposed and if this differs from the spoofed user-agent, will trigger red flags on the website.

**Comment by shirshak55** [comment]
u can change that right?

**Comment by Warren772** [comment]
Unfortunately, it's a read-only javascript property. If you want to emulate different user agents, it would be advantageous to hook them with the same OS, as to not trigger flags.

**Comment by shirshak55** [comment]
@Warren772 no .

```
Object.defineProperty(navigator, "platform", {
      get: () => "Mozilla"
    })
```

For more details see https://github.com/shirshak55/scrapper-tools/blob/master/src/fastPage/pageStealth.ts

**Comment by Warren772** [comment]
Using "Object.getOwnPropertyDescriptors(navigator)" will expose that you overriden these methods.

**Comment by shirshak55** [comment]
really?
```
Object.defineProperty(navigator, "platform", {
      get: () => "Mozilla"
    })

Object.getOwnPropertyDescriptors = () => ({});
```

**Comment by shirshak55** [comment]
@Warren772 and let me know what result u get :)

**Comment by berstend** [comment]
Please checkout `v2.4.0` of the stealth plugin ([Changelog](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth#v240)) which contains a boat load of other fixes as well. :)

Closing this for now, please open a new issue if you experience any issues with the new release.
