### ISSUE TITLE
[Bug] await page.authenticate doesnt work when puppeteer is packaged into an executable

### ISSUE THREAD

**Issue by TrustyJar** [berstend/puppeteer-extra#681]
I keep getting err_http_response_code_failure whenever using user:pass proxies with puppeteer (when it is packaged into an exe). Proxies work fine when the IP is whitelisted, but only then. Anyone else having this issue?

Compiling my file with https://www.npmjs.com/package/pkg

**Comment by berstend** [comment]
Is this a puppeteer-extra issue or puppeteer in general? If it's the latter this question is better suited for our discord :)

**Comment by TrustyJar** [comment]
> Is this a puppeteer-extra issue or puppeteer in general? If it's the latter this question is better suited for our discord :)

Its with puppeteer in general. I posted here since I am using puppeteer-extra imports. I will take a look in the Discord to see if anyone else has been having the same problem. Thanks!
