### ISSUE TITLE
C# port of this library

### ISSUE THREAD

**Issue by shravan2x** [berstend/puppeteer-extra#69]
I found this library useful and am working on a 1:1 port over to .NET at https://github.com/shravan2x/PuppeteerSharp.Extra. The license of the new repo will also be MIT. I'll include a credit to you (@berstend) along with a link back to this repo as soon as I set up a README.

Some hacks will likely be too difficult to port like the override of the private function at https://github.com/berstend/puppeteer-extra/blob/master/packages/puppeteer-extra/index.js#L173. I'll try to include warnings for these cases.

So far, I've ported the plugin core and the stealth plugin. They seem to work.

**Comment by berstend** [comment]
@shravan2x that sounds great :) I'll myself will refactor most parts of this project to TS, which shares some similarities to C# in my opinion. :)

**Comment by quelibrio** [comment]
wow amazing job Although its simple implementation worked great for my problem
