### ISSUE TITLE
[Bug] detected by adscore.com as a bot

### ISSUE THREAD

**Issue by CarmenLexa** [berstend/puppeteer-extra#692]
I have been trying for hours to jump to adscore but I can't do it.
I found a script here
https://github.com/chris124567/puppeteer-bypassing-bot-detection/blob/master/apply-evasions.js
but it doesn't seem to work any more so I took on the task of creating my own but still no success
does anyone know how to solve this problem with adscore?

**Comment by berstend** [comment]
This is not a bug report, here we discuss code :) There's a discord server for more general discussions.
