### ISSUE TITLE
[Feature] Add proxy options for recaptcha plugin

### ISSUE THREAD

**Issue by bert-w** [berstend/puppeteer-extra#697]
I want to send additional options to the 2captcha provider for the recaptcha plugin. Something like:

```js
await this.page.solveRecaptchas({
    proxy: 'abc:def@127.0.0.1:8000'
});
```
I can't find it in the current code if this is even possible. The implementation on https://github.com/berstend/puppeteer-extra/blob/master/packages/puppeteer-extra-plugin-recaptcha/src/provider/2captcha-api.ts is quite frankly unreadable, mostly due to the callbacks, indentations and repetitive usage of `require('https')` to make http requests. I'd be willing to rewrite some of this but it's going to be a pain to do so.

**Comment by berstend** [comment]
You want to instruct 2captcha to use a specific proxy to solve the captcha right?
this is already implemented: https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-recaptcha#proxies

I'm aware that file is messy a rewrite is in the works 😄

**Comment by berstend** [comment]
If you wish the 2captcha API communication to be done through a proxy you can use this as a workaround until I released the better and more flexible API client:
https://www.npmjs.com/package/global-tunnel
