### ISSUE TITLE
Unable to manage multiples context in one browser in heroku

### ISSUE THREAD

**Issue by jkune** [berstend/puppeteer-extra#70]
Hi all!

I'm encountering problems while using the same browser with multiples contexts (one context per page). It seems like all the context shared the same information so i can not login with two different users at the same time.

It's important to say that this problem occurs ONLY while using puppeteer-extra in Heroku. When debbuging in my PC before deploying to heroku all is fine in Visual Studio. 

I'm using the following Heroku buildpack:  https://github.com/jontewks/puppeteer-heroku-buildpack

¿Any idea why puppeter-extra is not working properly with this buildpack in Heroku?

Actually puppeter (no extra) is working fine with contexts with the buildpack but does not prevent detection :(

Here is an example that contexts do not work properly in the same browser.

Thanks!
	
```
(async () => {
    const puppeteer = require("puppeteer-extra");
    const pluginStealth = require("puppeteer-extra-plugin-stealth");

    var browser = null;

    puppeteer.use(pluginStealth());

    function init() {
        var botCredentials = [{username: '', password: '***'}, {username: '', password: '***'}]

        botCredentials.forEach((credentials) => {
            var bot = new Bot(credentials);
            
            bot.init();
        });
    }

    /**
    * Bot instance
    * @param {*} options 
    */
    function Bot(credentials = {}) {
        var credentials = credentials;
        var page = null;
        var context = null;

        this.init = async () => {
            page = await newPage();
            // DO STUFF LIKE LOGIN IN A WEBSITE. 
            // ONLY THE FIRST BOT WILL NEED TO SIGN IN. THE CONTEXTS ARE SHARED BECAUSE OF SOME REASON :(
        }

        /**
        * Get browser. Create one if not exists
        */
        async function getBrowser() {
            let options = {
                args: ['--no-sandbox', '--disable-setuid-sandbox'],
            }
            return await puppeteer.launch(options);
        }

        /**
        * Get a new page in a new context in the browser
        */
        async function newPage() {
            if (!browser) {
                browser = await getBrowser();
            }
            context = await browser.createIncognitoBrowserContext();
            return context.newPage();
        }
    }

    init();
})()
```

**Comment by jkune** [comment]
Related to this pull request that it is still opened.

https://github.com/berstend/puppeteer-extra/pull/47

**Comment by berstend** [comment]
This should be fixed with the latest releases, please ping if that's not the case. :)
