### ISSUE TITLE
Recaptcha V3 score returns 0.1 with stealth-plugin

### ISSUE THREAD

**Issue by opclient** [berstend/puppeteer-extra#76]
V3 captcha returns 0.1-0.3 score.
![Screenshot_2](https://user-images.githubusercontent.com/30980283/69639417-0ea0ac00-108f-11ea-8dfa-7c1357239818.jpg)

**Comment by berstend** [comment]
Hey there, as mentioned in the documentation the reCAPTCHA score (and especially  this test page) depend on a bunch of different things. :)

What IP are you using, a data center or residential one?

Also the score doesn't really matter as you will run into captchas as soon as you crawl more than 3 pages 😄 That's what the `recaptcha` plugin is for.

**Comment by berstend** [comment]
Please checkout `v2.4.0` of the stealth plugin ([Changelog](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth#v240)) which contains a boat load of other fixes as well. :)

Closing this for now, please open a new issue if you experience any issues with the new release.

**Comment by tackelua** [comment]
Please check with the web recaptcha score, now score is 0.1
residential IP from FTTH
https://recaptcha-demo.appspot.com/recaptcha-v3-request-scores.php
puppeteer-extra: 3.1.13
puppeteer-extra-plugin-stealth: 2.4.14

<img width="884" alt="Screen Shot 2020-07-25 at 22 12 43" src="https://user-images.githubusercontent.com/22250123/88460096-f904b000-cec3-11ea-95ae-f4668c6bce54.png">
