### ISSUE TITLE
Hitting CloudFlare block 100% of the time (using the latest versions for everything)

### ISSUE THREAD

**Issue by korablin** [berstend/puppeteer-extra#783]
Hitting CloudFlare 100% of the time.
Using virtual `xvfb & headless: false` doesn't help.
Clicking on the `Verify you are human` ofc doesn't help either.

**Comment by arnagar** [comment]
I'm not an expert in the area, but it's worth noting that it might be that CF just identifies the ip as datacenter ip so it automatically blocks the request.

**Comment by korablin** [comment]
Apparently, there are some cloud providers who are blacklisted by Cloudflare. I am closing this issue. To whoever is hitting this: try using a proxy - if it helps, it means your IP is blacklisted.
