### ISSUE TITLE
Inner and outer width/height inconsistency

### ISSUE THREAD

**Issue by flunkman** [berstend/puppeteer-extra#79]
Hi there!

I may have spotted an issue with the stealth plugin.

When I use 'await page.setViewport({ width: 800, height: 600 })' I get this:

![Screen Shot 11-27-19 at 10 19 PM](https://user-images.githubusercontent.com/58262513/69797773-94784080-11d0-11ea-9f69-96d610274551.PNG)

But if I raise the viewport dimensions, for instance 'await page.setViewport({ width: 1920, height: 1080 })' here is what I get:

![Screen Shot 11-27-19 at 10 17 PM](https://user-images.githubusercontent.com/58262513/69797794-9fcb6c00-11d0-11ea-90fd-3907c8778aa9.PNG)

As you can see several values like the outer width/height remains at 800x600 no matter what. Since those are lower than the inner width/height, some sites detect my headless Chrome and block it due to this simple test.

Are they hardcoded values or can we change them programmatically?

**Comment by berstend** [comment]
I remember that there was a discussion about this on the puppeteer issue tracker, If I recall correctly it matters when the viewport is set or something. I don't have time to look into this right now but please report any findings you might have :)

**Comment by berstend** [comment]
@flunkman just found this through google:
```js
const browser = await puppeteer.launch({defaultViewport: null});
```
> Set the defaultViewport option to null as above to disable the 800x600 resolution. It takes the max resolution then.

**Comment by berstend** [comment]
If this works we should seriously start a wiki with those stealth tips. 😄

**Comment by berstend** [comment]
I've added this to the new wiki: https://github.com/berstend/puppeteer-extra/wiki/Common-stealth-issues

**Comment by flunkman** [comment]
Just tested it and it works perfectly!

**Comment by flunkman** [comment]
The result is the same with 'defaultViewport: null' but I've managed to solve this issue by adding the '--window-size=1920,1080' argument to puppeteer.launch.

**Comment by LeninZapata** [comment]
> The result is the same with 'defaultViewport: null'...
> 
> But I've managed to solve this issue by adding the '--window-size=1920,1080' argument to puppeteer.launch.

This doesn't work for me
![image](https://github.com/berstend/puppeteer-extra/assets/42600954/a4c103c2-9d02-41c3-af91-e8e25e675335)
