### ISSUE TITLE
Stealth does not pass test

### ISSUE THREAD

**Issue by kaiserdj** [berstend/puppeteer-extra#80]
Using the example code and changing the url, for: [this](https://arh.antoinevastel.com/bots/areyouheadless)

Detect that it is headless

**Comment by berstend** [comment]
@kaiserdj would you mind adding more details? this is github after all :)

**Comment by berstend** [comment]
E.g. you could check which test is failing (they use https://github.com/antoinevastel/fpscanner).

**Comment by kaiserdj** [comment]
The code I use is the one that gives as an example. I have tried many tests but all give correct except this:
```
const puppeteer = require("puppeteer-extra")

const pluginStealth = require("puppeteer-extra-plugin-stealth")
puppeteer.use(pluginStealth())


puppeteer.launch({ headless: true }).then(async browser => {
  const page = await browser.newPage()
  await page.setViewport({ width: 800, height: 600 })
  await page.goto("https://arh.antoinevastel.com/bots/areyouheadless")
  await page.waitFor(5000)
  await page.screenshot({ path: "testresult.png", fullPage: true })
  await browser.close()
})
```
Result: 
![testresult](https://user-images.githubusercontent.com/5487950/69813005-9ef70200-11f1-11ea-940d-9f0509617fc0.png)

**Comment by berstend** [comment]
Ok thanks :) I'm busy rewriting the core to TypeScript currently (#21) but afterwards I want to cleanup and redo all stealth functionality.

I'm closing this in favor of #78 - make sure to follow that ticket to get notified once the stealth issues have been fixed.
