### ISSUE TITLE
[Feature] Expose registerCustomQueryHandler()

### ISSUE THREAD

**Issue by jaredcat** [berstend/puppeteer-extra#805]
I want to use: [puppeteer.registerCustomQueryHandler('shadow', QueryHandler);](https://github.com/webdriverio/query-selector-shadow-dom/tree/main/examples/puppeteer)
To help with shadow DOM elements but `pupeteer.registerCustomQueryHandler()` isn't exposed on PupeteerExtra class

**Comment by fmoessle** [comment]
Any updates?

**Comment by brunofmeurer** [comment]
Any updates?

**Comment by davidfant** [comment]
Did you end up finding a solution or workaround?

**Comment by jaredcat** [comment]
@fmoessle @davidfant 
It looks like the method has been deprecated, and you should use the static member now.

This is what I'm trying out: 
```javascript
import { Puppeteer } from 'puppeteer';
import puppeteer from 'puppeteer-extra';

const {
  QueryHandler,
} = require('query-selector-shadow-dom/plugins/puppeteer');
Puppeteer.registerCustomQueryHandler('shadow', QueryHandler);
```
