### ISSUE TITLE
Recaptcha in iFrame

### ISSUE THREAD

**Issue by svenadlung** [berstend/puppeteer-extra#83]
I wonder if there is a way how to use `puppeteer-extra-plugin-recaptcha` for a Recaptcha which is in within an iFrame (I do not mean recaptchas iFrame). `solveRecaptchas()` method is registered only in `page`s-context. Not sure how to use it with frames.

Any idea?

**Comment by berstend** [comment]
Good point! I'm checking the puppeteer docs right now to see if there's a good hook for this.

**Comment by berstend** [comment]
Alright, seems to be just a matter of looping through `page.mainFrame().childFrames()`.

What would be the better default, checking all iframes or only when opting-in?

Currently leaning towards an `allFrame: trues` plugin option as the default for better out of the box experience. :)

**Comment by berstend** [comment]
Or would it be better to keep it manual for the user so they can choose in which frame they try to solve captchas?

**Comment by svenadlung** [comment]
@berstend thx for your quick reply. For me it doesn't matter actually. I guess it's cant be too bad to check all frames and keeps the plugin easy to use. Maybe add a manual option as well - but keep scanning all frames by default?

**Comment by berstend** [comment]
I've added the custom captcha methods to potential Frames as well:

```js
  for (const frame of page.mainFrame().childFrames()) {
    await frame.solveRecaptchas()
  }
```

Will tests this a bit more and push a new release soon :)

**Comment by svenadlung** [comment]
Wow, perfect! Can't wait to test it as well. Thx for your effort!

**Comment by berstend** [comment]
@svenadlung Frames are now supported with `puppeteer-extra-plugin-recaptcha@3.1.5`.

Documentation: https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-recaptcha#solving-captchas-in-iframes

Please ping you experience any issues with the new frame support :)

**Comment by svenadlung** [comment]
Awesome! Works like a charm. Thank you so much.

**Comment by eloisamec** [comment]
I'm having issues with hCaptcha inside a frame. It identifies, but is taking very long to break it. I don't know if it's normal.
I'm trying to break in a login link: https://login.globo.com/login/3981?url=https%3A%2F%2Foglobo.globo.com%2F
The main code for solving hCaptcha:

```
await page.waitForResponse('https://login.globo.com/assets/partials/salutation.html', {delay:1000});
await page.type("input[name=login]", "username", {delay:40});
await page.type("input[type=password], "password", {delay:40});
await page.waitForTimeout(1000);
await page.solveRecaptchas();
await page.click("button[type=submit]");
```
