### ISSUE TITLE
authChallengeResponse required

### ISSUE THREAD

**Issue by antonioiliev** [berstend/puppeteer-extra#86]
Hi,

Just updated puppeteer-extra (v3.1.6) and puppeteer-extra-plugin-stealth (v2.4.0) and got the following error on a previously working code

`(node:18804) UnhandledPromiseRejectionWarning: Error: Protocol error (Network.continueInterceptedRequest): authChallengeResponse required.
    at \node_modules\puppeteer\lib\Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (\node_modules\puppeteer\lib\Connection.js:182:12)
    at CDPSession.<anonymous> (\node_modules\puppeteer-extra-plugin-stealth\evasions\accept-language\index.js:35:22)`

I am not intercepting a request from puppeteer at that particular piece of code, so I do not know whether it is a bug in puppeteer-extra-plugin-stealth or whatever triggers the error is designed as a code feature and I need to adapt my code?

This is how I use the plugin -
` const puppeteer = require("puppeteer-extra");
const pluginStealth = require("puppeteer-extra-plugin-stealth")();
puppeteer.use(pluginStealth);`

Any suggestions?

**Comment by berstend** [comment]
I think it's the new `accept-language` header plugin: we had to use CDP to intercept requests to set the header properly and I remember seeing that there was a special case for basic auth responses.

I'll look into it, in the meantime you can just disable `accept-language` evasions (documented in the readme how to do that).

**Comment by berstend** [comment]
Like this:

```js
pluginStealth.enabledEvasions.delete('accept-language')

```

**Comment by berstend** [comment]
@antonioiliev what's your puppeteer version?

Apparently quite a lot of issues have been fixed recently in this regard:
https://github.com/puppeteer/puppeteer/issues/627
https://github.com/puppeteer/puppeteer/issues/3471

**Comment by berstend** [comment]
@antonioiliev I'll look into not making the plugin throw on auth challenge responses but it seems you would need to authenticate regardless of my fix?

https://github.com/puppeteer/puppeteer/issues/426#issuecomment-333287858

**Comment by berstend** [comment]
Fixed in `puppeteer-extra-plugin-stealth` `2.4.1`. Please ping if you still encounter problems. :)

**Comment by antonioiliev** [comment]
Thank you for the quick action. Just updated Puppeteer to v2.0.0 and puppeteer-extra-plugin-stealth to v2.4.2. Issues have been fixed.
