### ISSUE TITLE
Stealth still not done :D

### ISSUE THREAD

**Issue by shirshak55** [berstend/puppeteer-extra#92]
I know its hard but today i found when i go to gmail registration page it has this:

![image](https://user-images.githubusercontent.com/8097377/70297452-3376eb00-1816-11ea-8018-58569c843543.png)

But on chrome it don't produce some error message it means they are still detecting headless right?

BTW I have no intention to create gmail account i am just testing stealth plugin with various other stuff like distil network, cloudflare etc.

**Comment by berstend** [comment]
Interesting, thanks for providing the devtools output. Seem like on or more of the evasion is not doing it's job perfectly. I'll look into that as soon as I find the time.

Note: The current evasions are a mix of very old one I copy pasted from other places and custom written (and better tested) more sophisticated ones. I'm slowly rewriting the old ones with better techniques that should be less error prone. :)

**Comment by berstend** [comment]
FWIW this issue has been fixed we the recent updates:

![image](https://user-images.githubusercontent.com/1368633/71830195-86a6bc80-30a6-11ea-965f-4b45e6abd374.png)

**Comment by shirshak55** [comment]
@berstend by the way i am using some of your code so i want to fully credit your work whats the best way? Adding name is read me is fine or per file etc?
https://github.com/shirshak55/scrapper-tools/blob/master/src/fastPage/pageStealth.ts
