### ISSUE TITLE
Spoof fonts

### ISSUE THREAD

**Issue by momala454** [berstend/puppeteer-extra#95]
do you know how to display the emoticons like on windows, example this page :
https://eosrei.github.io/emojione-color-font/full-demo.html

on linux i see mostly garbage, on windows i see all colored drawings.
I installed all fonts from c/windows/fonts to the server but it doesn't change anything.

installing fonts for linux will show the emojis but i need them to show exactly (due to canvas fingerprinting) as i woule like to spoof windows but windows have colorful specific emojis

**Comment by berstend** [comment]
I don't think this will work. To my knowledge font rendering (anti aliasing, etc) is highly OS dependent and not just about fonts. Please ping if you find a way.
