### ISSUE TITLE
Why webgl render "Intel Iris OpenGL Engine"

### ISSUE THREAD

**Issue by momala454** [berstend/puppeteer-extra#97]
Hi,

why use the renderer "Intel Iris OpenGL Engine" as based on https://amiunique.org/fp it's only  0.40% common, while "Google SwiftShader" is 2.60% on the last 30 days
maybe there is a more common value even ?

Also webgl vendor "intel inc" is 5.22% while "Google Inc." is 34.93%

**Comment by berstend** [comment]
Closing in favor of #101
