### ISSUE TITLE
Spoof keyboard layout ?

### ISSUE THREAD

**Issue by momala454** [berstend/puppeteer-extra#98]
Hi
i have  there https://amiunique.org/fp detected as keyboard layout "other" (9.52%)

Qwerty is 8.81%
azerty is 0.91%
on 30 day

what do you think about that "other", is it something that should be detected as qwerty even if it has less % ?

**Comment by berstend** [comment]
No idea. How are keyboard layouts detected? Please keep in mind that the primary purpose of the stealth plugin is to hide headless usage, not anti-fingerprinting measures :)

**Comment by berstend** [comment]
Closing in favor of #101

**Comment by M-Abubakr** [comment]
@momala454 were you able to resolve this ?

**Comment by momala454** [comment]
> 
> 
> @momala454 were you able to resolve this ?

didn't looked into it since then

**Comment by m-abu** [comment]
what about the mediaDevices ? were you able to spoof these at that time ? 
I am currently struggling with these two attributes.

**Comment by momala454** [comment]
didn't neither
