### ISSUE TITLE
Screen available height

### ISSUE THREAD

**Issue by momala454** [berstend/puppeteer-extra#99]
On
https://amiunique.org/fp

it shows a 100% screen available height (1080 if 1920 x 1080) while on normal windows there is a 40 pixels taskbar.

How do i spoof the taskbar height ?

**Comment by berstend** [comment]
Did you check the pptr documentation, viewport, etc?

**Comment by berstend** [comment]
Please let me know what you already tried and what didn't work.

**Comment by momala454** [comment]
i tried Target.createTarget with a specific height and setDeviceMetricsOverride with specific height and screenheight

but it doesn't seems to change the "available height", it's always set at the height defined by the command line arguments windowSize

**Comment by momala454** [comment]
i also tried Browser.setWindowBounds but it doesn't seems to impact the values neither, or i'm wrongly using them

**Comment by berstend** [comment]
Hmm, can you create a small test case for this? e.g. a complete NodeJS script that uses the settings you've mentioned and runs `page.evaluate` with the method that returns the pixels in question?

**Comment by momala454** [comment]
i am not using nodejs so i don't have a nodejs code to share

**Comment by berstend** [comment]
Mhm? What does your setup look like - you're using puppeteer right?

**Comment by momala454** [comment]
no i'm not using pupeteer, i'm using a php library https://github.com/chrome-php/headless-chromium-php/

**Comment by berstend** [comment]
Ok :) I don't have time to work an all edge cases (I don't make money with this open source project) so in some instances (like this one) I need to ask for some prep work to be done by others, like setting up a test case I can quickly work against.

As this is not `puppeteer-extra` related I suggest stackoverflow or similar to discuss this topic. :)

Closing for now, let me know if this should be handled by puppeteer-extra.

**Comment by pgamaster** [comment]
Sorry for bumping the topic, did you resolve the issue? When using DevTools https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setDeviceMetricsOverride - you can't set JS screens param - screen.availHeigh

On a real Chtome you will get something like: height: 1200 and availHeight: 1160
On emulation both params will be the same: 1200
